//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.Misc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.Misc.MiscUI", typeof(MiscUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bozja.
        /// </summary>
        internal static string Bozja {
            get {
                return ResourceManager.GetString("Bozja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Dungeon.
        /// </summary>
        internal static string Deep_Dungeon {
            get {
                return ResourceManager.GetString("Deep_Dungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOL.
        /// </summary>
        internal static string DOL {
            get {
                return ResourceManager.GetString("DOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        internal static string DPS {
            get {
                return ResourceManager.GetString("DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer.
        /// </summary>
        internal static string Healer {
            get {
                return ResourceManager.GetString("Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Roles.
        /// </summary>
        internal static string Job_Roles {
            get {
                return ResourceManager.GetString("Job Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occult Crescent.
        /// </summary>
        internal static string Occult_Crescent {
            get {
                return ResourceManager.GetString("Occult Crescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise.
        /// </summary>
        internal static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces.
        /// </summary>
        internal static string Replaces {
            get {
                return ResourceManager.GetString("Replaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles and Content.
        /// </summary>
        internal static string Roles_and_Content {
            get {
                return ResourceManager.GetString("Roles and Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        internal static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        internal static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant Dungeons.
        /// </summary>
        internal static string Variant_Dungeons {
            get {
                return ResourceManager.GetString("Variant Dungeons", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Wrath Combo | New Changes.
        /// </summary>
        internal static string MajorChangesTitle {
            get {
                return ResourceManager.GetString("MajorChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank In-Combo Mitigation Has Been Overhauled and Moved.
        /// </summary>
        internal static string TankMitOverhaulTitle {
            get {
                return ResourceManager.GetString("TankMitOverhaulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You had one of these tanks configured! Please Read!.
        /// </summary>
        internal static string TankMitYouHadConfigured {
            get {
                return ResourceManager.GetString("TankMitYouHadConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanks have had their In-Combo Mitigation completely overhauled. No longer is their mitigation settings in each combo, and no longer is mitigation entirely triggered by HP%. Mitigation is now in its own Section, under the Advanced Combos, and those options apply to the Advanced Combos if they have 'Include Mitigations' checked. (Simple Modes will use the recommended values for these settings, if 'Include Mitigations' is checked there)  You can find these moved mitigation settings here: PvE Features > [Tank of choice] > Advanced Mitigation Options  Make sure Mitigation is enabled in combos for these to work: PvE Features > [Tank of choice] > Advanced/Simple Combo > Include Mitigations.
        /// </summary>
        internal static string TankMitBody {
            get {
                return ResourceManager.GetString("TankMitBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (then just search for 'Mitigation').
        /// </summary>
        internal static string SearchForMitigation {
            get {
                return ResourceManager.GetString("SearchForMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to > Open Dark Knight's Config.
        /// </summary>
        internal static string OpenDRKConfig {
            get {
                return ResourceManager.GetString("OpenDRKConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to > Open Gun Breaker's Config.
        /// </summary>
        internal static string OpenGNBConfig {
            get {
                return ResourceManager.GetString("OpenGNBConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to > Open Paladin's Config.
        /// </summary>
        internal static string OpenPLDConfig {
            get {
                return ResourceManager.GetString("OpenPLDConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to > Open Warrior's Config.
        /// </summary>
        internal static string OpenWARConfig {
            get {
                return ResourceManager.GetString("OpenWARConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raidwide-Detection Improved, Tankbuster Detection Added.
        /// </summary>
        internal static string RaidwideTankbusterTitle {
            get {
                return ResourceManager.GetString("RaidwideTankbusterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raidwide detection has been improved to now also check for nearby stack marker visual effects, in addition to the existing raidwide cast detection. (No change by you is needed for this, it's just expanded now)  Tankbuster detection has been added by checking for visual effects! Options to mitigate as a tank for these is in the new mitigation options above.  Find the new tankbuster mitigation options here: PvE Features > [Tank of choice] > Advanced Mitigation Options > Boss Encounter (can also search for 'Tankbuster' in your tank's configuration).
        /// </summary>
        internal static string RaidwideTankbusterBody {
            get {
                return ResourceManager.GetString("RaidwideTankbusterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close and Do Not Show again.
        /// </summary>
        internal static string CloseAndDoNotShow {
            get {
                return ResourceManager.GetString("CloseAndDoNotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section contains a range of bespoke "Custom Actions" which can be used as replacements for either base action replacements or specific macros..
        /// </summary>
        internal static string CustomActionsIntro {
            get {
                return ResourceManager.GetString("CustomActionsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Buttons.
        /// </summary>
        internal static string RotationButtons {
            get {
                return ResourceManager.GetString("RotationButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These buttons replace the need to replace actions for all features marked as either Simple or Advanced. Enable the type of combo you're wanting to use custom actions for, and drag the icon to your hotbar.  This frees up the actions for manual use, for example, for downtime where you only want to use 1-2-3 combos, or for healers to always have access to basic healing actions..
        /// </summary>
        internal static string RotationButtonsDesc {
            get {
                return ResourceManager.GetString("RotationButtonsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string TableAction {
            get {
                return ResourceManager.GetString("TableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don't Override Icons with Job Actions (drag action to hotbar again to take effect).
        /// </summary>
        internal static string DontOverrideIcons {
            get {
                return ResourceManager.GetString("DontOverrideIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will hide all combo outputs on custom actions, leaving only these icons showing. This is not advised if you wish to see the real actions being output by the combos on your hotbar, and should only be used if you feel it's something you want..
        /// </summary>
        internal static string DontOverrideIconsHelp {
            get {
                return ResourceManager.GetString("DontOverrideIconsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility Buttons.
        /// </summary>
        internal static string UtilityButtons {
            get {
                return ResourceManager.GetString("UtilityButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are buttons which serve to control the plugin in some way. Just drag the icon to your hotbar to use them..
        /// </summary>
        internal static string UtilityButtonsDesc {
            get {
                return ResourceManager.GetString("UtilityButtonsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that even if you do not have all the required spells active, you may still use these features. Any spells you do not have active will be skipped over so if a feature is not working as intended then please try and enable more required spells..
        /// </summary>
        internal static string BLUNote {
            get {
                return ResourceManager.GetString("BLUNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Action.
        /// </summary>
        internal static string UnknownAction {
            get {
                return ResourceManager.GetString("UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Trait.
        /// </summary>
        internal static string UnknownTrait {
            get {
                return ResourceManager.GetString("UnknownTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Status.
        /// </summary>
        internal static string UnknownStatus {
            get {
                return ResourceManager.GetString("UnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Item.
        /// </summary>
        internal static string UnknownItem {
            get {
                return ResourceManager.GetString("UnknownItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Target DPS.
        /// </summary>
        internal static string CustomAction_ST_DPS {
            get {
                return ResourceManager.GetString("CustomAction_ST_DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is for the Single Target DPS combos.
        /// </summary>
        internal static string CustomAction_ST_DPS_Desc {
            get {
                return ResourceManager.GetString("CustomAction_ST_DPS_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoE DPS.
        /// </summary>
        internal static string CustomAction_AoE_DPS {
            get {
                return ResourceManager.GetString("CustomAction_AoE_DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is for the AoE DPS combos.
        /// </summary>
        internal static string CustomAction_AoE_DPS_Desc {
            get {
                return ResourceManager.GetString("CustomAction_AoE_DPS_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Target Heals.
        /// </summary>
        internal static string CustomAction_ST_Heals {
            get {
                return ResourceManager.GetString("CustomAction_ST_Heals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is for the Single Target Heal combos.
        /// </summary>
        internal static string CustomAction_ST_Heals_Desc {
            get {
                return ResourceManager.GetString("CustomAction_ST_Heals_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoE Heals.
        /// </summary>
        internal static string CustomAction_AoE_Heals {
            get {
                return ResourceManager.GetString("CustomAction_AoE_Heals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is for the AoE Heal combos.
        /// </summary>
        internal static string CustomAction_AoE_Heals_Desc {
            get {
                return ResourceManager.GetString("CustomAction_AoE_Heals_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Not Found.
        /// </summary>
        internal static string CustomAction_ItemNotFound {
            get {
                return ResourceManager.GetString("CustomAction_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users shouldn't see this.
        /// </summary>
        internal static string CustomAction_ItemNotFound_Desc {
            get {
                return ResourceManager.GetString("CustomAction_ItemNotFound_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cease!.
        /// </summary>
        internal static string CustomAction_Cease {
            get {
                return ResourceManager.GetString("CustomAction_Cease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God says no! We don't want you to use actions currently.
        /// </summary>
        internal static string CustomAction_Cease_Desc {
            get {
                return ResourceManager.GetString("CustomAction_Cease_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Rotation Enable.
        /// </summary>
        internal static string CustomAction_AutoOn {
            get {
                return ResourceManager.GetString("CustomAction_AutoOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables auto-rotation.
        /// </summary>
        internal static string CustomAction_AutoOn_Desc {
            get {
                return ResourceManager.GetString("CustomAction_AutoOn_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Rotation Disable.
        /// </summary>
        internal static string CustomAction_AutoOff {
            get {
                return ResourceManager.GetString("CustomAction_AutoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables auto-rotation.
        /// </summary>
        internal static string CustomAction_AutoOff_Desc {
            get {
                return ResourceManager.GetString("CustomAction_AutoOff_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Rotation Toggle.
        /// </summary>
        internal static string CustomAction_AutoToggle {
            get {
                return ResourceManager.GetString("CustomAction_AutoToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches between enabled and disabled for auto-rotation.
        /// </summary>
        internal static string CustomAction_AutoToggle_Desc {
            get {
                return ResourceManager.GetString("CustomAction_AutoToggle_Desc", resourceCulture);
            }
        }

    }
}