//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.AutoRotation {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoRotationUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoRotationUI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.AutoRotation.AutoRotationUI", typeof(AutoRotationUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Delete From Ignored 的本地化字符串。
        /// </summary>
        internal static string Button_DeleteFromIgnored {
            get {
                return ResourceManager.GetString("Button_DeleteFromIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-{0} 的本地化字符串。
        /// </summary>
        internal static string Checkbox_AutoCleanse {
            get {
                return ResourceManager.GetString("Checkbox_AutoCleanse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-Resurrect 的本地化字符串。
        /// </summary>
        internal static string Checkbox_AutoRez {
            get {
                return ResourceManager.GetString("Checkbox_AutoRez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply to {0} &amp; {1} 的本地化字符串。
        /// </summary>
        internal static string Checkbox_AutoRezDPSJobs {
            get {
                return ResourceManager.GetString("Checkbox_AutoRezDPSJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Raise Raisers 的本地化字符串。
        /// </summary>
        internal static string Checkbox_AutoRezDPSJobsHealersOnly {
            get {
                return ResourceManager.GetString("Checkbox_AutoRezDPSJobsHealersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply to Out of Party Members 的本地化字符串。
        /// </summary>
        internal static string Checkbox_AutoRezOutOfParty {
            get {
                return ResourceManager.GetString("Checkbox_AutoRezOutOfParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Require {0}/{1} 的本地化字符串。
        /// </summary>
        internal static string Checkbox_AutoRezRequireSwift {
            get {
                return ResourceManager.GetString("Checkbox_AutoRezRequireSwift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bypass Only in Combat for FATE Targets 的本地化字符串。
        /// </summary>
        internal static string Checkbox_BypassFATETargets {
            get {
                return ResourceManager.GetString("Checkbox_BypassFATETargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bypass Only in Combat for Quest Targets 的本地化字符串。
        /// </summary>
        internal static string Checkbox_BypassQuestTargets {
            get {
                return ResourceManager.GetString("Checkbox_BypassQuestTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bypass When Combo Suggests Self-Use Action 的本地化字符串。
        /// </summary>
        internal static string Checkbox_BypassSelfUse {
            get {
                return ResourceManager.GetString("Checkbox_BypassSelfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable After Leaving Instanced Content 的本地化字符串。
        /// </summary>
        internal static string Checkbox_DisableInstanceExit {
            get {
                return ResourceManager.GetString("Checkbox_DisableInstanceExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Set Hard Target 的本地化字符串。
        /// </summary>
        internal static string Checkbox_DPSAlwaysHardTarget {
            get {
                return ResourceManager.GetString("Checkbox_DPSAlwaysHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Auto-Rotation 的本地化字符串。
        /// </summary>
        internal static string Checkbox_EnableAutoRotation {
            get {
                return ResourceManager.GetString("Checkbox_EnableAutoRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Automatically in Instanced Content 的本地化字符串。
        /// </summary>
        internal static string Checkbox_EnableInstancedEnter {
            get {
                return ResourceManager.GetString("Checkbox_EnableInstancedEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enforce Best AoE Target Selection 的本地化字符串。
        /// </summary>
        internal static string Checkbox_EnforceBestAoETarget {
            get {
                return ResourceManager.GetString("Checkbox_EnforceBestAoETarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prioritise FATE Targets 的本地化字符串。
        /// </summary>
        internal static string Checkbox_FATEPriority {
            get {
                return ResourceManager.GetString("Checkbox_FATEPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handle Detected Raidwides 的本地化字符串。
        /// </summary>
        internal static string Checkbox_HandleRaidwides {
            get {
                return ResourceManager.GetString("Checkbox_HandleRaidwides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handle Detected Tankbusters 的本地化字符串。
        /// </summary>
        internal static string Checkbox_HandleTankbusters {
            get {
                return ResourceManager.GetString("Checkbox_HandleTankbusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Set Hard Target###HealerHardTarget 的本地化字符串。
        /// </summary>
        internal static string Checkbox_HealerAlwaysHardTarget {
            get {
                return ResourceManager.GetString("Checkbox_HealerAlwaysHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heal Friendly NPCs 的本地化字符串。
        /// </summary>
        internal static string Checkbox_IncludeNPCs {
            get {
                return ResourceManager.GetString("Checkbox_IncludeNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limit {0} swapping to tanks only 的本地化字符串。
        /// </summary>
        internal static string Checkbox_KardiaTanksOnly {
            get {
                return ResourceManager.GetString("Checkbox_KardiaTanksOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] Automatically Manage {1} 的本地化字符串。
        /// </summary>
        internal static string Checkbox_ManageKardia {
            get {
                return ResourceManager.GetString("Checkbox_ManageKardia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Attack Targets Already In Combat 的本地化字符串。
        /// </summary>
        internal static string Checkbox_OnlyAttackInCombat {
            get {
                return ResourceManager.GetString("Checkbox_OnlyAttackInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only in Combat 的本地化字符串。
        /// </summary>
        internal static string Checkbox_OnlyInCombat {
            get {
                return ResourceManager.GetString("Checkbox_OnlyInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Orbwalker Integration 的本地化字符串。
        /// </summary>
        internal static string Checkbox_Orbwalker {
            get {
                return ResourceManager.GetString("Checkbox_Orbwalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}/{1}/{2}/{3}] Pre-emptively apply Heal Over Time/Shields on focus target 的本地化字符串。
        /// </summary>
        internal static string Checkbox_PreEmptiveHoT {
            get {
                return ResourceManager.GetString("Checkbox_PreEmptiveHoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prioritise Targets Not in Combat 的本地化字符串。
        /// </summary>
        internal static string Checkbox_PreferNonCombat {
            get {
                return ResourceManager.GetString("Checkbox_PreferNonCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prioritise Quest Targets 的本地化字符串。
        /// </summary>
        internal static string Checkbox_QuestPriority {
            get {
                return ResourceManager.GetString("Checkbox_QuestPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Un-Target and Stop Actions for Pyretics 的本地化字符串。
        /// </summary>
        internal static string Checkbox_UnTargetAndDisableForPenalty {
            get {
                return ResourceManager.GetString("Checkbox_UnTargetAndDisableForPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Healing Settings 的本地化字符串。
        /// </summary>
        internal static string Header_HealingSettings {
            get {
                return ResourceManager.GetString("Header_HealingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling this will turn off AoE Healing features. Otherwise will require the amount of targets required to be in range of an AoE feature&apos;s heal to use. 的本地化字符串。
        /// </summary>
        internal static string HelpText_AoEHealTargetCount {
            get {
                return ResourceManager.GetString("HelpText_AoEHealTargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling this will turn off AoE DPS features. Otherwise will require the amount of targets required to be in range of an AoE feature&apos;s attack to use. This applies to all 3 roles, and for any features that deal AoE damage. 的本地化字符串。
        /// </summary>
        internal static string HelpText_AoETargetCount {
            get {
                return ResourceManager.GetString("HelpText_AoETargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will {0} any cleansable debuffs (Healing takes priority). 的本地化字符串。
        /// </summary>
        internal static string HelpText_AutoCleanse {
            get {
                return ResourceManager.GetString("HelpText_AutoCleanse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will attempt to resurrect dead party members.
        ///Applies to {0}, {1}, {2}, {3}, {4}, and {5} {6} {7} 的本地化字符串。
        /// </summary>
        internal static string HelpText_AutoRez {
            get {
                return ResourceManager.GetString("HelpText_AutoRez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When playing as {0} or {1}, also attempt to raise a dead party member. {2} will only resurrect with {3} or {4} active. 的本地化字符串。
        /// </summary>
        internal static string HelpText_AutoRezDPSJobs {
            get {
                return ResourceManager.GetString("HelpText_AutoRezDPSJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When playing as {0} or {1}, Will only attempt to res Healers and Raisers 的本地化字符串。
        /// </summary>
        internal static string HelpText_AutoRezDPSJobsHealersOnly {
            get {
                return ResourceManager.GetString("HelpText_AutoRezDPSJobsHealersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requires {0} or {1}&apos;s {2} to be available to resurrect a party member, to avoid hard-casting. 的本地化字符串。
        /// </summary>
        internal static string HelpText_AutoRezRequireSwift {
            get {
                return ResourceManager.GetString("HelpText_AutoRezRequireSwift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables Auto-Mode outside of combat unless you&apos;re synced to a FATE. 的本地化字符串。
        /// </summary>
        internal static string HelpText_BypassFATETargets {
            get {
                return ResourceManager.GetString("HelpText_BypassFATETargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables Auto-Mode outside of combat unless you&apos;re within range of a quest target. 的本地化字符串。
        /// </summary>
        internal static string HelpText_BypassQuestTargets {
            get {
                return ResourceManager.GetString("HelpText_BypassQuestTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Many jobs have an out of combat action that can be used, for example, {0} or {1}. This will allow these to be used without being in combat. 的本地化字符串。
        /// </summary>
        internal static string HelpText_BypassSelfUse {
            get {
                return ResourceManager.GetString("HelpText_BypassSelfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-rotation does not need to target enemies to work, however with this setting enabled it will always set your hard target when it executes an attack. 的本地化字符串。
        /// </summary>
        internal static string HelpText_DPSAlwaysHardTarget {
            get {
                return ResourceManager.GetString("HelpText_DPSAlwaysHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max distance all targeting modes (except Manual) will look for a target. Values from 1 to 30 only. 的本地化字符串。
        /// </summary>
        internal static string HelpText_DPSMaxTargetDistance {
            get {
                return ResourceManager.GetString("HelpText_DPSMaxTargetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual - Leaves all targeting decisions to you.
        ///Highest Max - Prioritises enemies with the highest max HP.
        ///Lowest Max - Prioritises enemies with the lowest max HP.
        ///Highest Current - Prioritises the enemy with the highest current HP.
        ///Lowest Current - Prioritises the enemy with the lowest current HP.
        ///Tank Target - Prioritises the same target as the first tank in your group.
        ///Nearest - Prioritises the closest target to you.
        ///Furthest - Prioritises the furthest target from you. 的本地化字符串。
        /// </summary>
        internal static string HelpText_DPSTargettingMode {
            get {
                return ResourceManager.GetString("HelpText_DPSTargettingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For all other targeting modes, AoE will target based on highest number of targets hit. In manual mode, it will only do this if you tick this box. 的本地化字符串。
        /// </summary>
        internal static string HelpText_EnforceBestAoETarget {
            get {
                return ResourceManager.GetString("HelpText_EnforceBestAoETarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will try to use actions before detected raidwides or group damage to either mitigate or top-off party members. Max 2 actions (excluding {0} for setup) 的本地化字符串。
        /// </summary>
        internal static string HelpText_HandleRaidwides {
            get {
                return ResourceManager.GetString("HelpText_HandleRaidwides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will try to use actions before detected tankbusters to mitigate damage on targeted member. Max 1 action (excluding {0} for setup) 的本地化字符串。
        /// </summary>
        internal static string HelpText_HandleTankbusters {
            get {
                return ResourceManager.GetString("HelpText_HandleTankbusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t set this too high! 1-2 seconds is normally comfy enough to be considered a natural reaction. 的本地化字符串。
        /// </summary>
        internal static string HelpText_HealDelay {
            get {
                return ResourceManager.GetString("HelpText_HealDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-rotation does not need to target allies to work, however with this setting enabled it will always set your hard target when it executes a heal. 的本地化字符串。
        /// </summary>
        internal static string HelpText_HealerAlwaysHardTarget {
            get {
                return ResourceManager.GetString("HelpText_HealerAlwaysHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual - Will only heal a target if you select them manually. If the target does not meet the healing threshold settings criteria below it will skip healing in favour of DPSing (if also enabled).
        ///Highest Current - Prioritises the party member with the highest current HP%.
        ///Lowest Current - Prioritises the party member with the lowest current HP%. 的本地化字符串。
        /// </summary>
        internal static string HelpText_HealerTargetingMode {
            get {
                return ResourceManager.GetString("HelpText_HealerTargetingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These NPCs will be ignored by Auto-Rotation.
        ///Every instance of this NPC will be excluded from automatic targeting (Manual will still work).
        ///To remove an NPC from this list, select it and press the Delete button below.
        ///To add an NPC to this list, target the NPC and use the command: /wrath ignore 的本地化字符串。
        /// </summary>
        internal static string HelpText_IgnoredNPCs {
            get {
                return ResourceManager.GetString("HelpText_IgnoredNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When in boss fights only, any target regardless of distance can be eligible to be attacked. 的本地化字符串。
        /// </summary>
        internal static string HelpText_IgnoreRangeInBoss {
            get {
                return ResourceManager.GetString("HelpText_IgnoreRangeInBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Useful for healer quests where NPCs are expected to be healed but aren&apos;t added directly to your party. 的本地化字符串。
        /// </summary>
        internal static string HelpText_IncludeNPCs {
            get {
                return ResourceManager.GetString("HelpText_IncludeNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switches {0} to party members currently being targeted by enemies, prioritising tanks if multiple people are being targeted. 的本地化字符串。
        /// </summary>
        internal static string HelpText_ManageKardia {
            get {
                return ResourceManager.GetString("HelpText_ManageKardia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will make Auto-Rotation use actions with cast times even whilst moving, as Orbwalker will lock movement during the cast. You may need to enable &quot;Buffer Initial Cast&quot; setting in Orbwalker if not already enabled. Requires an Orbwalker plugin to be installed and enabled. 的本地化字符串。
        /// </summary>
        internal static string HelpText_Orbwalker {
            get {
                return ResourceManager.GetString("HelpText_Orbwalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies {0}/{1}/{2}/{3} to your focus target when out of combat and they are 30y or less away from an enemy. (Bypasses &quot;Only in Combat&quot; setting) 的本地化字符串。
        /// </summary>
        internal static string HelpText_PreEmptiveHoT {
            get {
                return ResourceManager.GetString("HelpText_PreEmptiveHoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will determine how soon before the GCD is finished to queue up the next weaponskill or spell. Your latency may have an effect on what actions are performed so please adjust this if you&apos;re noticing improper action use, i.e double Blizzard IV casts due to MP not updating in time. 的本地化字符串。
        /// </summary>
        internal static string HelpText_QueueWindow {
            get {
                return ResourceManager.GetString("HelpText_QueueWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You typically want to set this lower than the above setting. 的本地化字符串。
        /// </summary>
        internal static string HelpText_SingleTargetExcogHPP {
            get {
                return ResourceManager.GetString("HelpText_SingleTargetExcogHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You typically want to set this lower than the above setting. 的本地化字符串。
        /// </summary>
        internal static string HelpText_SingleTargetRegenHPP {
            get {
                return ResourceManager.GetString("HelpText_SingleTargetRegenHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-Rotation has a built in throttler to only run every so many milliseconds for performance reasons. If you experience issues with frame rate, try increasing this value. Do note this may have a side-effect of introducing clipping if set too high, so experiment with the value. 的本地化字符串。
        /// </summary>
        internal static string HelpText_ThrottleDelay {
            get {
                return ResourceManager.GetString("HelpText_ThrottleDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will un-set any current target and disable Auto-Rotation actions if there is a current detected Pyretic (or similar, like Acceleration Bomb) mechanic affecting the player, that would harm them if they took any action. 的本地化字符串。
        /// </summary>
        internal static string HelpText_UnTargetAndDisableForPenalty {
            get {
                return ResourceManager.GetString("HelpText_UnTargetAndDisableForPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is where you can configure the parameters in which Auto-Rotation will operate.
        ///Features marked with an &apos;Auto-Mode&apos; checkbox are able to be used with Auto-Rotation. 的本地化字符串。
        /// </summary>
        internal static string Info_Header {
            get {
                return ResourceManager.GetString("Info_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Targets Required for AoE Healing Features 的本地化字符串。
        /// </summary>
        internal static string Input_AoEHealTargetCount {
            get {
                return ResourceManager.GetString("Input_AoEHealTargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Targets Required for AoE Damage Features 的本地化字符串。
        /// </summary>
        internal static string Input_AoETargetCount {
            get {
                return ResourceManager.GetString("Input_AoETargetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay to activate Auto-Rotation once combat starts (seconds) 的本地化字符串。
        /// </summary>
        internal static string Input_AutoRotationDelay {
            get {
                return ResourceManager.GetString("Input_AutoRotationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay to start healing once above conditions are met (seconds) 的本地化字符串。
        /// </summary>
        internal static string Input_HealDelay {
            get {
                return ResourceManager.GetString("Input_HealDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue Window (s) 的本地化字符串。
        /// </summary>
        internal static string Input_QueueWindow {
            get {
                return ResourceManager.GetString("Input_QueueWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Throttle Delay (ms) 的本地化字符串。
        /// </summary>
        internal static string Input_ThrottleDelay {
            get {
                return ResourceManager.GetString("Input_ThrottleDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced 的本地化字符串。
        /// </summary>
        internal static string Label_Advanced {
            get {
                return ResourceManager.GetString("Label_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damage Settings 的本地化字符串。
        /// </summary>
        internal static string Label_DamageSettings {
            get {
                return ResourceManager.GetString("Label_DamageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Target Distance 的本地化字符串。
        /// </summary>
        internal static string Label_DPSMaxTargetDistance {
            get {
                return ResourceManager.GetString("Label_DPSMaxTargetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Targeting Mode 的本地化字符串。
        /// </summary>
        internal static string Label_DPSTargetingMode {
            get {
                return ResourceManager.GetString("Label_DPSTargetingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Healer Targeting Mode 的本地化字符串。
        /// </summary>
        internal static string Label_HealingTargetingMode {
            get {
                return ResourceManager.GetString("Label_HealingTargetingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignored NPCs 的本地化字符串。
        /// </summary>
        internal static string Label_IgnoredNPCs {
            get {
                return ResourceManager.GetString("Label_IgnoredNPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Max Target Distance In Boss Fights 的本地化字符串。
        /// </summary>
        internal static string Label_IgnoreRangeInBoss {
            get {
                return ResourceManager.GetString("Label_IgnoreRangeInBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AoE HP% Threshold 的本地化字符串。
        /// </summary>
        internal static string Slider_AoETargetHPP {
            get {
                return ResourceManager.GetString("Slider_AoETargetHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Target HP% Threshold (target has Excogitation) 的本地化字符串。
        /// </summary>
        internal static string Slider_SingleTargetExcogHPP {
            get {
                return ResourceManager.GetString("Slider_SingleTargetExcogHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Target HP% Threshold 的本地化字符串。
        /// </summary>
        internal static string Slider_SingleTargetHPP {
            get {
                return ResourceManager.GetString("Slider_SingleTargetHPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Target HP% Threshold (target has Regen/Aspected Benefic) 的本地化字符串。
        /// </summary>
        internal static string Slider_SingleTargetRegenHPP {
            get {
                return ResourceManager.GetString("Slider_SingleTargetRegenHPP", resourceCulture);
            }
        }
    }
}
