//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BLM_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BLM_Config() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.BLM_Config", typeof(BLM_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} / {1} / {2} in {3} depending on stacks and level 的本地化字符串。
        /// </summary>
        internal static string Add0or1or2or3DependingonStackAndLevel {
            get {
                return ResourceManager.GetString("Add0or1or2or3DependingonStackAndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} / {1} when in {2} and stack is less than 3 的本地化字符串。
        /// </summary>
        internal static string Add0Or1WhenIn2 {
            get {
                return ResourceManager.GetString("Add0Or1WhenIn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} when in {1} and below 2400 MP. 的本地化字符串。
        /// </summary>
        internal static string Add0WhenBelow2400MP {
            get {
                return ResourceManager.GetString("Add0WhenBelow2400MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} when in {1} and above 800 MP. 的本地化字符串。
        /// </summary>
        internal static string Add0WhenIn1AndAbove800MP {
            get {
                return ResourceManager.GetString("Add0WhenIn1AndAbove800MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} in {1} when ready. 的本地化字符串。
        /// </summary>
        internal static string AddFlarestarinAF {
            get {
                return ResourceManager.GetString("AddFlarestarinAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use while under the effect of {0}.
        ///This is the recommended behaviour. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseUnderLeylines {
            get {
                return ResourceManager.GetString("DoNotUseUnderLeylines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leaves {0} in {2} 
        ///Will Use {0} / {1} if selected above. 的本地化字符串。
        /// </summary>
        internal static string DontChangeFireInUmbralIce {
            get {
                return ResourceManager.GetString("DontChangeFireInUmbralIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will only use {0} when both HP is under the slider threshold, and when groupwide damage is incoming 的本地化字符串。
        /// </summary>
        internal static string ManawardHPThresholdAndGroupwideDesc {
            get {
                return ResourceManager.GetString("ManawardHPThresholdAndGroupwideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not under {0} 的本地化字符串。
        /// </summary>
        internal static string NotUnderLeylines {
            get {
                return ResourceManager.GetString("NotUnderLeylines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only require HP threshold for solo play 的本地化字符串。
        /// </summary>
        internal static string OnlySolo {
            get {
                return ResourceManager.GetString("OnlySolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When solo (Chocobos do not count), will only require to meet the HP threshold. In a party, it will require both the HP threshold and groupwide damage incoming. 的本地化字符串。
        /// </summary>
        internal static string OnlySoloDesc {
            get {
                return ResourceManager.GetString("OnlySoloDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger only on groupwide damage incoming 的本地化字符串。
        /// </summary>
        internal static string OnlyTriggerGroupwide {
            get {
                return ResourceManager.GetString("OnlyTriggerGroupwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will only use {0} when groupwide damage is incoming 的本地化字符串。
        /// </summary>
        internal static string OnlyTriggerGroupwideDesc {
            get {
                return ResourceManager.GetString("OnlyTriggerGroupwideDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger only on HP threshold 的本地化字符串。
        /// </summary>
        internal static string OnlyTriggerHP {
            get {
                return ResourceManager.GetString("OnlyTriggerHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will only use {0} when HP is under the slider threshold, and will not wait for any groupwide damage to be detected (mostly for solo-play) 的本地化字符串。
        /// </summary>
        internal static string OnlyTriggerHPDesc {
            get {
                return ResourceManager.GetString("OnlyTriggerHPDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces {0} with {1} when in {2}. 的本地化字符串。
        /// </summary>
        internal static string ReplaceBlizzard3WithBlizzardWhenInUI3 {
            get {
                return ResourceManager.GetString("ReplaceBlizzard3WithBlizzardWhenInUI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces {0} with {1} when out of {2}. 的本地化字符串。
        /// </summary>
        internal static string ReplaceBlizzardWithBlizzard3WhenNotInUI3 {
            get {
                return ResourceManager.GetString("ReplaceBlizzardWithBlizzard3WhenNotInUI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces {0} with {1} when in {2}. 的本地化字符串。
        /// </summary>
        internal static string ReplaceFire3WithFireWhenInAF3 {
            get {
                return ResourceManager.GetString("ReplaceFire3WithFireWhenInAF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces {0} with {1} when out of {2} or not in combat. 的本地化字符串。
        /// </summary>
        internal static string ReplaceFireWithFire3WhenNotInAF3OrCombat {
            get {
                return ResourceManager.GetString("ReplaceFireWithFire3WhenNotInAF3OrCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Require both HP check and groupwide damage incoming 的本地化字符串。
        /// </summary>
        internal static string RequireHPandGroupwide {
            get {
                return ResourceManager.GetString("RequireHPandGroupwide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Makes it so that {0} also shows when {1} is on cooldown. 的本地化字符串。
        /// </summary>
        internal static string ShowXenoglossyWhenAmplifierIsOnCooldown {
            get {
                return ResourceManager.GetString("ShowXenoglossyWhenAmplifierIsOnCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show {0} when {1} is on cooldown 的本地化字符串。
        /// </summary>
        internal static string ShowXenoglossyWhenAmplifierOnCD {
            get {
                return ResourceManager.GetString("ShowXenoglossyWhenAmplifierOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} when below 1500 MP and when it is an instant cast (level 100 only). 的本地化字符串。
        /// </summary>
        internal static string UseDespairWhenBelow1500MP {
            get {
                return ResourceManager.GetString("UseDespairWhenBelow1500MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} when you have {1} proc. 的本地化字符串。
        /// </summary>
        internal static string UseFire3WhenYouHaveFirestarterProc {
            get {
                return ResourceManager.GetString("UseFire3WhenYouHaveFirestarterProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} when in {1}. 的本地化字符串。
        /// </summary>
        internal static string UseParadoxWhenInAF3 {
            get {
                return ResourceManager.GetString("UseParadoxWhenInAF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} when you don&apos;t have {1}. 的本地化字符串。
        /// </summary>
        internal static string UseSwiftcastWhenNoTriplecast {
            get {
                return ResourceManager.GetString("UseSwiftcastWhenNoTriplecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} when you don&apos;t have {1} active. 的本地化字符串。
        /// </summary>
        internal static string UseTriplecastWhenNoSwiftcast {
            get {
                return ResourceManager.GetString("UseTriplecastWhenNoSwiftcast", resourceCulture);
            }
        }
    }
}
