//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BRD_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BRD_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.BRD_Config", typeof(BRD_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to 2.48 Adjusted Standard Opener.
        /// </summary>
        internal static string Adjusted248Opener {
            get {
                return ResourceManager.GetString("Adjusted248Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.49 Standard Comfy.
        /// </summary>
        internal static string Standard249Comfy {
            get {
                return ResourceManager.GetString("Standard249Comfy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew time for dots (In seconds)..
        /// </summary>
        internal static string RenewTimeForDots {
            get {
                return ResourceManager.GetString("RenewTimeForDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Jaws Option.
        /// </summary>
        internal static string IronJawsOption {
            get {
                return ResourceManager.GetString("IronJawsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the refreshing of dots with Ironjaws.
        /// </summary>
        internal static string IronJawsOptionDesc {
            get {
                return ResourceManager.GetString("IronJawsOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Application Option.
        /// </summary>
        internal static string DotApplicationOption {
            get {
                return ResourceManager.GetString("DotApplicationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the application of dots outside of the opener.
        /// </summary>
        internal static string DotApplicationOptionDesc {
            get {
                return ResourceManager.GetString("DotApplicationOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raging Jaws Option.
        /// </summary>
        internal static string RagingJawsOption {
            get {
                return ResourceManager.GetString("RagingJawsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the snapshotting of DoTs, within the remaining time of Raging Strikes.
        /// </summary>
        internal static string RagingJawsOptionDesc {
            get {
                return ResourceManager.GetString("RagingJawsOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiDot Option.
        /// </summary>
        internal static string MultiDotOption {
            get {
                return ResourceManager.GetString("MultiDotOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will maintain dots on up to 3 targets..
        /// </summary>
        internal static string MultiDotOptionDesc {
            get {
                return ResourceManager.GetString("MultiDotOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raging Jaws: Renew time (In seconds).  Recommended 5, increase little by little if refresh is outside of radiant window.
        /// </summary>
        internal static string RagingJawsRenewTime {
            get {
                return ResourceManager.GetString("RagingJawsRenewTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop using Buffs on targets below this HP % (0% = always use, 100% = never use)..
        /// </summary>
        internal static string StopBuffsBelowHp {
            get {
                return ResourceManager.GetString("StopBuffsBelowHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop using Buffs on targets below this HP % (0 = always use, 100 = never use)..
        /// </summary>
        internal static string StopBuffsBelowHpAoE {
            get {
                return ResourceManager.GetString("StopBuffsBelowHpAoE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raging Strikes Option.
        /// </summary>
        internal static string RagingStrikesOption {
            get {
                return ResourceManager.GetString("RagingStrikesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Raging Strikes.
        /// </summary>
        internal static string AddsRagingStrikes {
            get {
                return ResourceManager.GetString("AddsRagingStrikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battlevoice Option.
        /// </summary>
        internal static string BattlevoiceOption {
            get {
                return ResourceManager.GetString("BattlevoiceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Battle Voice.
        /// </summary>
        internal static string AddsBattleVoice {
            get {
                return ResourceManager.GetString("AddsBattleVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrage Option.
        /// </summary>
        internal static string BarrageOption {
            get {
                return ResourceManager.GetString("BarrageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Barrage.
        /// </summary>
        internal static string AddsBarrage {
            get {
                return ResourceManager.GetString("AddsBarrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiant Finale Option.
        /// </summary>
        internal static string RadiantFinaleOption {
            get {
                return ResourceManager.GetString("RadiantFinaleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Radiant Finale.
        /// </summary>
        internal static string AddsRadiantFinale {
            get {
                return ResourceManager.GetString("AddsRadiantFinale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP percent threshold to use Second Wind below..
        /// </summary>
        internal static string SecondWindHpThreshold {
            get {
                return ResourceManager.GetString("SecondWindHpThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Cleanse Option.
        /// </summary>
        internal static string PartyCleanseOption {
            get {
                return ResourceManager.GetString("PartyCleanseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses Wardens Paeon when someone in the party has a cleansable debuff using the Retargeting Function following party list..
        /// </summary>
        internal static string PartyCleanseOptionDesc {
            get {
                return ResourceManager.GetString("PartyCleanseOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Empyreal Arrow.
        /// </summary>
        internal static string AddsEmpyrealArrow {
            get {
                return ResourceManager.GetString("AddsEmpyrealArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Pitch Perfect.
        /// </summary>
        internal static string AddsPitchPerfect {
            get {
                return ResourceManager.GetString("AddsPitchPerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Bloodletter when at max charges.
        /// </summary>
        internal static string AddsBloodletterMaxCharges {
            get {
                return ResourceManager.GetString("AddsBloodletterMaxCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Sidewinder.
        /// </summary>
        internal static string AddsSidewinder {
            get {
                return ResourceManager.GetString("AddsSidewinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Rain of Death when at max charges, or bloodletter below level..
        /// </summary>
        internal static string AddsRainOfDeath {
            get {
                return ResourceManager.GetString("AddsRainOfDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Jaws Alternate.
        /// </summary>
        internal static string IronJawsAlternate {
            get {
                return ResourceManager.GetString("IronJawsAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron Jaws will only show up when debuffs are about to expire..
        /// </summary>
        internal static string IronJawsAlternateDesc {
            get {
                return ResourceManager.GetString("IronJawsAlternateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apex Option.
        /// </summary>
        internal static string ApexOption {
            get {
                return ResourceManager.GetString("ApexOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Apex and Blast Arrow to Iron Jaws when available..
        /// </summary>
        internal static string ApexOptionDesc {
            get {
                return ResourceManager.GetString("ApexOptionDesc", resourceCulture);
            }
        }

    }
}