//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Generics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generics() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.Generics", typeof(Generics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Option 的本地化字符串。
        /// </summary>
        internal static string _0Option {
            get {
                return ResourceManager.GetString("_0Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Opener 的本地化字符串。
        /// </summary>
        internal static string Action_Opener {
            get {
                return ResourceManager.GetString("Action_Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Priority:  的本地化字符串。
        /// </summary>
        internal static string Action_Priority {
            get {
                return ResourceManager.GetString("Action_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Threshold 的本地化字符串。
        /// </summary>
        internal static string Action_Threshold {
            get {
                return ResourceManager.GetString("Action_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add {0} 的本地化字符串。
        /// </summary>
        internal static string Add0 {
            get {
                return ResourceManager.GetString("Add0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add {0} Combo 的本地化字符串。
        /// </summary>
        internal static string Add0Combo {
            get {
                return ResourceManager.GetString("Add0Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} combo when applicable. 的本地化字符串。
        /// </summary>
        internal static string Add0ComboWhenApplicable {
            get {
                return ResourceManager.GetString("Add0ComboWhenApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add {0} / {1}. 的本地化字符串。
        /// </summary>
        internal static string Add0Or1 {
            get {
                return ResourceManager.GetString("Add0Or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add {0} to the rotation. 的本地化字符串。
        /// </summary>
        internal static string Add0ToTheRotation {
            get {
                return ResourceManager.GetString("Add0ToTheRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add {0} when average HP% of the party is at or below. 的本地化字符串。
        /// </summary>
        internal static string Add0WhenAverageHpPercentofPartyIsAtOrBelow {
            get {
                return ResourceManager.GetString("Add0WhenAverageHpPercentofPartyIsAtOrBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds Field mouseover targetting. 的本地化字符串。
        /// </summary>
        internal static string AddFieldMouseoverTargetting {
            get {
                return ResourceManager.GetString("AddFieldMouseoverTargetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} to {1}. 的本地化字符串。
        /// </summary>
        internal static string Adds0To1 {
            get {
                return ResourceManager.GetString("Adds0To1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Content 的本地化字符串。
        /// </summary>
        internal static string AllContent {
            get {
                return ResourceManager.GetString("AllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies to all content in the game. 的本地化字符串。
        /// </summary>
        internal static string AllContentDescription {
            get {
                return ResourceManager.GetString("AllContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Enemies 的本地化字符串。
        /// </summary>
        internal static string AllEnemies {
            get {
                return ResourceManager.GetString("AllEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Mouseover &gt; Field Mouseover &gt; Focus Target &gt; Soft Target &gt; Hard Target 的本地化字符串。
        /// </summary>
        internal static string AllHealerRetargetting {
            get {
                return ResourceManager.GetString("AllHealerRetargetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ally Hard Target 的本地化字符串。
        /// </summary>
        internal static string AllyHardTarget {
            get {
                return ResourceManager.GetString("AllyHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always 的本地化字符串。
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any Movement 的本地化字符串。
        /// </summary>
        internal static string AnyMovement {
            get {
                return ResourceManager.GetString("AnyMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies options to {0} only. 的本地化字符串。
        /// </summary>
        internal static string ApplyOnlyTo0 {
            get {
                return ResourceManager.GetString("ApplyOnlyTo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies options to all of these:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string ApplyToAll0 {
            get {
                return ResourceManager.GetString("ApplyToAll0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boss Encounter Non Bosses. Stop using at Enemy HP %. 的本地化字符串。
        /// </summary>
        internal static string BossEncounterNonBossHpPercent {
            get {
                return ResourceManager.GetString("BossEncounterNonBossHpPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boss Only Content 的本地化字符串。
        /// </summary>
        internal static string BossOnlyContent {
            get {
                return ResourceManager.GetString("BossOnlyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only applies in instances where you directly fight a boss. Excludes many A Realm Reborn &amp; Heavensward raids that include trash. 的本地化字符串。
        /// </summary>
        internal static string BossOnlyDescription {
            get {
                return ResourceManager.GetString("BossOnlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bosses Only. Stop using at Enemy HP %. 的本地化字符串。
        /// </summary>
        internal static string BossOnlyHpPercent {
            get {
                return ResourceManager.GetString("BossOnlyHpPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BurstOption 的本地化字符串。
        /// </summary>
        internal static string BurstOption {
            get {
                return ResourceManager.GetString("BurstOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string Change0Or1 {
            get {
                return ResourceManager.GetString("Change0Or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How many charges to retain for manual use. Set to 0 to disable this check. 的本地化字符串。
        /// </summary>
        internal static string ChargePool {
            get {
                return ResourceManager.GetString("ChargePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How long to delay after detecting incoming tankbuster to use {0}. Set to 0 to disable this check. 的本地化字符串。
        /// </summary>
        internal static string DelayMit {
            get {
                return ResourceManager.GetString("DelayMit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable range check 的本地化字符串。
        /// </summary>
        internal static string DisableRangeCheck {
            get {
                return ResourceManager.GetString("DisableRangeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables the use of mitigations. 的本地化字符串。
        /// </summary>
        internal static string DisablesTheUseOfMitigations {
            get {
                return ResourceManager.GetString("DisablesTheUseOfMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t Use {0} 的本地化字符串。
        /// </summary>
        internal static string DontUse0 {
            get {
                return ResourceManager.GetString("DontUse0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds remaining before reapplying the DoT. Set to Zero to disable this check. 的本地化字符串。
        /// </summary>
        internal static string DoTSecondsRemainingZeroDisable {
            get {
                return ResourceManager.GetString("DoTSecondsRemainingZeroDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables the use of mitigations. 的本地化字符串。
        /// </summary>
        internal static string EnablesTheUseOfMitigations {
            get {
                return ResourceManager.GetString("EnablesTheUseOfMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enemy Hard Target 的本地化字符串。
        /// </summary>
        internal static string EnemyHardTarget {
            get {
                return ResourceManager.GetString("EnemyHardTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select what kind of enemies the HP check should be applied to: 的本地化字符串。
        /// </summary>
        internal static string EnemyTypeCheck {
            get {
                return ResourceManager.GetString("EnemyTypeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude {0} 的本地化字符串。
        /// </summary>
        internal static string Exclude0 {
            get {
                return ResourceManager.GetString("Exclude0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude Advanced Mitigations 的本地化字符串。
        /// </summary>
        internal static string ExcludeAdvancedMitigations {
            get {
                return ResourceManager.GetString("ExcludeAdvancedMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude Simple Mitigations 的本地化字符串。
        /// </summary>
        internal static string ExcludeSimpleMitigations {
            get {
                return ResourceManager.GetString("ExcludeSimpleMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Mouseover 的本地化字符串。
        /// </summary>
        internal static string FieldMouseover {
            get {
                return ResourceManager.GetString("FieldMouseover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Target 的本地化字符串。
        /// </summary>
        internal static string FocusTarget {
            get {
                return ResourceManager.GetString("FocusTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold {0} for {1} 的本地化字符串。
        /// </summary>
        internal static string Hold0For1 {
            get {
                return ResourceManager.GetString("Hold0For1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How many charges to save for movement? 的本地化字符串。
        /// </summary>
        internal static string HowManyChargesForMovement {
            get {
                return ResourceManager.GetString("HowManyChargesForMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  How many charges to keep ready?
        ///(0 = Use All) 的本地化字符串。
        /// </summary>
        internal static string HowManyChargesToKeepReady {
            get {
                return ResourceManager.GetString("HowManyChargesToKeepReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies HP Check to All Content 的本地化字符串。
        /// </summary>
        internal static string HPCheckAllContent {
            get {
                return ResourceManager.GetString("HPCheckAllContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies the HP check above to all enemies. 的本地化字符串。
        /// </summary>
        internal static string HPCheckAllEnemies {
            get {
                return ResourceManager.GetString("HPCheckAllEnemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applies HP check to Non-Boss Encounters only 的本地化字符串。
        /// </summary>
        internal static string HPCheckNonBossEncountersOnly {
            get {
                return ResourceManager.GetString("HPCheckNonBossEncountersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only applies the HP check above to non-bosses. 的本地化字符串。
        /// </summary>
        internal static string HPCheckNonBosses {
            get {
                return ResourceManager.GetString("HPCheckNonBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set a HP% Threshold for when {0} will not be automatically applied to the target. 的本地化字符串。
        /// </summary>
        internal static string HPPercentageFor0NotBeApplied {
            get {
                return ResourceManager.GetString("HPPercentageFor0NotBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} HP percentage threshold. 的本地化字符串。
        /// </summary>
        internal static string HPPercentageThreshold {
            get {
                return ResourceManager.GetString("HPPercentageThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HP% Threshold to use all charges of {0}. 的本地化字符串。
        /// </summary>
        internal static string HPPercentThresholdUseAllCharges0 {
            get {
                return ResourceManager.GetString("HPPercentThresholdUseAllCharges0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include {0} 的本地化字符串。
        /// </summary>
        internal static string Include0 {
            get {
                return ResourceManager.GetString("Include0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Advanced Mitigations 的本地化字符串。
        /// </summary>
        internal static string IncludeAdvancedMitigations {
            get {
                return ResourceManager.GetString("IncludeAdvancedMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Shields in HP Percent Sliders 的本地化字符串。
        /// </summary>
        internal static string IncludeShields {
            get {
                return ResourceManager.GetString("IncludeShields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Simple Mitigations 的本地化字符串。
        /// </summary>
        internal static string IncludeSimpleMitigations {
            get {
                return ResourceManager.GetString("IncludeSimpleMitigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Melee Range 的本地化字符串。
        /// </summary>
        internal static string InMeleeRange {
            get {
                return ResourceManager.GetString("InMeleeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In range 的本地化字符串。
        /// </summary>
        internal static string InRange {
            get {
                return ResourceManager.GetString("InRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Shield Check 的本地化字符串。
        /// </summary>
        internal static string Job0ShieldCheck {
            get {
                return ResourceManager.GetString("Job0ShieldCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable to not override an existing {0}&apos;s shield. 的本地化字符串。
        /// </summary>
        internal static string Job0ShieldCheckDesc {
            get {
                return ResourceManager.GetString("Job0ShieldCheckDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set value for your MP to be at or under for this feature to work 的本地化字符串。
        /// </summary>
        internal static string LucidMP {
            get {
                return ResourceManager.GetString("LucidMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of targets to employ multi-dotting  的本地化字符串。
        /// </summary>
        internal static string MaxTargetsMultiDot {
            get {
                return ResourceManager.GetString("MaxTargetsMultiDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum Gauge Required to use {0}  的本地化字符串。
        /// </summary>
        internal static string MinimumGauge {
            get {
                return ResourceManager.GetString("MinimumGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movement Option 的本地化字符串。
        /// </summary>
        internal static string MovementOption {
            get {
                return ResourceManager.GetString("MovementOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player MP to be less than or equal to: 的本地化字符串。
        /// </summary>
        internal static string MPLessOrEqual {
            get {
                return ResourceManager.GetString("MPLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Movement 的本地化字符串。
        /// </summary>
        internal static string NoMovement {
            get {
                return ResourceManager.GetString("NoMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-boss Encounters Only 的本地化字符串。
        /// </summary>
        internal static string NonBossEncountersOnly {
            get {
                return ResourceManager.GetString("NonBossEncountersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-Bosses 的本地化字符串。
        /// </summary>
        internal static string NonBosses {
            get {
                return ResourceManager.GetString("NonBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non boss encounter. Stop using at Enemy HP %. 的本地化字符串。
        /// </summary>
        internal static string NonBossHpPercent {
            get {
                return ResourceManager.GetString("NonBossHpPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal Targeting 的本地化字符串。
        /// </summary>
        internal static string NormalTargeting {
            get {
                return ResourceManager.GetString("NormalTargeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not In Boss Encounters 的本地化字符串。
        /// </summary>
        internal static string NotInBossEncounters {
            get {
                return ResourceManager.GetString("NotInBossEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On {0} 的本地化字符串。
        /// </summary>
        internal static string On0 {
            get {
                return ResourceManager.GetString("On0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only uses {0} when in melee range. 的本地化字符串。
        /// </summary>
        internal static string OnlyUse0WhenInMeleeRange {
            get {
                return ResourceManager.GetString("OnlyUse0WhenInMeleeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only uses {0} when not moving. 的本地化字符串。
        /// </summary>
        internal static string OnlyUse0WhenNotMoving {
            get {
                return ResourceManager.GetString("OnlyUse0WhenNotMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only use the opener when a countdown is active. 的本地化字符串。
        /// </summary>
        internal static string OnlyUseOpenerWhenCountdownActive {
            get {
                return ResourceManager.GetString("OnlyUseOpenerWhenCountdownActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only use {0} when the targeted enemy is a boss. 的本地化字符串。
        /// </summary>
        internal static string OnlyUseWhenTargetIsBoss {
            get {
                return ResourceManager.GetString("OnlyUseWhenTargetIsBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only use with {0} 的本地化字符串。
        /// </summary>
        internal static string OnlyUseWith0 {
            get {
                return ResourceManager.GetString("OnlyUseWith0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Weave 的本地化字符串。
        /// </summary>
        internal static string OnlyWeave {
            get {
                return ResourceManager.GetString("OnlyWeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only with countdown 的本地化字符串。
        /// </summary>
        internal static string OnlyWithCountdown {
            get {
                return ResourceManager.GetString("OnlyWithCountdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player HP% to be greater than or equal to: 的本地化字符串。
        /// </summary>
        internal static string PlayerHPGreaterOrEqual {
            get {
                return ResourceManager.GetString("PlayerHPGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player HP% to use {0} at or below.  Set to 100 to disable this check 的本地化字符串。
        /// </summary>
        internal static string PlayerHPToUseAction {
            get {
                return ResourceManager.GetString("PlayerHPToUseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prio buff upkeep 的本地化字符串。
        /// </summary>
        internal static string PrioBuffUpkeep {
            get {
                return ResourceManager.GetString("PrioBuffUpkeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority:  的本地化字符串。
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace {0} with {1} / {2}. 的本地化字符串。
        /// </summary>
        internal static string Replace0With1Or2 {
            get {
                return ResourceManager.GetString("Replace0With1Or2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces {0} 的本地化字符串。
        /// </summary>
        internal static string Replaces0 {
            get {
                return ResourceManager.GetString("Replaces0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save {0} charges for burst. 的本地化字符串。
        /// </summary>
        internal static string Save0ChargesForBurst {
            get {
                return ResourceManager.GetString("Save0ChargesForBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select what kind of content this option applies to: 的本地化字符串。
        /// </summary>
        internal static string SelectWhatKindOfContentThisOptionAppliesTo {
            get {
                return ResourceManager.GetString("SelectWhatKindOfContentThisOptionAppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self Only 的本地化字符串。
        /// </summary>
        internal static string SelfOnly {
            get {
                return ResourceManager.GetString("SelfOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shield Check: Percentage of Party Members without shields to check for. 的本地化字符串。
        /// </summary>
        internal static string ShieldCheckPartyMemberNeedPercent {
            get {
                return ResourceManager.GetString("ShieldCheckPartyMemberNeedPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soft Target 的本地化字符串。
        /// </summary>
        internal static string SoftTarget {
            get {
                return ResourceManager.GetString("SoftTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard opener 的本地化字符串。
        /// </summary>
        internal static string StandardOpener {
            get {
                return ResourceManager.GetString("StandardOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start using when below party average HP %. Set to 100 to disable this check 的本地化字符串。
        /// </summary>
        internal static string StartUsingWhenBelowPartyAverageHPSetTo100ToDisableThisCheck {
            get {
                return ResourceManager.GetString("StartUsingWhenBelowPartyAverageHPSetTo100ToDisableThisCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Stationary Delay Check (in seconds): 的本地化字符串。
        /// </summary>
        internal static string StationaryDelayCheck {
            get {
                return ResourceManager.GetString("StationaryDelayCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stationary Only 的本地化字符串。
        /// </summary>
        internal static string StationaryOnly {
            get {
                return ResourceManager.GetString("StationaryOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop using when average health percentage of nearby enemies is below set.
        ///(Set to 0 to disable this check) 的本地化字符串。
        /// </summary>
        internal static string StopBelowAverageEnemyHP {
            get {
                return ResourceManager.GetString("StopBelowAverageEnemyHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop using when below Enemy HP %.
        ///        Set to Zero to disable this check. 的本地化字符串。
        /// </summary>
        internal static string StopEnemyHpPercent {
            get {
                return ResourceManager.GetString("StopEnemyHpPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start using when below HP %.
        ///       Set to 100 to disable this check 的本地化字符串。
        /// </summary>
        internal static string StopFriendlyHpPercent100 {
            get {
                return ResourceManager.GetString("StopFriendlyHpPercent100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop using when below HP %. Set to Zero to disable this check 的本地化字符串。
        /// </summary>
        internal static string StopFriendlyHpPercentZero {
            get {
                return ResourceManager.GetString("StopFriendlyHpPercentZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Seconds remaining before reapplying (0 = Do not reapply early) 的本地化字符串。
        /// </summary>
        internal static string StopSeconds {
            get {
                return ResourceManager.GetString("StopSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Using {0} When Target HP% is at or Below (Set to 0 to Disable This Check) 的本地化字符串。
        /// </summary>
        internal static string StopUsing0WhenBelowTargetHPPercentage {
            get {
                return ResourceManager.GetString("StopUsing0WhenBelowTargetHPPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop using when below set percentage 的本地化字符串。
        /// </summary>
        internal static string StopUsingWhenBelowSetPercentage {
            get {
                return ResourceManager.GetString("StopUsingWhenBelowSetPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Using when Target HP% is at or Below (Set to 0 to Disable This Check) 的本地化字符串。
        /// </summary>
        internal static string StopUsingWhenBelowTargetHPPercent {
            get {
                return ResourceManager.GetString("StopUsingWhenBelowTargetHPPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tanks Only 的本地化字符串。
        /// </summary>
        internal static string TanksOnly {
            get {
                return ResourceManager.GetString("TanksOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target HP% to use {0} at or below. Set to 100 to disable this check. 的本地化字符串。
        /// </summary>
        internal static string TargetHPUse0AtOrBelow {
            get {
                return ResourceManager.GetString("TargetHPUse0AtOrBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Remaining on {0} to allow within
        ///(0 = Dismantled must not be on the target) 的本地化字符串。
        /// </summary>
        internal static string TimeRemainingOn0 {
            get {
                return ResourceManager.GetString("TimeRemainingOn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Remaining on others {0} to allow within
        ///(0 = {0} must not be on the target) 的本地化字符串。
        /// </summary>
        internal static string TimeRemainingOnOthers {
            get {
                return ResourceManager.GetString("TimeRemainingOnOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Remaining on others {0} / {1} / {2} to allow within
        ///(0 = {0} / {1} / {2} must not be on the target) 的本地化字符串。
        /// </summary>
        internal static string TimeRemainingOnOthers3 {
            get {
                return ResourceManager.GetString("TimeRemainingOnOthers3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two target dotting 的本地化字符串。
        /// </summary>
        internal static string TwoTargetDotting {
            get {
                return ResourceManager.GetString("TwoTargetDotting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will maintain Damage over time spells on two targets if applicable. 的本地化字符串。
        /// </summary>
        internal static string TwoTargetDottingDescription {
            get {
                return ResourceManager.GetString("TwoTargetDottingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} Opener 的本地化字符串。
        /// </summary>
        internal static string Use_0_Opener {
            get {
                return ResourceManager.GetString("Use_0_Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} 的本地化字符串。
        /// </summary>
        internal static string Use0 {
            get {
                return ResourceManager.GetString("Use0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} in {1} 的本地化字符串。
        /// </summary>
        internal static string Use0In1 {
            get {
                return ResourceManager.GetString("Use0In1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string Use0Or1 {
            get {
                return ResourceManager.GetString("Use0Or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} regardless of content. 的本地化字符串。
        /// </summary>
        internal static string Use0RegardlessOfContent {
            get {
                return ResourceManager.GetString("Use0RegardlessOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} when {1} charges are available. 的本地化字符串。
        /// </summary>
        internal static string Use0When1ChargesAreAvailable {
            get {
                return ResourceManager.GetString("Use0When1ChargesAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} when in range of a selected enemy target. 的本地化字符串。
        /// </summary>
        internal static string Use0WhenInRangeOfEnemy {
            get {
                return ResourceManager.GetString("Use0WhenInRangeOfEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} only while stationary 的本地化字符串。
        /// </summary>
        internal static string UseActionOnlyWhileStationary {
            get {
                return ResourceManager.GetString("UseActionOnlyWhileStationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use always. 的本地化字符串。
        /// </summary>
        internal static string UseAlways {
            get {
                return ResourceManager.GetString("UseAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses {0} regardless of any movement conditions.
        ///NOTE: This could possibly get you killed 的本地化字符串。
        /// </summary>
        internal static string Uses0RegardlessOfAnyMovementConditions {
            get {
                return ResourceManager.GetString("Uses0RegardlessOfAnyMovementConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses Standard opener 的本地化字符串。
        /// </summary>
        internal static string UsesStandardOpener {
            get {
                return ResourceManager.GetString("UsesStandardOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Use when Distance from target is less than or equal to: 的本地化字符串。
        /// </summary>
        internal static string UseWhenDistanceFromTargetIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("UseWhenDistanceFromTargetIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add {0} to the priority stack 的本地化字符串。
        /// </summary>
        internal static string WillAdd_0_ToThePriorityStack {
            get {
                return ResourceManager.GetString("WillAdd_0_ToThePriorityStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will not use in Boss encounters. 的本地化字符串。
        /// </summary>
        internal static string WillNotUseInBossEncounters {
            get {
                return ResourceManager.GetString("WillNotUseInBossEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will only use on Tanks 的本地化字符串。
        /// </summary>
        internal static string WillOnlyUseOnTanks {
            get {
                return ResourceManager.GetString("WillOnlyUseOnTanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will only weave this action. 的本地化字符串。
        /// </summary>
        internal static string WillOnlyWeaveThisAction {
            get {
                return ResourceManager.GetString("WillOnlyWeaveThisAction", resourceCulture);
            }
        }
    }
}
