//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MCH_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MCH_Config() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.MCH_Config", typeof(MCH_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Also use {0} / {1} on cooldown. 的本地化字符串。
        /// </summary>
        internal static string AlsoUse0Or1OnCooldown {
            get {
                return ResourceManager.GetString("AlsoUse0Or1OnCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery threshold 的本地化字符串。
        /// </summary>
        internal static string BatteryThreshold {
            get {
                return ResourceManager.GetString("BatteryThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes to {0} / {1} depending on charges and what was used last 的本地化字符串。
        /// </summary>
        internal static string ChangesTo0Or1 {
            get {
                return ResourceManager.GetString("ChangesTo0Or1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Early {0} opener 的本地化字符串。
        /// </summary>
        internal static string Early0Opener {
            get {
                return ResourceManager.GetString("Early0Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saves {0} for 2 minute windows
        ///THIS WILL CAUSE IT TO OVERCAP! 的本地化字符串。
        /// </summary>
        internal static string Save0ForEvenWindows {
            get {
                return ResourceManager.GetString("Save0ForEvenWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save for 2 minute windows 的本地化字符串。
        /// </summary>
        internal static string SaveForEvenWindows {
            get {
                return ResourceManager.GetString("SaveForEvenWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Using Tools When Target HP% is at or Below (Set to 0 to Disable This Check) 的本地化字符串。
        /// </summary>
        internal static string StopUsingToolsBelowHpPercentage {
            get {
                return ResourceManager.GetString("StopUsingToolsBelowHpPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses {0} every minute/whenever your highest level tool is off cooldown. 的本地化字符串。
        /// </summary>
        internal static string Use0EveryMinute {
            get {
                return ResourceManager.GetString("Use0EveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses Early {0} level 100 opener 的本地化字符串。
        /// </summary>
        internal static string UseEarly0Opener {
            get {
                return ResourceManager.GetString("UseEarly0Opener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use every minute 的本地化字符串。
        /// </summary>
        internal static string UseEveryMinute {
            get {
                return ResourceManager.GetString("UseEveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use {0} at this battery threshold outside of Boss encounter. 的本地化字符串。
        /// </summary>
        internal static string UseQueenOutsideOfBoss {
            get {
                return ResourceManager.GetString("UseQueenOutsideOfBoss", resourceCulture);
            }
        }
    }
}
