//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MNK_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MNK_Config() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.MNK_Config", typeof(MNK_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Double Lunar 的本地化字符串。
        /// </summary>
        internal static string DoubleLunarOpener {
            get {
                return ResourceManager.GetString("DoubleLunarOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses Lunar/Lunar opener. 的本地化字符串。
        /// </summary>
        internal static string DoubleLunarOpenerDesc {
            get {
                return ResourceManager.GetString("DoubleLunarOpenerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces {0} with {1} when {2} is on cooldown. 的本地化字符串。
        /// </summary>
        internal static string Repalce0With1When2IsOnCooldown {
            get {
                return ResourceManager.GetString("Repalce0With1When2IsOnCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solar Lunar 的本地化字符串。
        /// </summary>
        internal static string SolarLunarOpener {
            get {
                return ResourceManager.GetString("SolarLunarOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses Solar/Lunar opener. 的本地化字符串。
        /// </summary>
        internal static string SolarLunarOpenerDesc {
            get {
                return ResourceManager.GetString("SolarLunarOpenerDesc", resourceCulture);
            }
        }
    }
}
