//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SGE_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SGE_Config() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.SGE_Config", typeof(SGE_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Any {0} check 的本地化字符串。
        /// </summary>
        internal static string AnyPanhaimaCheck {
            get {
                return ResourceManager.GetString("AnyPanhaimaCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable to not override an existing {0}. 的本地化字符串。
        /// </summary>
        internal static string AnyPanhaimaCheckDesc {
            get {
                return ResourceManager.GetString("AnyPanhaimaCheckDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for {0} Trait (Heal over Time) 的本地化字符串。
        /// </summary>
        internal static string KerecholeTraitCheck {
            get {
                return ResourceManager.GetString("KerecholeTraitCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling this will prevent {0} from being used when the Heal over Time trait is unavailable. 的本地化字符串。
        /// </summary>
        internal static string KerecholeTraitCheckDesc {
            get {
                return ResourceManager.GetString("KerecholeTraitCheckDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add {0} at beginning 的本地化字符串。
        /// </summary>
        internal static string SGE_Mit_AoE_Kerachole_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_AoE_Kerachole_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add {0} at the end 的本地化字符串。
        /// </summary>
        internal static string SGE_Mit_AoE_Panhaima_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_AoE_Panhaima_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add {0} before {1} for the Healing Boost 的本地化字符串。
        /// </summary>
        internal static string SGE_Mit_AoE_Philosophia_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_AoE_Philosophia_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shield Check: Percentage of Party Members to get {0} shields. 
        ///0 = Dont use, 100 = everyone needs shields 的本地化字符串。
        /// </summary>
        internal static string SGE_Mit_AoE_PrognosisOption_Name {
            get {
                return ResourceManager.GetString("SGE_Mit_AoE_PrognosisOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add {0} for more mitigation. 的本地化字符串。
        /// </summary>
        internal static string SGE_Mit_ST_Haima_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_ST_Haima_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add {0} to top off targets health and add Damage reduction. 的本地化字符串。
        /// </summary>
        internal static string SGE_Mit_ST_Taurochole_Help {
            get {
                return ResourceManager.GetString("SGE_Mit_ST_Taurochole_Help", resourceCulture);
            }
        }
    }
}
