//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VPR_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VPR_Config() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.VPR_Config", typeof(VPR_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Adds {0} when available.
        /// Respects the manual {0} charge. 的本地化字符串。
        /// </summary>
        internal static string Add0WhenAvailableRespectManualCharge {
            get {
                return ResourceManager.GetString("Add0WhenAvailableRespectManualCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds range check for {0}, so it is used only when in range. 的本地化字符串。
        /// </summary>
        internal static string AddRangeCheckFor0 {
            get {
                return ResourceManager.GetString("AddRangeCheckFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adds range check for {0} and {1}, so it is used only when in range. 的本地化字符串。
        /// </summary>
        internal static string AddRangeCheckFor0And1 {
            get {
                return ResourceManager.GetString("AddRangeCheckFor0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables the range check for {0}, so it will be used even without a target selected. 的本地化字符串。
        /// </summary>
        internal static string DisableRangeCheckFor0 {
            get {
                return ResourceManager.GetString("DisableRangeCheckFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables the range check for {0} and {1}, so it will be used even without a target selected. 的本地化字符串。
        /// </summary>
        internal static string DisableRangeCheckFor0And1 {
            get {
                return ResourceManager.GetString("DisableRangeCheckFor0And1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forces {0} or {1} if buff needs to be reapplied. 的本地化字符串。
        /// </summary>
        internal static string Forces0Or1ForBuffs {
            get {
                return ResourceManager.GetString("Forces0Or1ForBuffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set a HP% threshold to use {0} whenever available. (Bosses Only) 的本地化字符串。
        /// </summary>
        internal static string HPPThresholdWheneverAvailableBossesOnly {
            get {
                return ResourceManager.GetString("HPPThresholdWheneverAvailableBossesOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replaces {0} with Full Generation - Legacy combo. 的本地化字符串。
        /// </summary>
        internal static string Replace0WithFullCombo {
            get {
                return ResourceManager.GetString("Replace0WithFullCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will hold the last charge of {0} for use with {1}, even when out of position for normal GCD.
        ///If above slider is set to 1, it will NOT use the remaining charge for {1}, but for manual use. 的本地化字符串。
        /// </summary>
        internal static string WillHoldLastChargeOf0For1 {
            get {
                return ResourceManager.GetString("WillHoldLastChargeOf0For1", resourceCulture);
            }
        }
    }
}
