//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WHM_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WHM_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.WHM_Config", typeof(WHM_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to On Stones/Glares.
        /// </summary>
        internal static string OnStonesGlares {
            get {
                return ResourceManager.GetString("OnStonesGlares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply options to all Stones and Glares..
        /// </summary>
        internal static string OnStonesGlaresDesc {
            get {
                return ResourceManager.GetString("OnStonesGlaresDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Aeros/Dia.
        /// </summary>
        internal static string OnAerosDia {
            get {
                return ResourceManager.GetString("OnAerosDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply options to all Aeros And Dia..
        /// </summary>
        internal static string OnAerosDiaDesc {
            get {
                return ResourceManager.GetString("OnAerosDiaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Stone II.
        /// </summary>
        internal static string OnStoneII {
            get {
                return ResourceManager.GetString("OnStoneII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply options to Stone II..
        /// </summary>
        internal static string OnStoneIIDesc {
            get {
                return ResourceManager.GetString("OnStoneIIDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold for Burst.
        /// </summary>
        internal static string HoldForBurst {
            get {
                return ResourceManager.GetString("HoldForBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will attempt to hold for burst as long as possible without overcapping.  Will prevent afflatus heals from being possible when at full Blood Lily stacks..
        /// </summary>
        internal static string HoldForBurstDesc {
            get {
                return ResourceManager.GetString("HoldForBurstDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Immediately.
        /// </summary>
        internal static string UseImmediately {
            get {
                return ResourceManager.GetString("UseImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will Use Immediately to make sure you are free to use Afflatus heals..
        /// </summary>
        internal static string UseImmediatelyDesc {
            get {
                return ResourceManager.GetString("UseImmediatelyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in Seconds to use Afflatus Rapture before overcapping Lily stacks.
        /// </summary>
        internal static string LilyOvercapSeconds {
            get {
                return ResourceManager.GetString("LilyOvercapSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Charges Option.
        /// </summary>
        internal static string BalanceChargesOption {
            get {
                return ResourceManager.GetString("BalanceChargesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only use if Tetra Charges are greater than or equal to Divine Benison Charges..
        /// </summary>
        internal static string TetraBalanceDesc {
            get {
                return ResourceManager.GetString("TetraBalanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only use if Divine Benison Charges are greater than or equal to Tetragrammaton Charges..
        /// </summary>
        internal static string BenisonBalanceDesc {
            get {
                return ResourceManager.GetString("BenisonBalanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Number of allies in range of Cure 3 target.
        /// </summary>
        internal static string Cure3MinAllies {
            get {
                return ResourceManager.GetString("Cure3MinAllies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP to be over.
        /// </summary>
        internal static string MpToBeOver {
            get {
                return ResourceManager.GetString("MpToBeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target HP% to use Tetra below).
        /// </summary>
        internal static string TetraHpThreshold {
            get {
                return ResourceManager.GetString("TetraHpThreshold", resourceCulture);
            }
        }

    }
}