using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class ASTDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region AST                
                KeyValuePair.Create("Replaces Malefic or Combust with options below", "用下方选项替换凶星或烧灼"),
                KeyValuePair.Create("Adds Combust to the DPS feature if it's not present on current target, or is about to expire.", "如果当前目标没有烧灼或即将失效，则将其添加到DPS功能中。"),
                KeyValuePair.Create("Adds Lightspeed when moving", "移动时添加光速"),
                KeyValuePair.Create("Adds Lucid Dreaming when MP drops below slider value", "当MP低于滑块值时添加醒梦"),
                KeyValuePair.Create("Adds Divination", "添加占卜"),
                KeyValuePair.Create("Draws your cards", "抽卡"),
                KeyValuePair.Create("Weaves your Balance or Spear card (best used with Quick Target Cards)", "插入你的太阳神之衡或战争神之枪卡（最好与快速目标发卡一起使用）"),
                KeyValuePair.Create("Adds Lord Of Crowns", "添加王冠之领主"),
                KeyValuePair.Create("Adds Oracle after Divination", "在占卜后添加神谕"),
                KeyValuePair.Create("Replaces Gravity with options below", "用下方选项替换重力"),
                KeyValuePair.Create("Replaces Benefic II with a one button healing replacement.", "用一个按钮的治疗替换福星。"),
                KeyValuePair.Create("Essential Dignity will be added when the target is at or below the value set", "当目标处于或低于设定值时添加先天禀赋"),
                KeyValuePair.Create("Adds Celestial Intersection.", "添加天星交错。"),
                KeyValuePair.Create("Adds Aspected Benefic & refreshes it if needed.", "添加吉星相位并在需要时刷新它。"),
                KeyValuePair.Create("Adds Exaltation.", "添加擢升。"),
                KeyValuePair.Create("Adds The Spire (Shield) when the card has been drawn", "当抽到建筑神之塔（护盾）时添加"),
                KeyValuePair.Create("Adds The Ewer (Heal over time) when the card has been drawn", "当抽到河流神之瓶（持续治疗）时添加"),
                KeyValuePair.Create("Adds The Arrow (increased healing)  when the card has been drawn", "当抽到放浪神之箭（增加治疗）时添加"),
                KeyValuePair.Create("Adds The Bole (Reduced Damage) when the card has been drawn", "当抽到世界树之干（减少伤害）时添加"),
                KeyValuePair.Create("Replaces Aspected Helios/Helios Conjunction or Helios with a one button healing replacement.", "用一个按钮的治疗替换阳星相位/阳星合相或阳星。"),
                KeyValuePair.Create("Adds Celestial Opposition", "添加天星冲日"),
                KeyValuePair.Create("Adds Lady of Crowns, if the card is drawn", "如果抽到王冠之贵妇，则添加"),
                KeyValuePair.Create("Adds Horoscope.", "添加天宫图。"),
                KeyValuePair.Create("Changes Benefic 2 to Benefic when Benefic 2 is not unlocked or available.", "当福星未解锁或不可用时，将其更改为吉星。"),
                KeyValuePair.Create("Changes Swiftcast to Ascend", "将即刻咏唱更改为生辰"),
                KeyValuePair.Create("When you play the Balance or Spear, this will automatically apply the buff to a party member. It will look at DPS that suit the card first, if none found or they have buffs already, will look at the other DPS instead.", "当你使用太阳神之衡或放浪神之箭时，自动将卡发给一名队员。它将首先考虑发给适合该卡的进攻职业，如果没有找到或他们已经拥有进攻卡，则会发给其他进攻职业。"),
                KeyValuePair.Create("Targets a tank or healer if no DPS remain for quick target selection", "如果没有剩余的DPS用于快速目标选择，则选择坦克或治疗者"),
                KeyValuePair.Create("Turns Fall Malefic into an all-in-one damage button.", "将落陷凶星变成一个全能伤害按钮。"),
                KeyValuePair.Create("Adds Drawing Cards to Burst Mode.", "将抽卡添加到爆发模式。"),
                KeyValuePair.Create("Adds Playing Cards to Burst Mode.", "将使用卡添加到爆发模式。"),
                KeyValuePair.Create("Adds Double Cast to Aspected Benefic.", "为吉星相位添加双重施法。"),
                KeyValuePair.Create("Adds Double Malefic Cast to Burst Mode.", "将双重凶星施法添加到爆发模式。"),
                KeyValuePair.Create("Adds Double Gravity Cast to Burst Mode.", "将双重重力施法添加到爆发模式。"),
                KeyValuePair.Create("Adds Gravity Cast to Burst Mode.", "将重力施法添加到爆发模式。"),
                KeyValuePair.Create("Adds Macrocosmos to Burst Mode. ", "将大宇宙添加到爆发模式。"),
                KeyValuePair.Create(" If Double Gravity is enabled, it will hold Macrocosmos for the double gravity burst.", "如果启用了双重重力，它将保留大宇宙用于双重重力爆发。"),
                KeyValuePair.Create("Turns Epicycle into burst combo.", "将本轮转变为爆发连击。"),
                KeyValuePair.Create("Card Draw", "抽卡"),
                KeyValuePair.Create("Card Play", "出卡"),
                KeyValuePair.Create("Quick Target Damage Cards", "伤害卡快速目标发放"),
                KeyValuePair.Create("Add Tanks/Healers to Auto-Target", "将防护职业和治疗职业加入发卡目标"),
                KeyValuePair.Create("No Override", "不覆盖"),
                KeyValuePair.Create("Hard Target Override", "强制目标覆盖"),
                KeyValuePair.Create("Overrides selection with hard target if you have one", "如果你选择了可以发卡的目标，则覆盖发卡"),
                KeyValuePair.Create("UI Mousover Override", "UI鼠标悬停覆盖"),
                KeyValuePair.Create("Overrides selection with UI mouseover target if you have one", "如果存在UI鼠标悬停目标，为鼠标悬停目标发卡"),
                KeyValuePair.Create("Skip targets with a 伤害降低 debuff", "跳过有伤害降低debuff的目标"),
                KeyValuePair.Create("Skip targets with a 衰弱 or 濒死 debuff", "跳过有衰弱或濒死debuff的目标"),
                KeyValuePair.Create("Downgrade", "降级"),
                KeyValuePair.Create("In Helios mode: Will Cast Aspected Helios/Helios Conjunction when the HoT is missing on yourself.", "在阳星模式下：当你身上缺少HoT效果时，会根据情况自动施放阳星相位或阳星合相。"),
                KeyValuePair.Create("In Aspected Helios mode: Is considered enabled regardless.", "在阳星相位下：无论条件如何，均视为启用。"),
                KeyValuePair.Create("Alternative AOE Mode. Leaves Aspected Helios alone for manual HoTs", "替代AOE模式。保留阳星相位用于手动施放HoT效果"),
                KeyValuePair.Create("Alternative DPS Mode. Leaves 凶星 alone for pure DPS, becomes 凶星 when features are on cooldown", "替代DPS模式。保留凶星用于纯DPS输出，当技能处于冷却时切换为凶星"),
                KeyValuePair.Create("Double Gravity Cast Option", "双重重力"),
                KeyValuePair.Create("Overwrite Non-DPS Cards", "覆盖非输出卡牌"),
                KeyValuePair.Create("Will draw even if you have healing cards remaining.", "即使你仍有治疗卡牌，也会抽取。"),
                KeyValuePair.Create("Set percentage value", "设置百分比值"),
                KeyValuePair.Create("Will only weave this action.", "仅会穿插此技能。"),
                #endregion

                #region ASTPvP
                KeyValuePair.Create("Lord and Lady card play", "领主和贵妇卡组合使用"),
                KeyValuePair.Create("Uses Lord and Lady of Crowns when available.", "当王冠之贵妇和王冠之领主可用时同时使用"),
                KeyValuePair.Create("Lord of Crowns card play", "仅使用王冠之领主卡"),
                KeyValuePair.Create("Only uses Lord of Crowns when available.", "仅当王冠之领主卡可用时使用"),
                KeyValuePair.Create("Lady of Crowns card play", "仅使用王冠之贵妇卡"),
                KeyValuePair.Create("Only uses Lady of Crowns when available.", "仅当王冠之贵妇卡可用时使用")
                #endregion
            ];
        }
    }
}
