using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BLMPvE
                KeyValuePair.Create("Replaces Fire with a full one-button single target rotation.", "用一键单体循环替换Fire。"),
                KeyValuePair.Create("Replaces Blizzard II with a full one-button AoE rotation.", "用一键AOE循环替换Blizzard II。"),
                KeyValuePair.Create("Need a GCD of 2.45 or lower to use.", "需要使用GCD为2.45或更低的技能。"),
                KeyValuePair.Create("Add Leylines to the rotation.", "将Leylines加入循环。"),
                KeyValuePair.Create("Add Amplifier to the rotation.", "将Amplifier加入循环。"),
                KeyValuePair.Create("Add Manafont to the rotation.", "将Manafont加入循环。"),
                KeyValuePair.Create("Add (High) Thunder to the rotation.", "将（高）闪雷加入循环。"),
                KeyValuePair.Create("Add Despair to the rotation.", "将Despair加入循环。"),
                KeyValuePair.Create("Add Swiftcast to the rotation.", "将Swiftcast加入循环。"),
                KeyValuePair.Create("Add Triplecast to the rotation.", "将Triplecast加入循环。"),
                KeyValuePair.Create("Add Transpose to the rotation.", "将Transpose加入循环。"),
                KeyValuePair.Create("Add Foul/Xenoglossy to the rotation.", "将Foul/Xenoglossy加入循环。"),
                KeyValuePair.Create("Add Foul / Xenoglossy to the rotation as movement option.", "将Foul / Xenoglossy作为移动选项加入循环。"),
                KeyValuePair.Create("Add Flare to the rotation.", "将Flare加入循环。"),
                KeyValuePair.Create("Add Foul to the rotation.", "将Foul加入循环。"),
                KeyValuePair.Create("Add Foul to the rotation as movement option.", "将Foul作为移动选项加入循环。"),
                KeyValuePair.Create("Replaces Triplecast with Savage Blade when you already have triplecast active.", "当你已经激活了Triplecast时，将Triplecast替换为Savage Blade。"),
                KeyValuePair.Create("Replaces Transpose with Umbral Soul when Umbral Soul is available.", "当Umbral Soul可用时，将Transpose替换为Umbral Soul。"),
                KeyValuePair.Create("Replaces Scathe with Xenoglossy when available.", "当Xenoglossy可用时，将Scathe替换为Xenoglossy。"),
                KeyValuePair.Create("Replaces Aetherial Manipulation with Between the Lines when you are out of active Ley Lines and standing still.", "当你不在激活的黑魔纹范围内且站立不动时，将以太步替换为魔纹步。"),
                KeyValuePair.Create("(High) Thunder Option", "（高）闪雷"),
                KeyValuePair.Create("Flare Star Option", "耀星"),
                KeyValuePair.Create("Add Flare Star to the rotation.", "将耀星添加到循环中。"),
                KeyValuePair.Create("Foul/Xenoglossy for Movement Option", "秽浊/异言移动选项"),
                KeyValuePair.Create("(High) Thunder II Option", "（高）震雷"),
                KeyValuePair.Create("Add (High) Thunder II to the rotation.", "将（高）震雷添加到循环中。"),
                KeyValuePair.Create("Fire I/III Feature", "火炎/爆炎"),
                KeyValuePair.Create("Replaces Fire I with Fire III outside of Astral Fire or when Firestarter is up.", "不在星极火状态或触发火苗时，将火炎替换为爆炎。"),
                KeyValuePair.Create("Blizzard I/III Feature", "冰结/冰封"),
                KeyValuePair.Create("Replaces Blizzard I with Blizzard III when out of Umbral Ice.", "不在灵极冰状态时，将冰结替换为冰封。"),
                KeyValuePair.Create("Replaces Freeze with Blizzard II when synced below Lv.40.", "在同步等级低于 40 时，将冰冻替换为玄冰。"),
                KeyValuePair.Create("Fire & Ice", "火与冰"),
                KeyValuePair.Create("Replaces Fire4 with Blizzard4 when in Umbral Ice.", "在灵极冰状态下，将炽炎替换为冰澈。"),
                KeyValuePair.Create("Between the Ley Lines Feature", "魔纹之间功能"),
                KeyValuePair.Create("Replaces Ley Lines with Between the Lines when Ley Lines is active.", "当黑魔纹激活时，将黑魔纹替换为魔纹步。"),
                KeyValuePair.Create("Set the amount of time remaining on Triplecast charge before using.(Only when at threshold)", "设置在使用三重咏唱充能前的剩余时间。（仅在达到阈值时）"),
                #endregion
                
                #region BLMPvP
                KeyValuePair.Create("Turns Fire into an all-in-one button.", "将Fire变为一个多功能按钮。"),
                KeyValuePair.Create("- Uses Blizzard spells while moving (One Button Mode only).", "- 在移动时使用Blizzard法术（仅限一键模式）。"),
                KeyValuePair.Create("- Will use Paradox when appropriate.", "- 在适当时机使用Paradox。"),
                KeyValuePair.Create("Uses Burst when available.", "在可用时使用Burst。"),
                KeyValuePair.Create("- Requires target to be within range.", "- 需要目标在范围内。"),
                KeyValuePair.Create("Uses Xenoglossy when available.", "在可用时使用Xenoglossy。"),
                KeyValuePair.Create("Uses Lethargy when available.", "在可用时使用Lethargy。"),
                KeyValuePair.Create("- Will not use against non-players.", "- 不会对非玩家使用。"),
                KeyValuePair.Create("Uses Wreath of Fire when available.", "在可用时使用Wreath of Fire。"),
                KeyValuePair.Create("- Requires player's HP to be at or above:", "- 需要玩家的生命值达到或高于："),
                KeyValuePair.Create("Elemental Weave Option", "元素天赋穿插"),
                KeyValuePair.Create("Uses Elemental Star when available.", "在可用时使用Elemental Star。"),
                KeyValuePair.Create("- Prioritizes Flare Star unless expiring.", "- 优先使用耀星，除非即将结束。"),
                #endregion
            ];
        }
    }
}
