using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BLMPvE
                KeyValuePair.Create("Replaces Fire with a full one-button single target rotation.", "用一键单体循环替换火炎。"),
                KeyValuePair.Create("Replaces Blizzard II with a full one-button AoE rotation.", "用一键AOE循环替换冰冻。"),
                KeyValuePair.Create("Need a GCD of 2.45 or lower to use.", "需要使用GCD为2.45或更低的技能。"),
                KeyValuePair.Create("Add Leylines to the rotation.", "将黑魔纹加入循环。"),
                KeyValuePair.Create("Add Amplifier to the rotation.", "将详述加入循环。"),
                KeyValuePair.Create("Add Manafont to the rotation.", "将魔泉加入循环。"),
                KeyValuePair.Create("Add (High) Thunder to the rotation.", "将（高）闪雷加入循环。"),
                KeyValuePair.Create("Add Despair to the rotation.", "将绝望加入循环。"),
                KeyValuePair.Create("Add Swiftcast to the rotation.", "将Swiftcast加入循环。"),
                KeyValuePair.Create("Add Triplecast to the rotation.", "将三连咏唱加入循环。"),
                KeyValuePair.Create("Add Transpose to the rotation.", "将星灵移位加入循环。"),
                KeyValuePair.Create("Add Foul/Xenoglossy to the rotation.", "将秽浊/异言加入循环。"),
                KeyValuePair.Create("Add Foul / Xenoglossy to the rotation as movement option.", "将秽浊 / 异言作为移动选项加入循环。"),
                KeyValuePair.Create("Add Flare to the rotation.", "将核爆加入循环。"),
                KeyValuePair.Create("Add Foul to the rotation.", "将秽浊加入循环。"),
                KeyValuePair.Create("Add Foul to the rotation as movement option.", "将秽浊作为移动选项加入循环。"),
                KeyValuePair.Create("Replaces Triplecast with Savage Blade when you already have triplecast active.", "当你已经激活了三连咏唱时，将三连咏唱替换为Savage Blade。"),
                KeyValuePair.Create("Replaces Transpose with Umbral Soul when Umbral Soul is available.", "当灵极魂可用时，将星灵移位替换为灵极魂。"),
                KeyValuePair.Create("Replaces Scathe with Xenoglossy when available.", "当异言可用时，将崩溃替换为异言。"),
                KeyValuePair.Create("Replaces Aetherial Manipulation with Between the Lines when you are out of active Ley Lines and standing still.", "当你不在激活的黑魔纹范围内且站立不动时，将以太步替换为魔纹步。"),
                KeyValuePair.Create("(High) Thunder Option", "（高）闪雷"),
                KeyValuePair.Create("Flare Star Option", "耀星"),
                KeyValuePair.Create("Add Flare Star to the rotation.", "将耀星添加到循环中。"),
                KeyValuePair.Create("Foul/Xenoglossy for Movement Option", "秽浊/异言移动选项"),
                KeyValuePair.Create("(High) Thunder II Option", "（高）震雷"),
                KeyValuePair.Create("Add (High) Thunder II to the rotation.", "将（高）震雷添加到循环中。"),
                KeyValuePair.Create("Fire I/III Feature", "火炎/爆炎"),
                KeyValuePair.Create("Replaces Fire I with Fire III outside of Astral Fire or when Firestarter is up.", "不在星极火状态或触发火苗时，将火炎替换为爆炎。"),
                KeyValuePair.Create("Blizzard I/III Feature", "冰结/冰封"),
                KeyValuePair.Create("Replaces Blizzard I with Blizzard III when out of Umbral Ice.", "不在灵极冰状态时，将冰结替换为冰封。"),
                KeyValuePair.Create("Replaces Freeze with Blizzard II when synced below Lv.40.", "在同步等级低于 40 时，将玄冰替换为冰冻。"),
                KeyValuePair.Create("Fire & Ice", "火与冰"),
                KeyValuePair.Create("Replaces Fire4 with Blizzard4 when in Umbral Ice.", "在灵极冰状态下，将炽炎替换为冰澈。"),
                KeyValuePair.Create("Between the Ley Lines Feature", "魔纹之间功能"),
                KeyValuePair.Create("Replaces Ley Lines with Between the Lines when Ley Lines is active.", "当黑魔纹激活时，将黑魔纹替换为魔纹步。"),
                KeyValuePair.Create("Set the amount of time remaining on Triplecast charge before using.(Only when at threshold)", "设置在使用三重咏唱充能前的剩余时间。（仅在达到阈值时）"),
                #endregion
                
                #region BLMPvP
                KeyValuePair.Create("Turns Fire into an all-in-one button.", "将火炎变为一个多功能按钮。"),
                KeyValuePair.Create("- Uses Blizzard spells while moving (One Button Mode only).", "- 在移动时使用冰结法术（仅限一键模式）。"),
                KeyValuePair.Create("- Will use Paradox when appropriate.", "- 在适当时机使用Paradox。"),
                KeyValuePair.Create("Uses Burst when available.", "在可用时使用Burst。"),
                KeyValuePair.Create("- Requires target to be within range.", "- 需要目标在范围内。"),
                KeyValuePair.Create("Uses Xenoglossy when available.", "在可用时使用异言。"),
                KeyValuePair.Create("Uses Lethargy when available.", "在可用时使用昏沉。"),
                KeyValuePair.Create("- Will not use against non-players.", "- 不会对非玩家使用。"),
                KeyValuePair.Create("Uses Wreath of Fire when available.", "在可用时使用烈火环。"),
                KeyValuePair.Create("- Requires player's HP to be at or above:", "- 需要玩家的生命值达到或高于："),
                KeyValuePair.Create("Elemental Weave Option", "元素天赋穿插"),
                KeyValuePair.Create("Uses Elemental Star when available.", "在可用时使用元素之星。"),
                KeyValuePair.Create("- Prioritizes Flare Star unless expiring.", "- 优先使用耀星，除非即将结束。"),
                KeyValuePair.Create("One Button Mode", "单按钮模式"),
                KeyValuePair.Create("Combines Fire & Blizzard onto one button", "将火炎与冰结技能合并到一个按钮"),
                KeyValuePair.Create("Dual Button Mode", "双按钮模式"),
                KeyValuePair.Create("Puts the combo onto separate Fire & Blizzard buttons, which will only use that element.", "将连击分配到独立的火炎与冰结按钮，各按钮仅使用对应元素技能"),
                KeyValuePair.Create("When under the effect of Astral Fire, must be moving this long before using Blizzard spells.", "处于星极火状态时，必须移动指定时长才能使用冰系法术"),
                KeyValuePair.Create("Defensive Burst", "防御性爆发"),
                KeyValuePair.Create("Also uses Burst when under 50% HP.", "50%血量以下时也会使用爆发"),
                KeyValuePair.Create("Will not use outside combat.", "非战斗状态下不使用"),
                KeyValuePair.Create("Defensive Xenoglossy", "防御性异言"),
                KeyValuePair.Create("Also uses Xenoglossy when under 50% HP.", "50%血量以下时也会使用异言"),
                KeyValuePair.Create("Defensive Lethargy", "防御性昏乱"),
                KeyValuePair.Create("Also uses Lethargy when under 50% HP.", "50%血量以下时也会使用昏乱"),
                KeyValuePair.Create("Uses only when targeted by enemy.", "仅在被敌人锁定目标时使用"),
                KeyValuePair.Create("Defensive Elemental Weave", "防御性元素天赋穿插"),
                KeyValuePair.Create("When under, uses Wreath of Ice instead.", "血量低下时改用寒冰环"),
                #endregion
            ];
        }
    }
}
