using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using static WrathCombo.Combos.PvE.BLM;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BLMPvE
                KeyValuePair.Create("Replaces Fire with a full one-button single target rotation.", "用一键单体循环替换火炎。"),
                KeyValuePair.Create("Replaces Blizzard II with a full one-button AoE rotation.", "用一键AOE循环替换冰冻。"),
                KeyValuePair.Create("Need a GCD of 2.45 or lower to use.", "需要使用GCD为2.45或更低的技能。"),
                KeyValuePair.Create("Add Leylines to the rotation.", "将黑魔纹加入循环。"),
                KeyValuePair.Create("Add Amplifier to the rotation.", "将详述加入循环。"),
                KeyValuePair.Create("Add Manafont to the rotation.", "将魔泉加入循环。"),
                KeyValuePair.Create("Add (High) Thunder to the rotation.", "将（高）闪雷加入循环。"),
                KeyValuePair.Create("Add Despair to the rotation.", "将绝望加入循环。"),
                KeyValuePair.Create("Add Swiftcast to the rotation.", "将Swiftcast加入循环。"),
                KeyValuePair.Create("Add Triplecast to the rotation.", "将三连咏唱加入循环。"),
                KeyValuePair.Create("Add Transpose to the rotation.", "将星灵移位加入循环。"),
                KeyValuePair.Create("Add Foul/Xenoglossy to the rotation.", "将秽浊/异言加入循环。"),
                KeyValuePair.Create("Add Foul / Xenoglossy to the rotation as movement option.", "将秽浊 / 异言作为移动选项加入循环。"),
                KeyValuePair.Create("Add Flare to the rotation.", "将核爆加入循环。"),
                KeyValuePair.Create("Add Foul to the rotation.", "将秽浊加入循环。"),
                KeyValuePair.Create("Add Foul to the rotation as movement option.", "将秽浊作为移动选项加入循环。"),
                KeyValuePair.Create("Replaces Triplecast with Savage Blade when you already have triplecast active.", "当你已经激活了三连咏唱时，将三连咏唱替换为Savage Blade。"),
                KeyValuePair.Create("Replaces Transpose with Umbral Soul when Umbral Soul is available.", "当灵极魂可用时，将星灵移位替换为灵极魂。"),
                KeyValuePair.Create("Replaces Scathe with Xenoglossy when available.", "当异言可用时，将崩溃替换为异言。"),
                KeyValuePair.Create("Replaces Aetherial Manipulation with Between the Lines when you are out of active Ley Lines and standing still.", "当你不在激活的黑魔纹范围内且站立不动时，将以太步替换为魔纹步。"),
                KeyValuePair.Create("(High) Thunder Option", "（高）闪雷"),
                KeyValuePair.Create("Flare Star Option", "耀星"),
                KeyValuePair.Create("Add Flare Star to the rotation.", "将耀星添加到循环中。"),
                KeyValuePair.Create("Foul/Xenoglossy for Movement Option", "秽浊/异言移动选项"),
                KeyValuePair.Create("(High) Thunder II Option", "（高）震雷"),
                KeyValuePair.Create("Add (High) Thunder II to the rotation.", "将（高）震雷添加到循环中。"),
                KeyValuePair.Create("Fire I/III Feature", "火炎/爆炎"),
                KeyValuePair.Create("Replaces Fire I with Fire III outside of Astral Fire or when Firestarter is up.", "不在星极火状态或触发火苗时，将火炎替换为爆炎。"),
                KeyValuePair.Create("Blizzard I/III Feature", "冰结/冰封"),
                KeyValuePair.Create("Replaces Blizzard I with Blizzard III when out of Umbral Ice.", "不在灵极冰状态时，将冰结替换为冰封。"),
                KeyValuePair.Create("Replaces Freeze with Blizzard II when synced below Lv.40.", "在同步等级低于 40 时，将玄冰替换为冰冻。"),
                KeyValuePair.Create("Fire & Ice", "火与冰"),
                KeyValuePair.Create("Replaces Fire4 with Blizzard4 when in Umbral Ice.", "在灵极冰状态下，将炽炎替换为冰澈。"),
                KeyValuePair.Create("Between the Ley Lines Feature", "魔纹之间功能"),
                KeyValuePair.Create("Replaces Ley Lines with Between the Lines when Ley Lines is active.", "当黑魔纹激活时，将黑魔纹替换为魔纹步。"),
                KeyValuePair.Create("Set the amount of time remaining on Triplecast charge before using.(Only when at threshold)", "设置在使用三重咏唱充能前的剩余时间。（仅在达到阈值时）"),
                KeyValuePair.Create("Stationary Only", "仅限静止"),
                KeyValuePair.Create("Uses Leylines only while stationary", "仅在静止时使用黑魔纹"),
                KeyValuePair.Create("Any Movement", "任意移动"),
                KeyValuePair.Create("Uses Leylines regardless of any movement conditions.", "无视任何移动条件使用黑魔纹。"),
                KeyValuePair.Create("NOTE: This could possibly get you killed", "注意：这可能会让你死亡"),
                KeyValuePair.Create("Stationary Delay Check (in seconds):", "静止延迟检查（秒）："),
                KeyValuePair.Create("Will only be used if Swiftcast is on cooldown.", "仅在即刻咏唱冷却时使用。"),
                KeyValuePair.Create("Add chosen options for movement.", "为移动选项添加指定的技能。"),
                KeyValuePair.Create("Scathe Option", "崩溃"),
                KeyValuePair.Create("Add Scathe while moving and below lvl 66.", "在移动时且等级低于66时添加崩溃。"),
                KeyValuePair.Create("Manaward Option", "魔罩"),
                KeyValuePair.Create("Adds Manaward to the rotation when below HP Treshold and when raidwide is casting.", "在血量低于阈值且敌人正在咏唱AoE技能时，将魔罩添加到循环中。"),
                KeyValuePair.Create("Addle Raidwide Option", "昏乱团减"),
                KeyValuePair.Create("Adds Addle when Raidwide is detected casting.", "检测到敌人正在咏唱AoE技能时添加昏乱到循环。"),
                KeyValuePair.Create("Adds Triplecast to the rotation.", "将三连咏唱添加到循环中。"),
                KeyValuePair.Create("Adds Paradox as a filler at max level to the rotation.", "在满级时将悖论作为填充技能添加到循环中。"),
                KeyValuePair.Create("Add Triplecast while moving.", "在移动时添加三连咏唱。"),
                KeyValuePair.Create("Blizzard IV on 2 Targets Option", "冰澈双目标"),
                KeyValuePair.Create("Substitutes Freeze for Blizzard 4 whenever it would hit 2 targets.", "当能命中2个目标时，将玄冰替换为冰澈。"),
                KeyValuePair.Create("Aetherial Manipulation Movement option", "以太步移动"),
                KeyValuePair.Create("Retargets Aetherial Manipulation to UI/Field Mouseover", "将以太步重新定位到UI/场地鼠标悬停位置"),
                KeyValuePair.Create("Replaces Fire I or Fire III with the options below.", "用下面的选项替换火炎或爆炎。"),
                KeyValuePair.Create("Replaces Fire IV with the options below.", "用下面的选项替换炽炎。"),
                KeyValuePair.Create("Replaces Flare with the options below.", "用下面的选项替换核爆。"),
                KeyValuePair.Create("Replaces Blizzard I or Blizzard III with the options below.", "用下面的选项替换冰结或冰封。"),
                KeyValuePair.Create("Blizzard IV to Despair", "冰澈转绝望"),
                KeyValuePair.Create("Replaces Blizzard IV with Despair when in Astral Fire.", "在星极火状态下，将冰澈替换为绝望。"),
                KeyValuePair.Create("Freeze feature", "玄冰"),
                KeyValuePair.Create("Replaces Freeze with Ice Paradox when you have 3 Umbral Heart stacks.", "当你有3层灵极心时，将玄冰替换为冰悖论。"),
                KeyValuePair.Create("Changes Freeze to Blizzard II when synched down.", "同步等级降低时将玄冰改为冰冻。"),
                KeyValuePair.Create("Flarestar to Paradox", "耀星转悖论"),
                KeyValuePair.Create("Replaces Flarestar with Fire Paradox when not at max Flarestar stacks.", "当未达到最大耀星层数时，将耀星替换为火悖论。"),
                KeyValuePair.Create("Amplifier to Xenoglossy", "详述转异言"),
                KeyValuePair.Create("Replaces Amplifier with Xenoglossy when at max Polyglot stacks.", "在达到最大通晓层数时，将详述替换为异言。"),
                KeyValuePair.Create("Xenoglossy to Thunder", "异言转闪雷"),
                KeyValuePair.Create("Replaces Xenoglossy with Thunder when Thunder is 3 secs or lower.", "当闪雷剩余3秒或更少时，将异言替换为闪雷。"),
                KeyValuePair.Create("Foul to Thunder II", "秽浊转震雷"),
                KeyValuePair.Create("Replaces Foul with Thunder II when Thunder is 3 secs or lower.", "当闪雷剩余3秒或更少时，将秽浊替换为震雷。"),
                KeyValuePair.Create($"Replaces {Blizzard.ActionName()} with {Blizzard3.ActionName()} when out of Umbral Ice III.", "不在灵极冰3层状态时，将冰结替换为冰封。"),
                KeyValuePair.Create($"Replaces {Blizzard3.ActionName()} with {Blizzard.ActionName()} when in Umbral Ice III.", "在灵极冰3层状态时，将冰封替换为冰结。"),
                KeyValuePair.Create("Adds Field mouseover targetting.", "添加场地鼠标悬停定位。"),
                KeyValuePair.Create("Add Field Mouseover", "添加场地鼠标悬停"),
                #endregion
                
                #region BLMPvP
                KeyValuePair.Create("Turns Fire into an all-in-one button.", "将火炎变为一个多功能按钮。"),
                KeyValuePair.Create("- Uses Blizzard spells while moving (One Button Mode only).", "- 在移动时使用冰结法术（仅限一键模式）。"),
                KeyValuePair.Create("- Will use Paradox when appropriate.", "- 在适当时机使用Paradox。"),
                KeyValuePair.Create("Uses Burst when available.", "在可用时使用Burst。"),
                KeyValuePair.Create("- Requires target to be within range.", "- 需要目标在范围内。"),
                KeyValuePair.Create("Uses Xenoglossy when available.", "在可用时使用异言。"),
                KeyValuePair.Create("Uses Lethargy when available.", "在可用时使用昏沉。"),
                KeyValuePair.Create("- Will not use against non-players.", "- 不会对非玩家使用。"),
                KeyValuePair.Create("Uses Wreath of Fire when available.", "在可用时使用烈火环。"),
                KeyValuePair.Create("- Requires player's HP to be at or above:", "- 需要玩家的生命值达到或高于："),
                KeyValuePair.Create("Elemental Weave Option", "元素天赋穿插"),
                KeyValuePair.Create("Uses Elemental Star when available.", "在可用时使用元素之星。"),
                KeyValuePair.Create("- Prioritizes Flare Star unless expiring.", "- 优先使用耀星，除非即将结束。"),
                KeyValuePair.Create("One Button Mode", "单按钮模式"),
                KeyValuePair.Create("Combines Fire & Blizzard onto one button", "将火炎与冰结技能合并到一个按钮"),
                KeyValuePair.Create("Dual Button Mode", "双按钮模式"),
                KeyValuePair.Create("Puts the combo onto separate Fire & Blizzard buttons, which will only use that element.", "将连击分配到独立的火炎与冰结按钮，各按钮仅使用对应元素技能"),
                KeyValuePair.Create("When under the effect of Astral Fire, must be moving this long before using Blizzard spells.", "处于星极火状态时，必须移动指定时长才能使用冰系法术"),
                KeyValuePair.Create("Defensive Burst", "防御性爆发"),
                KeyValuePair.Create("Also uses Burst when under 50% HP.", "50%血量以下时也会使用爆发"),
                KeyValuePair.Create("Will not use outside combat.", "非战斗状态下不使用"),
                KeyValuePair.Create("Defensive Xenoglossy", "防御性异言"),
                KeyValuePair.Create("Also uses Xenoglossy when under 50% HP.", "50%血量以下时也会使用异言"),
                KeyValuePair.Create("Defensive Lethargy", "防御性昏乱"),
                KeyValuePair.Create("Also uses Lethargy when under 50% HP.", "50%血量以下时也会使用昏乱"),
                KeyValuePair.Create("Uses only when targeted by enemy.", "仅在被敌人锁定目标时使用"),
                KeyValuePair.Create("Defensive Elemental Weave", "防御性元素天赋穿插"),
                KeyValuePair.Create("When under, uses Wreath of Ice instead.", "血量低下时改用寒冰环"),
                #endregion
            ];
        }
    }
}
