using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLUDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BLU
                KeyValuePair.Create("Turns Moon Flute into a full opener.", "将月之笛变为完整的起手技能。"),
                KeyValuePair.Create("Use the remaining 2 charges of Winged Reprobation before starting the opener again!", "在重新开始起手之前使用剩余的2次断罪飞翔！"),
                KeyValuePair.Create("Can be done with 2.50 spell speed", "可以在2.50咏唱速度下完成。"),
                KeyValuePair.Create("Changes the opener to apply either Mortal Flame or Breath of Magic instead of using Winged Reprobation.", "将起手技能改为施放必灭之炎或魔法吐息，而不是使用断罪飞翔。"),
                KeyValuePair.Create("Requires 2.20 or faster spell speed", "需要2.20或更快的咏唱速度。"),
                KeyValuePair.Create("Here for historical value; level 80 opener is more potent.", "此功能为历史遗留，80级的起手技能更为强力。"),
                KeyValuePair.Create("Turns Final Sting into the buff combo of: Moon Flute > Tingle > Whistle > Final Sting.", "将终极针变为以下增益组合：月之笛 > 哔哩哔哩 > 口笛 > 终极针。"),
                KeyValuePair.Create("Adds Rose of Destruction, Feather Rain, Glass Dance, and J Kick to the combo.", "在组合中加入斗灵弹、飞翎雨、冰雪乱舞和正义飞踢。"),
                KeyValuePair.Create("Uses Basic Instinct if you're in an instance and on your own.", "如果你在副本中且独自一人，则使用斗争本能。"),
                KeyValuePair.Create("Turns Ultravibration into Ram's Voice if Deep Freeze isn't on the target. Will swiftcast Ultravibration if available.", "如果目标没有冻结效果，则将超振动变为寒冰咆哮。如有即可咏唱可用，则即可咏唱超振动。"),
                KeyValuePair.Create("Uses Hydro Pull before using Ram's Voice.", "在使用寒冰咆哮之前使用水力吸引。"),
                KeyValuePair.Create("Turns Feather Rain into Shock Strike, Rose of Destruction, and Glass Dance.", "将飞翎雨变为轰雷、斗灵弹和冰雪乱舞。"),
                KeyValuePair.Create("Will cause primals to desync from Moon Flute burst phases if used on cooldown.", "如果在冷却时使用，会导致召唤兽与Moon Flute爆发阶段不同步。"),
                KeyValuePair.Create("Holds spells if Moon Flute burst is about to occur and spells are off cooldown.", "如果月之笛爆发即将发生且技能不在冷却中，则保留技能。"),
                KeyValuePair.Create("Adds J Kick to the combo.", "在组合中加入正义飞踢。"),
                KeyValuePair.Create("Adds Sea Shanty to the combo.", "在组合中加入咕噜咕噜。"),
                KeyValuePair.Create("Adds Winged Reprobation to the combo.", "在组合中加入断罪飞翔。"),
                KeyValuePair.Create("Adds Matra Magic to the combo.", "在组合中加入马特拉魔术。"),
                KeyValuePair.Create("Adds Surpanakha to the combo.", "在组合中加入穿甲散弹。"),
                KeyValuePair.Create("Adds Phantom Flurry to the combo.", "在组合中加入鬼宿脚。"),
                KeyValuePair.Create("Adds Nightbloom to the combo.", "在组合中加入月下彼岸花。"),
                KeyValuePair.Create("Turns Song of Torment into Bristle so Song of Torment is buffed.", "将苦闷之歌变为怒发冲冠，使苦闷之歌获得增益。"),
                KeyValuePair.Create("Turns Peripheral Synthesis into Mustard Bomb when target is under the effect of Lightheaded.", "当目标处于头晕效果下时，将生成外设变为芥末爆弹。"),
                KeyValuePair.Create("Turns Sonic Boom into Sharpened Knife when in melee range.", "当在近战范围内时，将音爆变为锋利菜刀。"),
                KeyValuePair.Create("Turns Magic Hammer into Addle when off cooldown.", "当不在冷却中时，将魔法锤变为昏乱。"),
                KeyValuePair.Create("Turns Black Knight's Tour or White Knight's Tour into its counterpart when the enemy is under the effect of the spell's debuff.", "当敌人处于技能减益效果下时，将黑骑士之旅或白骑士之旅变为其对应技能。"),
                KeyValuePair.Create("Puts Devour, Off-Guard, Lucid Dreaming, and Bad Breath into one button when under Tank Mimicry.", "在以太复制：防护状态下，将捕食、破防、醒梦和臭气合并为一个按钮。"),
                KeyValuePair.Create("Changes Deep Clean to Peat Pelt if current target is not inflicted with Begrimed.", "如果当前目标没有泥污效果，则将大扫除变为玩泥球。"),
                KeyValuePair.Create("Turns Perpetual Ray into Sharpened Knife when target is stunned and in melee range.", "当目标处于眩晕状态且在近战范围内时，将永恒射线替换为锋利菜刀"),
                KeyValuePair.Create("Perpetual Ray into Sharpened Knife", "永恒射线转为锋利菜刀"),
                KeyValuePair.Create("Peripheral Synthesis into Mustard Bomb", "生成外设转为芥末爆弹"),
                KeyValuePair.Create("Buffed Song of Torment", "强化苦闷之歌"),
                KeyValuePair.Create("Primal Feature", "蛮神特性"),
                KeyValuePair.Create("Hydro Pull Setup", "水力吸引前置"),
                KeyValuePair.Create("Vibe Combo", "超振动连击"),
                KeyValuePair.Create("Solo Mode", "单人模式"),
                KeyValuePair.Create("Off-cooldown Primal Additions", "冷却结束的蛮神技能补充"),
                KeyValuePair.Create("Peat Clean", "玩泥球扫除"),
                #endregion
            ];
        }
    }
}
