using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BLUDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BLU
                KeyValuePair.Create("Turns Moon Flute into a full opener.", "将Moon Flute变为完整的起手技能。"),
                KeyValuePair.Create("Use the remaining 2 charges of Winged Reprobation before starting the opener again!", "在重新开始起手之前使用剩余的2次Winged Reprobation！"),
                KeyValuePair.Create("Can be done with 2.50 spell speed", "可以在2.50咏唱速度下完成。"),
                KeyValuePair.Create("Changes the opener to apply either Mortal Flame or Breath of Magic instead of using Winged Reprobation.", "将起手技能改为施放Mortal Flame或Breath of Magic，而不是使用Winged Reprobation。"),
                KeyValuePair.Create("Requires 2.20 or faster spell speed", "需要2.20或更快的咏唱速度。"),
                KeyValuePair.Create("Here for historical value; level 80 opener is more potent.", "此功能为历史遗留，80级的起手技能更为强力。"),
                KeyValuePair.Create("Turns Final Sting into the buff combo of: Moon Flute > Tingle > Whistle > Final Sting.", "将Final Sting变为以下增益组合：Moon Flute > Tingle > Whistle > Final Sting。"),
                KeyValuePair.Create("Adds Rose of Destruction, Feather Rain, Glass Dance, and J Kick to the combo.", "在组合中加入Rose of Destruction、Feather Rain、Glass Dance和J Kick。"),
                KeyValuePair.Create("Uses Basic Instinct if you're in an instance and on your own.", "如果你在副本中且独自一人，则使用Basic Instinct。"),
                KeyValuePair.Create("Turns Ultravibration into Ram's Voice if Deep Freeze isn't on the target. Will swiftcast Ultravibration if available.", "如果目标没有状态冻结效果，则将Ultravibration变为Ram's Voice。如果有Swiftcast可用，则使用Swiftcast Ultravibration。"),
                KeyValuePair.Create("Uses Hydro Pull before using Ram's Voice.", "在使用Ram's Voice之前使用Hydro Pull。"),
                KeyValuePair.Create("Turns Feather Rain into Shock Strike, Rose of Destruction, and Glass Dance.", "将Feather Rain变为Shock Strike、Rose of Destruction和Glass Dance。"),
                KeyValuePair.Create("Will cause primals to desync from Moon Flute burst phases if used on cooldown.", "如果在冷却时使用，会导致召唤兽与Moon Flute爆发阶段不同步。"),
                KeyValuePair.Create("Holds spells if Moon Flute burst is about to occur and spells are off cooldown.", "如果Moon Flute爆发即将发生且技能不在冷却中，则保留技能。"),
                KeyValuePair.Create("Adds J Kick to the combo.", "在组合中加入J Kick。"),
                KeyValuePair.Create("Adds Sea Shanty to the combo.", "在组合中加入Sea Shanty。"),
                KeyValuePair.Create("Adds Winged Reprobation to the combo.", "在组合中加入Winged Reprobation。"),
                KeyValuePair.Create("Adds Matra Magic to the combo.", "在组合中加入Matra Magic。"),
                KeyValuePair.Create("Adds Surpanakha to the combo.", "在组合中加入Surpanakha。"),
                KeyValuePair.Create("Adds Phantom Flurry to the combo.", "在组合中加入Phantom Flurry。"),
                KeyValuePair.Create("Adds Nightbloom to the combo.", "在组合中加入Nightbloom。"),
                KeyValuePair.Create("Turns Song of Torment into Bristle so Song of Torment is buffed.", "将Song of Torment变为Bristle，以便Song of Torment获得增益。"),
                KeyValuePair.Create("Turns Peripheral Synthesis into Mustard Bomb when target is under the effect of Lightheaded.", "当目标处于Lightheaded效果下时，将Peripheral Synthesis变为Mustard Bomb。"),
                KeyValuePair.Create("Turns Sonic Boom into Sharpened Knife when in melee range.", "当在近战范围内时，将Sonic Boom变为Sharpened Knife。"),
                KeyValuePair.Create("Turns Magic Hammer into Addle when off cooldown.", "当不在冷却中时，将Magic Hammer变为Addle。"),
                KeyValuePair.Create("Turns Black Knight's Tour or White Knight's Tour into its counterpart when the enemy is under the effect of the spell's debuff.", "当敌人处于技能减益效果下时，将Black Knight's Tour或White Knight's Tour变为其对应技能。"),
                KeyValuePair.Create("Puts Devour, Off-Guard, Lucid Dreaming, and Bad Breath into one button when under Tank Mimicry.", "在以太复制：防护职业状态下，将Devour、破防、Lucid Dreaming和Bad Breath合并为一个按钮。"),
                KeyValuePair.Create("Changes Deep Clean to Peat Pelt if current target is not inflicted with Begrimed.", "如果当前目标没有Begrimed效果，则将Deep Clean变为Peat Pelt。"),
                KeyValuePair.Create("Turns Perpetual Ray into Sharpened Knife when target is stunned and in melee range.", "当目标处于眩晕状态且在近战范围内时，将PerpetualRay替换为SharpenedKnife"),
                KeyValuePair.Create("Perpetual Ray into Sharpened Knife", "Perpetual Ray转为Sharpened Knife"),
                KeyValuePair.Create("Peripheral Synthesis into Mustard Bomb", "Peripheral Synthesis转为Mustard Bomb"),
                KeyValuePair.Create("Buffed Song of Torment", "强化Song of Torment"),
                KeyValuePair.Create("Primal Feature", "蛮神特性"),
                KeyValuePair.Create("Hydro Pull Setup", "水力吸引"),
                KeyValuePair.Create("Vibe Combo", "振动连击"),
                KeyValuePair.Create("Solo Mode", "单人模式"),
                KeyValuePair.Create("Off-cooldown Primal Additions", "补充已冷却的蛮神技能"),
                KeyValuePair.Create("Peat Clean", "泥球扫除"),
                #endregion
            ];
        }
    }
}
