using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class BRDDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region BRDPvE
                KeyValuePair.Create("Replaces Heavy Shot with a full one-button single target rotation.", "用一键单目标循环替换强力射击。"),
                KeyValuePair.Create("Replaces Quick Nock with a full one-button AoE rotation.", "用一键AoE循环替换连珠箭。"),
                KeyValuePair.Create("This option will make Bard apply DoTs if none are present on the target.", "此选项将使吟游诗人在目标没有DoT时施加DoT。"),
                KeyValuePair.Create("Enable the snapshotting of DoTs, within the remaining time of Raging Strikes below:", "在猛者强击剩余时间内启用DoT快照："),
                KeyValuePair.Create("This option adds the Bard's Songs to the Advanced Bard Feature.", "此选项将吟游诗人的歌曲添加到高级吟游诗人功能中。"),
                KeyValuePair.Create("Adds buffs onto the Advanced Bard feature.", "将增益效果添加到高级吟游诗人功能中。"),
                KeyValuePair.Create("Adds Resonant Arrow to the Rotation after Barrage.", "在纷乱箭后添加共鸣箭到循环中。"),
                KeyValuePair.Create("Adds Radiant Encore to the Rotation after Finale.", "在光明神的最终乐章后添加光明神的返场余音到循环中。"),
                KeyValuePair.Create("Adds Apex Arrow and Blast shot", "添加绝峰箭与爆破箭。"),
                KeyValuePair.Create("Weave Sidewinder, Empyreal arrow, Rain of death, and Pitch perfect when available.", "在可用时插入侧风诱导箭、九天连箭、死亡箭雨和完美音调。"),
                KeyValuePair.Create("84+ Pools Bloodletter charges to allow for optimum burst phases.", "84+时储存失血箭充能以优化爆发阶段。"),
                KeyValuePair.Create("Uses interrupt during the rotation if applicable.", "在循环中使用打断技能（如果适用）。"),
                KeyValuePair.Create("Adds enemy health checking on mobs for buffs, DoTs and Songs.", "添加对怪物生命值的检查以应用增益、DoT和歌曲。"),
                KeyValuePair.Create("They will not be reapplied if less than specified.", "如果低于指定值，则不会重新应用。"),
                KeyValuePair.Create("Uses Second Wind when below set HP percentage.", "当HP低于设定百分比时使用内丹。"),
                KeyValuePair.Create("Uses Wardens Paeon when you have a cleansable debuff.", "当你有可清除的减益时使用光阴神的礼赞凯歌。"),
                KeyValuePair.Create("Weave Songs on the Advanced AoE.", "在高级AoE中插入歌曲。"),
                KeyValuePair.Create("Adds buffs onto the Advance AoE Bard feature.", "将增益效果添加到高级AoE吟游诗人功能中。"),
                KeyValuePair.Create("84+ Pools Rain of death charges to allow for optimum burst phases.", "84+时储存Rain of Death充能以优化爆发阶段。"),
                KeyValuePair.Create("Adds enemy health checking on targetted mob for songs.", "添加对目标怪物生命值的检查以应用歌曲。"),
                KeyValuePair.Create("Replaces Heavy Shot/Burst Shot with Straight Shot/Refulgent Arrow when procced.", "在触发时用直线射击/辉煌箭替换强力射击/爆发射击。"),
                KeyValuePair.Create("Enabling this option will make Heavy Shot into Straight Shot refresh your DoTs on your current.", "启用此选项将使强力射击变为直线射击时刷新当前目标的DoT。"),
                KeyValuePair.Create("Replaces Burst Shot with Apex Arrow when gauge is full and Blast Arrow when you are Blast Arrow ready.", "当量谱满时用绝峰箭替换爆发射击，当爆破箭准备就绪时用爆破箭替换。"),
                KeyValuePair.Create("Iron Jaws is replaced with Caustic Bite/Stormbite if one or both are not up.", "如果烈毒咬箭/狂风蚀箭未生效，则用它们替换伶牙俐齿。"),
                KeyValuePair.Create("Alternates between the two if Iron Jaws isn't available.", "如果Iron Jaws不可用，则在两者之间交替使用。"),
                KeyValuePair.Create("Adds Apex and Blast Arrow to Iron Jaws when available.", "在可用时将绝峰箭与爆破箭添加到伶牙俐齿中。"),
                KeyValuePair.Create("Iron Jaws will only show up when debuffs are about to expire.", "伶牙俐齿只会在减益即将结束时显示。"),
                KeyValuePair.Create("Replaces Quick Nock/Ladonsbite with Shadowbite when ready.", "在准备就绪时用影噬箭替换连珠箭/百首龙牙箭。"),
                KeyValuePair.Create("Replaces Ladonsbite and Quick Nock with Apex Arrow when gauge is full and Blast Arrow when you are Blast Arrow ready.", "当量谱满时用绝峰箭替换百首龙牙箭与连珠箭，当爆破箭准备就绪时用爆破箭替换。"),
                KeyValuePair.Create("All oGCD's on Bloodletter/Heartbreakshot", "所有能力技添加在失血箭/碎心箭上。"),
                KeyValuePair.Create("Adds the songs to the oGCD feature. Wanderers > Mages > Armys", "将歌曲添加到能力技功能中。放浪神 > 贤者 > 军神。"),
                KeyValuePair.Create("All AoE oGCD's on Rain of Death depending on their CD.", "所有AoE能力技根据冷却时间添加在Rain of Death上。"),
                KeyValuePair.Create("Adds the songs to the AoE oGCD feature. Wanderers > Mages > Armys", "将歌曲添加到AoE能力技功能中。放浪神 > 贤者 > 军神。"),
                KeyValuePair.Create("Adds Raging Strikes and Battle Voice onto Barrage.", "将猛者强击和战斗之声添加到纷乱箭上。"),
                KeyValuePair.Create("Add Mage's Ballad and Army's Paeon to Wanderer's Minuet depending on cooldowns.", "根据冷却时间将贤者的叙事谣和军神的赞美歌添加到放浪神的小步舞曲中。"),
                KeyValuePair.Create("Adds Silent Nocturne to Burst Mode.", "将默者的夜曲添加到爆发模式中。"),
                KeyValuePair.Create("Adds Apex Arrow to Burst Mode.", "将绝峰箭添加到爆发模式中。"),
                KeyValuePair.Create("Adds Blast Arrow to Burst Mode.", "将爆破箭添加到爆发模式中。"),
                KeyValuePair.Create("Adds Harmonic Arrow to Burst Mode. Will use it at set number of charges AND when target is below the health threshold per charge for execute. ", "将和弦箭添加到爆发模式中。将在设定充能数时使用，并且当目标生命值低于每充能的执行阈值时使用。"),
                KeyValuePair.Create("Adds Encore of Light to Burst Mode.", "将英雄的返场余音添加到爆发模式中。"),
                KeyValuePair.Create("Auto Self cleanse of soft cc. ", "自动清除软控制效果。"),
                KeyValuePair.Create(" Half Asleep, Heavy, and Bind", "催眠、加重和止步。"),
                KeyValuePair.Create("Bard DoTs Option", "诗人DoT选项"),
                KeyValuePair.Create("Raging Jaws Option", "伶牙俐齿选项"),
                KeyValuePair.Create("Bard Songs Option", "诗人歌曲选项"),
                KeyValuePair.Create("Bard Song Option", "诗人歌曲选项"),
                KeyValuePair.Create("Resonant Option", "共鸣箭"),
                KeyValuePair.Create("Encore Option", "光明神的返场余音"),
                KeyValuePair.Create("oGcd Option", "能力技选项"),
                KeyValuePair.Create("No Waste Option", "防止浪费选项"),
                KeyValuePair.Create("Self Cleanse Option", "自我净化"),
                KeyValuePair.Create("AoE No Waste Option", "AoE防止浪费选项"),
                KeyValuePair.Create("Heavy Shot into Straight Shot Feature", "强力射击 -> 直线射击"),
                KeyValuePair.Create("Iron Jaws Alternate Feature", "伶牙俐齿替代"),
                KeyValuePair.Create("Quick song option", "快速唱歌"),
                KeyValuePair.Create("Bard Buffs Feature", "诗人Buff"),
                KeyValuePair.Create("One Button Songs Feature", "一键唱歌"),
                KeyValuePair.Create("2.48 Adjusted Standard Opener", "2.48调整标准起手"),
                KeyValuePair.Create("2.49 Standard Comfy", "2.49标准舒适起手"),
                KeyValuePair.Create("Remaining time (In seconds). Recommended 5, increase little by little if refresh is outside of radiant window", "剩余时间（秒）。推荐5，如果刷新在光明神窗口期外，请逐步增加数值。"),
                KeyValuePair.Create("Remaining target HP percentage", "目标剩余生命值百分比"),
                #endregion

                #region BRDPvP
                KeyValuePair.Create("Turns Powerful Shot into an all-in-one damage button.", "将强劲射击变为一个全能伤害技能按钮。"),
                KeyValuePair.Create("How many Charges to use it at", "使用多少充能次数"),
                KeyValuePair.Create("1 charge 8000 damage", "1次充能: 8000伤害"),
                KeyValuePair.Create("2 charge 12000 damage", "2次充能: 12000伤害"),
                KeyValuePair.Create("3 charge 15000 damage", "3次充能: 15000伤害"),
                KeyValuePair.Create("4 charge 17000 damage", "4次充能: 17000伤害")
                #endregion
            ];
        }
    }
}
