using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DOLDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region DOL
                KeyValuePair.Create("Replaces Ageless Words and Solid Reason with Wise to the World when available", "当可用时，用Wise to the World替换Ageless Words和Solid Reason。"),
                KeyValuePair.Create("Replaces Lay of the Lands or Arbor Calls with Prospect/Triangulate and Truth of Mountains/Forests if not active.", "如果未激活，用Prospect/Triangulate和Truth of Mountains/Truth of Forests替换Lay of the Land或Arbor Call。"),
                KeyValuePair.Create("Replaces Cast with Hook when fishing", "钓鱼时，用Hook替换Cast。"),
                KeyValuePair.Create("Replace fishing abilities with diving abilities when underwater", "水下时，用潜水技能替换钓鱼技能。"),
                KeyValuePair.Create("Replaces Cast with Gig when diving.", "潜水时，用Gig替换Cast。"),
                KeyValuePair.Create("Replaces Surface Slap with Veteran Trade when diving.", "潜水时，用Veteran Trade替换Surface Slap。"),
                KeyValuePair.Create("Replaces Prize Catch with Nature's Bounty when diving.", "潜水时，用Nature's Bounty替换Prize Catch。"),
                KeyValuePair.Create("Replaces Snagging with Salvage when diving.", "潜水时，用Salvage替换Snagging。"),
                KeyValuePair.Create("Replaces Cast Light with Electric Current when diving.", "潜水时，用Electric Current替换Cast Light。"),
                KeyValuePair.Create("Replaces Mooch with Shark Eye when diving.", "潜水时，用Shark Eye替换Mooch。"),
                KeyValuePair.Create("Replaces Fish Eyes with Vital Sight when diving.", "潜水时，用Vital Sight替换Fish Eyes。"),
                KeyValuePair.Create("Replaces Chum with Baited Breath when diving.", "潜水时，用Baited Breath替换Chum。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Locate & Truth Feature", "探查特性"),
            ];
        }
    }
}
