using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DRGDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region DRG
                KeyValuePair.Create("Replaces True Thrust with a full one-button single target rotation.", "用一键单体循环替换True Thrust。"),
                KeyValuePair.Create("Replaces Doom Spike with a full one-button AoE rotation.", "用一键AOE循环替换Doom Spike。"),
                KeyValuePair.Create("Adds various buffs to the rotation.", "在循环中添加各种增益效果。"),
                KeyValuePair.Create("Adds Battle Litany to the rotation.", "在循环中添加Battle Litany。"),
                KeyValuePair.Create("Adds Lance Charge to the rotation.", "在循环中添加Lance Charge。"),
                KeyValuePair.Create("Adds various cooldowns to the rotation.", "在循环中添加各种冷却技能。"),
                KeyValuePair.Create("Adds Life Surge, on the proper GCD, to the rotation.", "在正确的GCD上添加Life Surge到循环中。"),
                KeyValuePair.Create("Adds Mirage Dive to the rotation.", "在循环中添加Mirage Dive。"),
                KeyValuePair.Create("Adds Dragonfire Dive to the rotation.", "在循环中添加Dragonfire Dive。"),
                KeyValuePair.Create("Adds Dragonfire Dive to the rotation when in the target ring (1 yalm) & when not moving.", "当在目标圈内（1米）且不移动时，在循环中添加Dragonfire Dive。"),
                KeyValuePair.Create("Adds Geirskogul to the rotation.", "在循环中添加Geirskogul。"),
                KeyValuePair.Create("Adds Nastrond to the rotation.", "在循环中添加Nastrond。"),
                KeyValuePair.Create("Adds Stardiver to the rotation.", "在循环中添加Stardiver。"),
                KeyValuePair.Create("Adds Stardiver to the rotation when in the target ring (1 yalm) & when not moving.", "当在目标圈内（1米）且不移动时，在循环中添加Stardiver。"),
                KeyValuePair.Create("Adds Wyrmwind Thrust to the rotation.", "在循环中添加Wyrmwind Thrust。"),
                KeyValuePair.Create("Adds Rise of the Dragon to the rotation.", "在循环中添加Rise of the Dragon。"),
                KeyValuePair.Create("Adds Starcross to the rotation.", "在循环中添加Starcross。"),
                KeyValuePair.Create("Adds True North before Chaos Thrust/Chaotic Spring, Fang And Claw and Wheeling Thrust when you are not in the correct position for the enhanced potency bonus.", "当你不处于正确位置以获得增强威力加成时，在Chaos Thrust/Chaotic Spring、Fang And Claw和Wheeling Thrust之前添加True North。"),
                KeyValuePair.Create("Adds Piercing Talon to the rotation when you are out of melee range.", "当你超出近战范围时，在循环中添加Piercing Talon。"),
                KeyValuePair.Create("Replaces Doomspike with a full one-button AoE rotation.", "用一键AOE循环替换Doomspike。"),
                KeyValuePair.Create("Adds Lance Charge and Battle Litany to the rotation.", "在循环中添加Lance Charge和Battle Litany。"),
                KeyValuePair.Create("Adds Life Surge, onto proper GCDs, to the rotation.", "在正确的GCD上添加Life Surge到循环中。"),
                KeyValuePair.Create("Adds Disembowel combo to the rotation when you are or synced below level 62.", "当你在62级以下或同步到62级以下时，在循环中添加Disembowel连击。"),
                KeyValuePair.Create("Standard opener", "标准起手"),
                KeyValuePair.Create("Uses Standard opener", "使用标准起手"),
                KeyValuePair.Create("Piercing Talon opener", "穿刺之爪起手"),
                KeyValuePair.Create("Uses Piercing Talon opener", "使用穿刺之爪起手"),
                KeyValuePair.Create("High Jump Option", "高跳选项"),
                KeyValuePair.Create("Adds (High) Jump to the rotation.", "将高跳添加到循环中。"),
                KeyValuePair.Create("(High) Jump Melee option", "高跳近战选项"),
                KeyValuePair.Create("Adds (High) Jump to the rotation when in the target ring (1 yalm) & when not moving.", "当在目标圈内（1 米）且不移动时，将高跳添加到循环中。"),
                KeyValuePair.Create("Second Wind HP percentage threshold (0 = Disabled)", "内丹生命百分比阈值（0 = 禁用）"),
                KeyValuePair.Create("Bloodbath HP percentage threshold (0 = Disabled)", "浴血生命百分比阈值（0 = 禁用）"),
                KeyValuePair.Create("HP% to be at or under", "生命值百分比达到或低于"),
                KeyValuePair.Create("Wyrmwind Option", "天龙点睛"),
                KeyValuePair.Create("Replace Full Thrust/Heavens' Thrust with its combo chain.", "用其连击链替换Full Thrust/Heavens' Thrust。"),
                KeyValuePair.Create("Replace Chaos Thrust /Chaotic Spring with its combo chain.", "用其连击链替换Chaos Thrust /Chaotic Spring。"),
                KeyValuePair.Create("Turns Lance Charge into Battle Litany when the former is on cooldown.", "当Lance Charge冷却时，将其转换为Battle Litany。"),
                KeyValuePair.Create("Turns Drakesbane Combo into an all-in-one damage button.", "将Drakesbane连击转换为一个全能伤害按钮。"),
                KeyValuePair.Create("Adds Geirskogul to Burst Mode.", "在Burst Mode中添加Geirskogul。"),
                KeyValuePair.Create("Adds Nastrond to Burst Mode.", "在Burst Mode中添加Nastrond。"),
                KeyValuePair.Create("Adds Horrid Roar to Burst Mode.", "在Burst Mode中添加Horrid Roar。"),
                KeyValuePair.Create("Sustain Chaos Spring Option", "樱花缭乱维持"),
                KeyValuePair.Create("Execute Chaos Spring Option", "樱花缭乱处决"),
                KeyValuePair.Create("Adds Chaos Spring to Burst Mode when below the set HP percentage.", "当HP低于设定百分比时，在Burst Mode中添加樱花缭乱。"),
                KeyValuePair.Create("Adds Chaos Spring to Burst Mode when target is below 8k health because it goes through guard.", "当目标血量低于8000时，在Burst Mode中添加樱花缭乱，因为它可以穿透防御。"),
                KeyValuePair.Create("Adds Wyrmwind Thrust to Burst Mode.", "在Burst Mode中添加Wyrmwind Thrust。"),
                KeyValuePair.Create("High Jump Weave Option", "高跳穿插"),
                KeyValuePair.Create("Adds High Jump to Burst Mode.", "在Burst Mode中添加高跳。"),
                KeyValuePair.Create("Using Elusive Jump turns Drakesbane Combo into all-in-one burst damage button once all cooldowns are ready. ", "当所有冷却技能准备就绪时，使用Elusive Jump将Drakesbane连击转换为全能爆发伤害按钮。"),
                KeyValuePair.Create(" Disables Elusive Jump if Burst is not ready.", "如果Burst未准备就绪，则禁用Elusive Jump。"),
                KeyValuePair.Create("Stop Using When Target HP% is at or Below (Set to 0 to Disable This Check)", "当目标生命值百分比达到或低于此值时停止使用（设置为0以禁用此检查）"),
                #endregion
            ];
        }
    }
}
