using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class DRKDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region DRK
                KeyValuePair.Create("Replaces Hard Slash with a full one-button single target rotation.", "用一键完整单体循环替换Hard Slash。"),
                KeyValuePair.Create("Replaces Unleash with a full one-button AoE rotation.", "用一键完整AOE循环替换Unleash。"),
                KeyValuePair.Create("Tries to prevent any triple-weaving (even when it may not clip).", "尽量避免三插（即使可能不会卡GCD）。"),
                KeyValuePair.Create("Adds Unmend to the rotation when you are out of range.", "当你超出近战范围时，将Unmend加入循环。"),
                KeyValuePair.Create("Collection of cooldowns to add to the rotation.", "将冷却技能集合加入循环。"),
                KeyValuePair.Create("Adds Delirium (or Blood Weapon at lower levels) to the rotation on cooldown and when Darkside is up.", "当Darkside激活且冷却完毕时，将Delirium（或低等级时的Blood Weapon）加入循环。"),
                KeyValuePair.Create(" Will also spend 50 blood gauge if Delirium is nearly ready to protect from overcap.", "如果Delirium即将准备就绪，还会消耗50点血槽以防止溢出。"),
                KeyValuePair.Create("Adds Living Shadow to the rotation when Darkside is up.", "当Darkside激活时，将Living Shadow加入循环。"),
                KeyValuePair.Create("Adds Disesteem to the rotation when available.", "当可用时，将Disesteem加入循环。"),
                KeyValuePair.Create("Adds Shadowbringer to the rotation while Darkside is up. Will use all stacks on cooldown.", "当Darkside激活时，将Shadowbringer加入循环。冷却完毕时将使用所有层数。"),
                KeyValuePair.Create("Pools Shadowbringer to use during even minute window bursts (after Disesteem).", "在偶数分钟的爆发窗口（Disesteem之后）集中使用Shadowbringer。"),
                KeyValuePair.Create("Adds Salted Earth to the rotation while Darkside is up, will use Salt and Darkness if unlocked.", "当Darkside激活时，将Salted Earth加入循环，如果解锁了Salt and Darkness也会使用。"),
                KeyValuePair.Create("Adds Salt and Darkness to the rotation in the latter half of its duration.", "在Salted Earth持续时间后半段将Salt and Darkness加入循环。"),
                KeyValuePair.Create("Adds Carve and Spit to the rotation while Darkside is up.", "当Darkside激活时，将Carve and Spit加入循环。"),
                KeyValuePair.Create("Collection of spenders (mana and blood) to add to the rotation.", "将消耗资源（魔力和血槽）的技能集合加入循环。"),
                KeyValuePair.Create("Adds the Scarlet Delirium combo chain to the rotation when Delirium is activated.", "当Delirium激活时，将Scarlet Delirium连击链加入循环。"),
                KeyValuePair.Create("Adds Bloodspiller to the rotation when Delirium is active or well outside of burst.", "当Delirium激活或远离爆发期时，将Bloodspiller加入循环。"),
                KeyValuePair.Create("Adds Bloodspiller to the rotation after Syphon Strike when the blood gauge is above the chosen threshold.", "当血槽超过设定阈值时，在Syphon Strike后将Bloodspiller加入循环。"),
                KeyValuePair.Create("Uses Edge of Darkness in burst windows, and outside of that will spend to chosen MP limit.", "在爆发窗口使用Edge of Darkness，其他时候会消耗到设定的MP上限。"),
                KeyValuePair.Create("Will spend Dark Arts if your own The Blackest Night shield is active on you.", "如果你自身的The Blackest Night护盾激活，会消耗Dark Arts。"),
                KeyValuePair.Create("Uses Edge of Darkness if Darkside is about to expire (<10s).", "如果Darkside即将结束（<10秒），使用Edge of Darkness。"),
                KeyValuePair.Create("Uses Edge of Darkness if you are above 8,500 mana.", "如果你的魔力超过8,500，使用Edge of Darkness。"),
                KeyValuePair.Create("Collection of Mitigations to add to the rotation.", "将减伤技能集合加入循环。"),
                KeyValuePair.Create("Uses Oblation based on Health Remaining.", "根据剩余生命值使用Oblation。"),
                KeyValuePair.Create("Uses Reprisal when a raidwide is in the process of casting.", "当团队范围技能正在施放时，使用Reprisal。"),
                KeyValuePair.Create("Uses Dark Missionary when a raidwide is in the process of casting.", "当团队范围技能正在施放时，使用Dark Missionary。"),
                KeyValuePair.Create("Won't use Dark Missionary if your own Reprisal is on the target.", "如果你自身的Reprisal已在目标上，不会使用Dark Missionary。"),
                KeyValuePair.Create("Uses Shadowed Vigil based on Health Remaining.", "根据剩余生命值使用Shadowed Vigil。"),
                KeyValuePair.Create("Uses Living Dead based on Health Remaining.", "根据剩余生命值使用Living Dead。"),
                KeyValuePair.Create("Uses The Blackest Night based on Health Remaining.", "根据剩余生命值使用Blackest Night。"),
                KeyValuePair.Create("(Note: makes no attempt to ensure shield will break)", "（注意：不保证护盾会被打破）"),
                KeyValuePair.Create("Adds Low Blow to the rotation when your target's cast is interruptible.", "当目标施法可打断时，将Low Blow加入循环。"),
                KeyValuePair.Create("Adds Living Shadow to the rotation on cooldown and when Darkside is up.", "当Darkside激活且冷却完毕时，将Living Shadow加入循环。"),
                KeyValuePair.Create("Adds Shadowbringer to the rotation.", "将Shadowbringer加入循环。"),
                KeyValuePair.Create("Adds Salted Earth and Salt and Darkness to the rotation on cooldown and when Darkside is up.", "当Darkside激活且冷却完毕时，将Salted Earth和Salt and Darkness加入循环。"),
                KeyValuePair.Create("Requires to be at a stand-still and for combat to have been going on for >7 seconds to use Salted Earth, to try to make it be placed after you finish your pull.", "需要站立不动且战斗持续超过7秒才能使用Salted Earth，以确保在拉怪结束后放置。"),
                KeyValuePair.Create("Adds Abyssal Drain to the rotation when you fall below the chosen HP.", "当生命值低于设定阈值时，将Abyssal Drain加入循环。"),
                KeyValuePair.Create("Adds Impalement to the rotation when Delirium is active.", "当Delirium激活时，将Impalement加入循环。"),
                KeyValuePair.Create("Adds Quietus to the rotation when Delirium is active or well outside of burst.", "当Delirium激活或远离爆发期时，将Quietus加入循环。"),
                KeyValuePair.Create("Adds Quietus to the rotation when the blood gauge is above the chosen threshold.", "当血槽超过设定阈值时，将Quietus加入循环。"),
                KeyValuePair.Create("Uses Flood of Shadow in burst, if Darkside is about to expire (<10s), if you have Dark Arts and use The Blackest Night, and outside of burst will spend to chosen MP limit.", "在爆发期使用Flood of Shadow，如果Darkside即将结束（<10秒），如果你有Dark Arts并使用The Blackest Night，以及在爆发期外会消耗到设定的MP上限。"),
                KeyValuePair.Create("Uses Flood of Shadow if you are above 8,500 mana.", "如果你的魔力超过8,500，使用Flood of Shadow。"),
                KeyValuePair.Create("Adds The Blackest Night to the rotation.", "将The Blackest Night加入循环。"),
                KeyValuePair.Create("Adds Reprisal to the rotation.", "将Reprisal加入循环。"),
                KeyValuePair.Create("Adds Rampart to the rotation.", "将Rampart加入循环。"),
                KeyValuePair.Create("Adds Arm's Length to the rotation.", "将Arm's Length加入循环。"),
                KeyValuePair.Create("Uses Living Dead based on your and your enemy's Remaining Health.", "根据你和敌人的剩余生命值使用Living Dead。"),
                KeyValuePair.Create("Replaces Dark Mind with an all-in-one mitigation button.", "用一键减伤按钮替换Dark Mind。"),
                KeyValuePair.Create("Gives max priority to Living Dead when the Health percentage threshold is met.", "当生命值百分比达到阈值时，优先使用Living Dead。"),
                KeyValuePair.Create("Adds The Blackest Night to the one-button mitigation.", "将The Blackest Night加入一键减伤。"),
                KeyValuePair.Create("Adds Oblation to the one-button mitigation.", "将Oblation加入一键减伤。"),
                KeyValuePair.Create("Adds Dark Missionary to the one-button mitigation.", "将Dark Missionary加入一键减伤。"),
                KeyValuePair.Create("Adds Shadow Wall / Vigil to the one-button mitigation.", "将Shadow Wall / Vigil加入一键减伤。"),
                KeyValuePair.Create("Adds selected oGCD abilities to Carve And Spit and Abyssal Drain.", "将选中的oGCD技能加入Carve and Spit和Abyssal Drain。"),
                KeyValuePair.Create("Adds Interject to the feature when your target's cast is interruptible.", "当目标施法可打断时，将Interject加入功能。"),
                KeyValuePair.Create("Adds Delirium (or Blood Weapon) to the Feature.", "将Delirium（或Blood Weapon）加入功能。"),
                KeyValuePair.Create("Adds Living Shadow to the Feature.", "将Living Shadow加入功能。"),
                KeyValuePair.Create("Adds Disesteem to the Feature.", "将Disesteem加入功能。"),
                KeyValuePair.Create("Adds Salted Earth to the Feature.", "将Salted Earth加入功能。"),
                KeyValuePair.Create("Adds Saltand Darkness to the Feature when under the effect of Salted Earth.", "当处于Salted Earth效果下时，将Salt and Darkness加入功能。"),
                KeyValuePair.Create("Adds Shadowbringer to the Feature.", "将Shadowbringer加入功能。"),
                KeyValuePair.Create("Use Variant Spirit Dart whenever the debuff is not present or less than 3s.", "当debuff不存在或少于3秒时，使用Variant Spirit Dart。"),
                KeyValuePair.Create("Use Variant Cure when HP is below set threshold.", "当生命值低于设定阈值时，使用Variant Cure。"),
                KeyValuePair.Create("Use Variant Ultimatum on cooldown.", "冷却完毕时使用Variant Ultimatum。"),
                KeyValuePair.Create("Turns Souleater Combo into an all-in-one damage button.", "将Souleater连击变为一键伤害按钮。"),
                KeyValuePair.Create("Adds Plunge to Burst Mode.", "将Plunge加入爆发模式。"),
                KeyValuePair.Create("Uses Plunge whilst in melee range, and not just as a gap-closer.", "在近战范围内使用Plunge，而不仅仅是作为接近技能。"),
                KeyValuePair.Create("Adds Salted Earth to Burst mode.", "将Salted Earth加入爆发模式。"),
                KeyValuePair.Create("Adds Salt and Darkness to Burst mode.", "将Salt and Darkness加入爆发模式。"),
                KeyValuePair.Create("Adds Impalement to Burst mode.", "将Impalement加入爆发模式。"),
                KeyValuePair.Create("Adds Shadowbringer to Burst mode.", "将Shadowbringer加入爆发模式。"),
                KeyValuePair.Create("Adds Blackest Night to Burst mode.", "将The Blackest Night加入爆发模式。"),
                KeyValuePair.Create("Adds Scorn to Burst mode.", "将Scorn加入爆发模式。"),
                KeyValuePair.Create("Over 7,000 mana", "超过7000魔力值"),
                KeyValuePair.Create("# to use at or above", "达到或高于这个值时使用"),
                KeyValuePair.Create("Mana to save for TBN", "为暗黑布道保留的魔力值"),
                KeyValuePair.Create("Avoid Doubling up on Group Mit", "避免重复使用团队减伤技能"),
                KeyValuePair.Create("Salt After Pull Option", "拉怪后使用Salted Earth"),
                KeyValuePair.Create("HP% to be at or Above to use ", "生命值达到或超过这个百分比时使用"),
                #endregion
            ];
        }
    }
}
