using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class Genesis
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region ADV
                KeyValuePair.Create("Island Sanctuary Sprint Feature", "无名岛冲刺特性"),
                KeyValuePair.Create("Replaces Sprint with Isle Sprint.", "用海岛冲刺替换冲刺。"),
                KeyValuePair.Create("Only works at the Island Sanctuary. Icon does not change.", "仅在无名岛有效。图标不会改变。"),
                KeyValuePair.Create("Do not use with SimpleTweaks' Island Sanctuary Sprint fix.", "不要与SimpleTweaks的海岛冲刺替换功能一起使用。"),
                KeyValuePair.Create("Features and options involving shared role actions for Tanks.", "涉及防护职业共享职能技能的功能和选项。"),
                KeyValuePair.Create("Replaces Low Blow (Stun) with Interject (Interrupt) when the target can be interrupted.", "当目标可被中断时，用Interject（中断）替换Low Blow（眩晕）。"),
                KeyValuePair.Create("PLDs can slot Shield Bash to have the feature to work with Shield Bash.", "骑士可以装备Shield Bash以使该功能与Shield Bash一起使用。"),
                KeyValuePair.Create("Prevents the use of Reprisal when target already has the effect by replacing it with Savage Blade.", "当目标已有该效果时，用Savage Blade替换Reprisal以防止使用Reprisal。"),
                KeyValuePair.Create("Features and options involving shared role actions for Healers.", "涉及治疗者共享职能技能的功能和选项。"),
                KeyValuePair.Create("Changes the class' Raise Ability into Swiftcast.", "将该职业的复活技能更改为Swiftcast。"),
                KeyValuePair.Create("Features and options involving shared role actions for Magical Ranged DPS.", "涉及远程魔法DPS共享职能技能的功能和选项。"),
                KeyValuePair.Create("Prevents the use of Addle when target already has the effect by replacing it with Savage Blade.", "当目标已有该效果时，用Savage Blade替换Addle以防止使用Addle。"),
                KeyValuePair.Create("Red Mage will also show VerCure if Swiftcast is on cooldown.", "如果Swiftcast在冷却中，赤魔法师还会显示Vercure。"),
                KeyValuePair.Create("Features and options involving shared role actions for Melee DPS.", "涉及近战DPS共享职能技能的功能和选项。"),
                KeyValuePair.Create("Prevents the use of Feint when target already has the effect by replacing it with Savage Blade.", "当目标已有该效果时，用Savage Blade替换Feint以防止使用Feint。"),
                KeyValuePair.Create("Prevents the use of True North when its buff is already active by replacing it with Savage Blade.", "当True North的增益效果已激活时，用Savage Blade替换True North以防止使用True North。"),
                KeyValuePair.Create("Features and options involving shared role actions for Physical Ranged DPS.", "涉及远程物理DPS共享职能技能的功能和选项。"),
                KeyValuePair.Create("Prevents the use of Tactician/Troubadour/Shield Samba when target already has one of those three effects by replacing them with Savage Blade.", "当目标已有Tactician/Troubadour/Shield Samba中的任一效果时，用Savage Blade替换它们以防止使用这些技能。"),
                KeyValuePair.Create("Replaces Foot Graze with Head Graze when target can be interrupted.", "当目标可被中断时，用Head Graze替换Foot Graze。"),
                KeyValuePair.Create("Outputs your performed actions to the chat.", "将你执行的技能输出到聊天窗口。"),
                KeyValuePair.Create("Uses Recuperate when your HP is under the set threshold and you have sufficient MP.", "当你的HP低于设定阈值且MP充足时，使用Recuperate。"),
                KeyValuePair.Create("Prevent Mash Cancelling Feature", "防止快速点击取消防御"),
                KeyValuePair.Create("Uses Guard when your HP is under the set threshold.", "当你的HP低于设定阈值时，使用Guard。"),
                KeyValuePair.Create("Uses Purify when afflicted with any selected debuff.", "当你受到任何选定的减益效果影响时，使用Purify。"),
                KeyValuePair.Create("Stops you cancelling your guard if you're pressing buttons quickly by replacing your buttons with Savage Blade.", "如果你快速按下按钮，用Savage Blade替换你的按钮以防止你取消Guard。"),
                KeyValuePair.Create("Allows you to cancel your guard with Recuperate on the Guard button if health is low enough to not waste it.", "当生命值足够低时，允许你在防御按钮上使用自愈技能来取消防御，以避免浪费。"),                
                KeyValuePair.Create("Turns Berserk / Inner Release into the Primal combo (Primal Rend -> Primal Ruination) on use.", "使用时将狂暴/原初的解放转换为原初连击（蛮荒崩裂 -> 尽毁）。"),                
                KeyValuePair.Create("Adds Primal Ruination into the AoE rotation.", "将尽毁加入AOE循环。"),                
                KeyValuePair.Create("Retargets Benefic and Benefic II to the heal stack (even from the Benefic 2 Downgrade Feature above).", "将吉星和福星重新定向到治疗堆栈（即使触发了上方的福星降级选项）。"),
                KeyValuePair.Create("Applies HP check to Non-Boss Encounters only", "仅对非Boss遭遇战应用HP检查"),
                KeyValuePair.Create("For PLDs this feature will add Shield Bash when Interject and Low Blow are on cooldown.", "对于骑士，当插言和下踢都在冷却中时，此功能将添加盾牌猛击。"),
                KeyValuePair.Create("Retarget Interrupts", "重定向打断技能"),
                KeyValuePair.Create("Will retarget the interrupt if the caster is not your current target.", "如果施法者不是你当前的目标，将重定向打断技能。"),
                KeyValuePair.Create("Tank: Shirk Retargeting", "防护职业：退避重定向"),
                KeyValuePair.Create("Retargets Shirk to the other tank if there is one.", "如果有其他防护职业，将退避重定向到其他防护职业。"),
                KeyValuePair.Create("Use Healers instead", "治疗职业替代"),
                KeyValuePair.Create("Will Retarget Shirk to healers, instead of the other tank.", "将退避重定向到治疗职业，而不是其他防护职业。"),
                KeyValuePair.Create("Only recommended during some specific enrages.", "仅在特定狂暴阶段推荐使用。"),
                KeyValuePair.Create("Fallback to Any Support", "回退到任意支援职业"),
                KeyValuePair.Create("Will Retarget Shirk to tanks or healers, per your setting above, but will include a fallback to any tank OR healer if none of your setting is found.", "将根据上述设置将退避重新定向到防护职业或治疗职业，但如果找不到你选择的玩家，将回退到任意防护职业或治疗职业。"),
                KeyValuePair.Create("Useful to help your Shirk always go to *someone* even if your chosen players are not alive.", "有助于确保你的退避总是能施放到*某人*身上，即使你选择的玩家已经死亡。"),
                KeyValuePair.Create("Healer: Esuna Retargeting", "治疗职业：康复重定向"),
                KeyValuePair.Create("Retargets Esuna (outside of combo usage) to your Heal Stack, checking if each potential target in the stack has a cleansable debuff.", "将康复（在连击使用之外）重定向到你的治疗堆栈，检查堆栈中每个潜在目标是否有可净化的减益效果。"),
                KeyValuePair.Create("Healer: Rescue Retargeting", "治疗职业：营救重定向"),
                KeyValuePair.Create("Retargets Rescue (outside of combo usage) to UI Mouseover and additional options.", "将营救（在连击使用之外）重定向到鼠标悬停目标和额外选项。"),
                KeyValuePair.Create("Enable this to add Variant Actions in Variant Dungeons.", "启用此选项可在多变迷宫中添加多变技能。"),
                KeyValuePair.Create("Variant Actions will be used by Single Target and AoE DPS Combos, in both Simple & Advanced", "多变技能将被单体目标和多目标输出连击使用，包括简单和高级模式"),
                KeyValuePair.Create("Use Variant Raise on incapacitated party members.", "对失去战斗能力的队友使用多变复活。"),
                KeyValuePair.Create("Use Variant Spirit Dart whenever the debuff is not present or less than 3s", "当减益效果不存在或剩余时间少于3秒时使用多变精神镖。"),
                KeyValuePair.Create("Variant Magic", "多变法系输出"),
                KeyValuePair.Create("Variant Actions will be used by Single Target and AoE DPS Features, in both Simple & Advanced selections", "多变技能将被单体目标和多目标输出功能使用，包括简单和高级选择"),

                // Manually added
                // PLD
                KeyValuePair.Create("Guardian", PLD.Guardian.ActionName()),
                // WAR
                KeyValuePair.Create("Primal Ruination", WAR.PrimalRuination.ActionName()),
                // SMN                
                KeyValuePair.Create("DeathFlare", SMNPvP.DeathFlare.ActionName()),
                // SGE
                KeyValuePair.Create("Addersgall Threshold", "蛇胆阈值"),
                // Config
                KeyValuePair.Create("MP Threshold", "魔力阈值"),
                #endregion

                #region General
                KeyValuePair.Create("Interrupt with Stun Option", "使用眩晕技能打断"),
                KeyValuePair.Create("Interrupt with Low Blow Option", "使用下踢打断"),
                KeyValuePair.Create("Adds Low Blow to the rotation when your target is casting.", "当你的目标正在施法时，将下踢加入循环。"),
                KeyValuePair.Create("Not advised outside of overworld content, as it can waste a lot of Low Blows on un-stun-able enemies, etc. Will try to not use it in boss fights.", "不建议在野外等内容中使用，因为它会在无法眩晕的敌人上浪费很多下踢。将在BOSS战中尽量不使用。"),                
                KeyValuePair.Create("Interrupt with Shield Bash Option", "使用盾牌猛击打断"),
                KeyValuePair.Create("Adds Shield Bash to the rotation when your target is casting.", "当你的目标正在施法时，将盾牌猛击加入循环。"),
                KeyValuePair.Create("Not advised outside of overworld content, as it can waste a lot of GCDs on un-stun-able enemies, etc. Will try to not use it in boss fights.", "不建议在野外等内容中使用，因为它会在无法眩晕的敌人上浪费很多GCD。将在BOSS战中尽量不使用。"),
                #endregion

                #region PvP
                // Melee DPS
                KeyValuePair.Create("Role Action Smite Option", "职能技能-猛击"),
                KeyValuePair.Create("Adds Role Action Smite to Burst Mode below selected health", "在目标生命值低于所选阈值时，将职能技能猛击添加到爆发模式"),
                KeyValuePair.Create("Set the HP percentage to be at or under for the feature to kick in.", "设置生命值百分比阈值，使功能生效。"),
                KeyValuePair.Create("100% is considered to start at 8,000 less than your max HP to prevent wastage.", "100%被认为是开始于8,000小于你的最大生命值，以防止浪费。"),
                KeyValuePair.Create("Target HP% to smite, Max damage below 25%", "猛击的目标生命值百分比阈值，最大伤害低于25%"),
                KeyValuePair.Create("HP Value to be at or under:", "生命值等于或低于："),
                // Healer
                KeyValuePair.Create("Role Action Diabrosis Option", "职能技能-溃破"),
                KeyValuePair.Create("Adds Role Action Diabrosis to Burst Mode below selected health", "在目标生命值低于所选阈值时，将职能技能溃破添加到爆发模式"),
                KeyValuePair.Create("Cure 3 Waste Prevention", "当愈疗就绪增益剩余时间低于6秒时，将愈疗添加到爆发连击"),
                KeyValuePair.Create("Target HP% to use Diabrosis", "使用溃破的目标生命值百分比阈值"),
                KeyValuePair.Create("Cure III Priority Option", "愈疗优先级"),
                KeyValuePair.Create("Makes Cure 3 prioritized before Aquaveil.", "使愈疗在水流幕之前优先使用。"),
                KeyValuePair.Create("Cure 3 replaces Cure 2 regardless of this setting as that is how SE made it", "无论此设置如何，愈疗都会替换救疗，这是官方的设定。"),
                KeyValuePair.Create("Adlo Option", "鼓舞激励之策"),
                KeyValuePair.Create("Adlo Retarget", "重定向鼓舞激励之策"),
                KeyValuePair.Create("Retargets Adlo to the heal stack (In Wrath Settings) outside of the Burst Feature", "在爆发模式之外，将鼓舞激励之策重定向到治疗堆栈（在插件设置中设置）"),
                KeyValuePair.Create("Retarget Adlo", "重定向鼓舞激励之策"),
                KeyValuePair.Create("HP% to use Adlo", "使用鼓舞激励之策的目标生命值百分比阈值"),
                KeyValuePair.Create("Adds Adloquium to self when at or beneath selected heath threshold.", "当自身生命值低于或等于设定阈值时，为自己使用鼓励激励之策。"),
                KeyValuePair.Create("Will Not Overwrite Catalyze", "不会覆盖激励。"),
                KeyValuePair.Create("Adds Cure 2/3 and Aquaveil to Burst combo below all damage options.", "将救疗和愈疗和水流幕添加到爆发连击下方所有伤害选项。"),
                KeyValuePair.Create("Heals in the Burst Mode", "爆发模式中的治疗"),
                KeyValuePair.Create("To the Heal Stack (In Wrath Settings)", "治疗堆栈（在插件设置中设置）"),
                KeyValuePair.Create("Retarget Cure 2", "重定向救疗"),
                KeyValuePair.Create("Retarget Cure 3", "重定向愈疗"),
                KeyValuePair.Create("Retarget Aquaveil", "重定向水流幕"),
                KeyValuePair.Create("Adds Kardia Reminder to Burst Mode if buff is missing", "如果buff缺失，在爆发模式中添加心关提醒"),
                KeyValuePair.Create("Kardia Retarget", "重定向心关"),
                KeyValuePair.Create("Retargets Kardia to the heal stack (In Wrath Settings) outside of the Burst Feature", "在爆发模式之外，将心关重定向到治疗堆栈（在插件设置中设置）"),
                KeyValuePair.Create("Mobile Kardia Option", "移动心关选项"),
                KeyValuePair.Create("Retarget Kardia according to your heal stack. ", "根据你的治疗堆栈重定向心关。"),
                KeyValuePair.Create("This will move Kardia around via weaves. Will use Heal stack.(In Wrath Settings)", "这将通过能力技插入切换心关。将遵循治疗堆栈（在插件设置中设置）"),

                // Physical Ranged DPS
                KeyValuePair.Create("Role Action Eagle Eye Shot Option", "职能技能-锐眼追击"),
                KeyValuePair.Create("Automatically Adds Eagle Eye Shot to Burst Mode when target is guarded or under selected health percentage", "当目标处于防御状态或生命值低于所选百分比时，自动在爆发模式中加入锐眼追击"),
                KeyValuePair.Create("WILL ONLY WORK IN LARGE SCALE PVP", "仅在大规模PVP中有效"),
                KeyValuePair.Create("Do not use Purify below set MP", "当魔力低于设定阈值时，不使用净化。"),
                // Tank
                KeyValuePair.Create("Role Action Rampart Option", "职能技能-铁壁"),
                KeyValuePair.Create("Adds Defensive Role Action Rampart to Burst Mode below selected health", "在生命值低于所选阈值时，将防御型职能技能铁壁添加到爆发模式"),
                KeyValuePair.Create("Use Rampart below set threshold for self", "低于设定阈值时，为自己使用铁壁"),
                KeyValuePair.Create("Must be missing this much health to use Holy Spirit", "当生命值低于设定阈值时，使用圣灵。"),
                KeyValuePair.Create("Uses Guard when at or under:", "当生命值低于或等于设定阈值时，使用防御。"),
                // Magical Ranged DPS
                KeyValuePair.Create("Phantom Dart Option", "幻影弹"),
                KeyValuePair.Create("Uses Phantom Dart (if selected) when available at or below set health threshold.", "在可用且目标生命值低于设定阈值时（若已选择），使用幻影弹。"),
                KeyValuePair.Create("Target HP percent threshold to use Eagle Eye Shot Below.", "锐眼追击的目标生命值百分比阈值"),

                // Jobs Config
                KeyValuePair.Create("Select what kind of enemies the HP check should be applied to:", "选择HP检查应应用于哪些类型的敌人："),
                KeyValuePair.Create("Select which difficulties the ability should be used in:", "选择应在哪些难度下使用："),
                KeyValuePair.Create("How many charges to keep for manual usage.", "保留多少充能数供手动使用："),
                #endregion
            ];
        }
    }
}
