using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class Genesis
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region ADV
                KeyValuePair.Create("Island Sanctuary Sprint Feature", "无名岛冲刺特性"),
                KeyValuePair.Create("Replaces Sprint with Isle Sprint.", "用海岛冲刺替换冲刺。"),
                KeyValuePair.Create("Only works at the Island Sanctuary. Icon does not change.", "仅在无名岛有效。图标不会改变。"),
                KeyValuePair.Create("Do not use with SimpleTweaks' Island Sanctuary Sprint fix.", "不要与SimpleTweaks的海岛冲刺替换功能一起使用。"),
                KeyValuePair.Create("Features and options involving shared role actions for Tanks.", "涉及坦克共享职能技能的功能和选项。"),
                KeyValuePair.Create("Replaces Low Blow (Stun) with Interject (Interrupt) when the target can be interrupted.", "当目标可被中断时，用Interject（中断）替换Low Blow（眩晕）。"),
                KeyValuePair.Create("PLDs can slot Shield Bash to have the feature to work with Shield Bash.", "骑士可以装备Shield Bash以使该功能与Shield Bash一起使用。"),
                KeyValuePair.Create("Prevents the use of Reprisal when target already has the effect by replacing it with Savage Blade.", "当目标已有该效果时，用Savage Blade替换Reprisal以防止使用Reprisal。"),
                KeyValuePair.Create("Features and options involving shared role actions for Healers.", "涉及治疗者共享职能技能的功能和选项。"),
                KeyValuePair.Create("Changes the class' Raise Ability into Swiftcast.", "将该职业的复活技能更改为Swiftcast。"),
                KeyValuePair.Create("Features and options involving shared role actions for Magical Ranged DPS.", "涉及远程魔法DPS共享职能技能的功能和选项。"),
                KeyValuePair.Create("Prevents the use of Addle when target already has the effect by replacing it with Savage Blade.", "当目标已有该效果时，用Savage Blade替换Addle以防止使用Addle。"),
                KeyValuePair.Create("Red Mage will also show VerCure if Swiftcast is on cooldown.", "如果Swiftcast在冷却中，赤魔法师还会显示Vercure。"),
                KeyValuePair.Create("Features and options involving shared role actions for Melee DPS.", "涉及近战DPS共享职能技能的功能和选项。"),
                KeyValuePair.Create("Prevents the use of Feint when target already has the effect by replacing it with Savage Blade.", "当目标已有该效果时，用Savage Blade替换Feint以防止使用Feint。"),
                KeyValuePair.Create("Prevents the use of True North when its buff is already active by replacing it with Savage Blade.", "当True North的增益效果已激活时，用Savage Blade替换True North以防止使用True North。"),
                KeyValuePair.Create("Features and options involving shared role actions for Physical Ranged DPS.", "涉及远程物理DPS共享职能技能的功能和选项。"),
                KeyValuePair.Create("Prevents the use of Tactician/Troubadour/Shield Samba when target already has one of those three effects by replacing them with Savage Blade.", "当目标已有Tactician/Troubadour/Shield Samba中的任一效果时，用Savage Blade替换它们以防止使用这些技能。"),
                KeyValuePair.Create("Replaces Foot Graze with Head Graze when target can be interrupted.", "当目标可被中断时，用Head Graze替换Foot Graze。"),
                KeyValuePair.Create("Outputs your performed actions to the chat.", "将你执行的技能输出到聊天窗口。"),
                KeyValuePair.Create("Uses Recuperate when your HP is under the set threshold and you have sufficient MP.", "当你的HP低于设定阈值且MP充足时，使用Recuperate。"),
                KeyValuePair.Create("Prevent Mash Cancelling Feature", "防止快速点击取消防御"),
                KeyValuePair.Create("Uses Guard when your HP is under the set threshold.", "当你的HP低于设定阈值时，使用Guard。"),
                KeyValuePair.Create("Uses Purify when afflicted with any selected debuff.", "当你受到任何选定的减益效果影响时，使用Purify。"),
                KeyValuePair.Create("Stops you cancelling your guard if you're pressing buttons quickly by replacing your buttons with Savage Blade.", "如果你快速按下按钮，用Savage Blade替换你的按钮以防止你取消Guard。"),
                KeyValuePair.Create("Allows you to cancel your guard with Recuperate on the Guard button if health is low enough to not waste it.", "当生命值足够低时，允许你在防御按钮上使用自愈技能来取消防御，以避免浪费。"),
                KeyValuePair.Create("Set value for your MP to be at or under for this feature to work", "设置你的 MP 值，当 MP 等于或低于该值时此功能生效"),
                
                // Manually added
                // PLD
                KeyValuePair.Create("Guardian", PLD.Guardian.ActionName()),
                // WAR
                KeyValuePair.Create("Primal Ruination", WAR.PrimalRuination.ActionName()),
                // SMN                
                KeyValuePair.Create("DeathFlare", SMNPvP.DeathFlare.ActionName()),
                // SGE
                KeyValuePair.Create("Addersgall Threshold", "蛇胆阈值"),
                // Config
                KeyValuePair.Create("MP Threshold", "魔力阈值"),
                #endregion
            ];
        }
    }
}
