using System;
using System.Collections.Generic;
using WrathCombo.Data;
using WrathCombo.Extensions;
using static WrathCombo.Combos.PvE.MCH;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class MCHDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region MCHPvE
                KeyValuePair.Create("Replaces Split Shot with a full one-button single target rotation.", "用完整的一键单目标循环替换分裂弹。"),
                KeyValuePair.Create("Replaces Spreadshot with a full one-button AoE rotation.", "用完整的一键AoE循环替换散射。"),
                KeyValuePair.Create("Will lock out input to keep Flamethrower going by replacing Spreadshot with Savage Blade.", "通过用狂怒剑替换散射来锁定输入以保持火焰喷射器的持续。"),
                KeyValuePair.Create("Adds the Balance opener at lvl 90+.", "在90级以上时使用由「The Balance」社区推荐的起手循环。"),
                KeyValuePair.Create("Adds Barrel Stabilizer to the rotation.", "将枪管加热添加到循环中。"),
                KeyValuePair.Create("Adds Full Metal Field to the rotation.", "将全金属爆发添加到循环中。"),
                KeyValuePair.Create("Adds Gauss Round and Ricochet or Double Check and Checkmate to the rotation. Will prevent overcapping.", "将虹吸弹和弹射或双将和将死添加到循环中。防止资源溢出。"),
                KeyValuePair.Create("Adds Wildfire to the rotation.", "将野火添加到循环中。"),
                KeyValuePair.Create("Adds Hypercharge to the rotation.", "将超荷添加到循环中。"),
                KeyValuePair.Create("Adds Heat Blast or Blazing Shot to the rotation", "将热冲击或烈焰弹添加到循环中。"),
                KeyValuePair.Create("Adds Rook Autoturret or Automaton Queen to the rotation.", "将车式浮空炮塔或后式自走人偶添加到循环中。"),
                KeyValuePair.Create("Rook / Queen Overdrive Option", "车/后式超档选项"),
                KeyValuePair.Create("Adds Rook or Queen Overdrive to the rotation.", "将超档车式炮塔或超档后式人偶添加到循环中。"),
                KeyValuePair.Create("Adds Reassemble to the rotation.", "将整备添加到循环中。"),
                KeyValuePair.Create("Will be used priority based.", "将根据优先级使用。"),
                KeyValuePair.Create("Order from highest to lowest priority :", "优先级从高到低排序："),
                KeyValuePair.Create("Excavator - Chainsaw - Air Anchor - Drill - Clean Shot", "掘地飞轮 - 回转飞锯 - 空气锚 - 钻头 - 狙击弹"),
                KeyValuePair.Create("Adds Drill to the rotation.", "将钻头添加到循环中。"),
                KeyValuePair.Create("Adds Hot Shot/Air Anchor to the rotation.", "将热弹/空气锚添加到循环中。"),
                KeyValuePair.Create("Adds Chain Saw to the rotation.", "将回转飞锯添加到循环中。"),
                KeyValuePair.Create("Adds Excavator to the rotation.", "将掘地飞轮添加到循环中。"),
                KeyValuePair.Create("Uses Head Graze to interrupt during the rotation, where applicable.", "在适用的情况下，使用Head Graze在循环中打断。"),
                KeyValuePair.Create("Use Second Wind when below the set HP percentage.", "当HP低于设定百分比时使用内丹。"),
                KeyValuePair.Create("Adds Flamethrower to the rotation.", "将火焰喷射器添加到循环中。"),
                KeyValuePair.Create(" Changes to Savage blade when in use to prevent cancelling.", "在使用时更改为狂怒剑以防止取消。"),
                KeyValuePair.Create("Adds Gauss Round and Ricochet or Double Check and Checkmate to the rotation.", "将虹吸弹和弹射或双将和将死添加到循环中。（至少选择一个）"),
                KeyValuePair.Create("Use Blazing shot instead of Crossbow at lvl 92+", "在92级以上时使用烈焰弹代替自动弩。"),
                KeyValuePair.Create("Adds Bioblaster to the rotation.", "将毒菌冲击添加到循环中。"),
                KeyValuePair.Create("Adds Air Anchor to the the rotation.", "将空气锚添加到循环中。"),
                KeyValuePair.Create("Adds Chain Saw to the the rotation.", "将回转飞锯添加到循环中。"),
                KeyValuePair.Create("Prevents the use of Dismantle when target already has the effect by replacing it with Savage Blade.", "当目标已有武装解除效果时，通过用狂怒剑替换来防止使用武装解除。"),
                KeyValuePair.Create("Swap dismantle with tactician when dismantle is on cooldown.", "当武装解除冷却时，用策动替换武装解除。"),
                KeyValuePair.Create("Turns Heat Blast or Blazing Shot into Hypercharge ", "当你有50或更多热量或获得超荷增益时，将热冲击或烈焰弹转换为超荷。"),
                KeyValuePair.Create("when u have 50 or more heat or when u got Hypercharged buff.", "当你有50或更多热量或获得超荷增益时。"),
                KeyValuePair.Create("Adds Barrel Stabilizer to the feature when off cooldown.", "冷却结束时将枪管加热添加到功能中。"),
                KeyValuePair.Create("Adds Wildfire to the feature when off cooldown and overheated.", "冷却结束且过热时将野火添加到功能中。"),
                KeyValuePair.Create("Switches between Heat Blast and either Gauss Round and Ricochet or Double Check and Checkmate, depending on cooldown timers.", "根据冷却时间在热冲击与虹吸弹/弹射或双将/将死之间切换。"),
                KeyValuePair.Create("Turns Auto Crossbow into Hypercharge when at or above 50 heat.", "当热量达到或超过50时，将自动弩转换为超荷。"),
                KeyValuePair.Create("Adds Barrel Stabilizer to the feature when below 50 Heat Gauge.", "当热量低于50时，将枪管加热添加到功能中。"),
                KeyValuePair.Create("Switches between Auto Crossbow and either Gauss Round and Ricochet or Double Check and Checkmate, depending on cooldown timers.", "根据冷却时间在自动弩与虹吸弹/弹射或双将/将死之间切换。"),
                KeyValuePair.Create("Replace Rook Autoturret and Automaton Queen with Overdrive while active.", "在激活时用超档替换车式浮空炮塔和后式自走人偶。"),
                KeyValuePair.Create("Replace Hot Shot, Drill, Air Anchor, Chainsaw and Excavator depending on which is on cooldown.", "根据冷却时间替换热弹、钻头、空气锚、回转飞锯和掘地飞轮。"),
                KeyValuePair.Create("Replace Gauss Round and Ricochet or Double Check and Checkmate with one or the other depending on which has more charges.", "根据剩余次数在虹吸弹/弹射或双将/将死之间替换。"),
                KeyValuePair.Create("Number of Charges to Save for Manual Use", "保留用于手动使用的充能次数"),
                KeyValuePair.Create($"Uses {AutomatonQueen.ActionName()} at this battery threshold outside of Boss encounter.", $"在非Boss战中，当电量达到此阈值时使用{AutomatonQueen.ActionName()}。"),
                KeyValuePair.Create("Only counts for 'Boss encounters Only setting'.", "仅适用于“仅限Boss战”设置。"),
                KeyValuePair.Create("HP% for the target to be at or under", "目标生命百分比达到或低于此值"),
                KeyValuePair.Create($"Uses {AutomatonQueen.ActionName()} logic regardless of content.", $"无论内容如何，使用{AutomatonQueen.ActionName()}的逻辑。"),
                KeyValuePair.Create($"Uses {Excavator.ActionName()} logic regardless of content.", $"无论内容如何，使用{Excavator.ActionName()}的逻辑。"),
                KeyValuePair.Create($"Only uses {Excavator.ActionName()} logic when in Boss encounters.", $"仅在Boss战中使用{Excavator.ActionName()}的逻辑。"),
                KeyValuePair.Create($"Only uses {AutomatonQueen.ActionName()} logic when in Boss encounters.", $"仅在Boss战中使用{AutomatonQueen.ActionName()}的逻辑。"),
                KeyValuePair.Create("Battery threshold", "电量阈值"),
                KeyValuePair.Create("Barrel Option", "枪管加热"),
                KeyValuePair.Create($"Stop Using {Reassemble.ActionName()} When Target HP% is at or Below (Set to 0 to Disable This Check)", $"当目标血量百分比达到或低于此值时停止使用{Reassemble.ActionName()}（设置为0以禁用此检查）"),
                KeyValuePair.Create($"Stop Using {RookAutoturret.ActionName()} When Target HP% is at or Below (Set to 0 to Disable This Check)", $"当目标血量百分比达到或低于此值时停止使用{RookAutoturret.ActionName()}（设置为0以禁用此检查）"),
                KeyValuePair.Create($"Stop Using {BarrelStabilizer.ActionName()} When Target HP% is at or Below (Set to 0 to Disable This Check)", $"当目标血量百分比达到或低于此值时停止使用{BarrelStabilizer.ActionName()}（设置为0以禁用此检查）"),
                KeyValuePair.Create($"Stop Using {Chainsaw.ActionName()} When Target HP% is at or Below (Set to 0 to Disable This Check)", $"当目标血量百分比达到或低于此值时停止使用{Chainsaw.ActionName()}（设置为0以禁用此检查）"),
                KeyValuePair.Create($"Stop Using {Hypercharge.ActionName()} When Target HP% is at or Below (Set to 0 to Disable This Check)", $"当目标血量百分比达到或低于此值时停止使用{Hypercharge.ActionName()}（设置为0以禁用此检查）"),
                KeyValuePair.Create($"Change {GaussRound.ActionName()} / {DoubleCheck.ActionName()}", $"更改为{GaussRound.ActionName()} / {DoubleCheck.ActionName()}"),
                KeyValuePair.Create($"Changes to {Ricochet.ActionName()} / {CheckMate.ActionName()} depending on charges and what was used last", $"根据充能次数和上次使用情况，更改为{Ricochet.ActionName()} / {CheckMate.ActionName()}。"),
                KeyValuePair.Create($"Change {Ricochet.ActionName()} / {CheckMate.ActionName()}", $"更改为{Ricochet.ActionName()} / {CheckMate.ActionName()}"),
                KeyValuePair.Create($"Changes to {GaussRound.ActionName()} / {DoubleCheck.ActionName()} depending on charges and what was used last", $"根据充能次数和上次使用情况，更改为{GaussRound.ActionName()} / {DoubleCheck.ActionName()}。"),
                KeyValuePair.Create("Tactician Raidwide Option", "策动"),
                KeyValuePair.Create("Adds Tactician when Raidwide is detected casting.", "当检测到群体攻击施法时添加策动。"),
                KeyValuePair.Create("Dismantle Raidwide Option", "武装解除"),
                KeyValuePair.Create("Adds Dismantle when Raidwide is detected casting.", "当检测到群体攻击施法时添加武装解除。"),
                KeyValuePair.Create($"Use on {SpreadShot.ActionName()}/{Scattergun.ActionName()}", $"用于{SpreadShot.ActionName()}/{Scattergun.ActionName()}"),
                KeyValuePair.Create($"Use on {AirAnchor.ActionName()}", $"用于{AirAnchor.ActionName()}"),
                KeyValuePair.Create($"Use on {Chainsaw.ActionName()}", $"用于{Chainsaw.ActionName()}"),
                KeyValuePair.Create($"Use on {Excavator.ActionName()}", $"用于{Excavator.ActionName()}"),
                KeyValuePair.Create($"Use on {Drill.ActionName()}", $"用于{Drill.ActionName()}"),
                KeyValuePair.Create($"Use on {CleanShot.ActionName()}", $"用于{CleanShot.ActionName()}"),
                KeyValuePair.Create("Will follow Balance logic if selected on Turret/Queen.", "若在炮塔/人偶选项中启用，将遵循「The Balance」逻辑。"),
                KeyValuePair.Create("Balance Opener (Level 90/100)", "「The Balance」起手循环（90级/100级）"),
                KeyValuePair.Create("Adds the Balance opener at lvl 90/100.", "在90级/100级时添加「The Balance」起手循环。"),
                KeyValuePair.Create("Adds Hotshot, Drill, Air Anchor, Chainsaw and Excavator to the rotation.", "将热弹、钻头、空气锚、回转飞锯和掘地飞轮添加到循环中。"),
                KeyValuePair.Create("Adds Bioblaster, Air Anchor, Chainsaw and Excavator to the rotation.", "将毒菌冲击、空气锚、回转飞锯和掘地飞轮添加到循环中。"),
                #endregion
                
                #region MCHPvP
                KeyValuePair.Create("Turns Blast Charge into an all-in-one damage button.", "将蓄力冲击变为一个全能伤害按钮。"),
                KeyValuePair.Create("Adds Air Anchor to Burst Mode.", "将空气锚加入爆发模式。"),
                KeyValuePair.Create("Adds Analysis to Burst Mode.", "将分析加入爆发模式。"),
                KeyValuePair.Create("Alternate Analysis Option", "保留分析"),
                KeyValuePair.Create("Uses Analysis with Air Anchor instead of Chain Saw.", "在爆发模式中将分析与空气锚配合使用，而非回转飞锯。"),
                KeyValuePair.Create("Adds Drill to Burst Mode.", "将钻头加入爆发模式。"),
                KeyValuePair.Create("Saves Drill for use after Wildfire.", "保留钻头在野火之后使用。"),
                KeyValuePair.Create("Bio Blaster Option", "毒菌冲击"),
                KeyValuePair.Create("Adds Bio Blaster to Burst Mode.", "将毒菌冲击加入爆发模式。"),
                KeyValuePair.Create("Adds Chain Saw to Burst Mode.", "将回转飞锯加入爆发模式。"),
                KeyValuePair.Create("Adds Full Metal Field to Burst Mode.", "将全金属爆发加入爆发模式。"),
                KeyValuePair.Create("Adds Wildfire to Burst Mode.", "将野火加入爆发模式。"),
                KeyValuePair.Create("Adds Marksmans Spite to Burst Mode when the target is below specified HP.", "当目标生命值低于指定值时，将魔弹射手加入爆发模式。"),
                KeyValuePair.Create("Adds Barrel Stabilizer to Burst Mode.", "将枪管加热加入爆发模式。"),
                KeyValuePair.Create("Alternate Drill Option", "保留钻头"),
                KeyValuePair.Create("Full Metal Field Wildfire combo", "全金属爆发野火连击"),
                KeyValuePair.Create("Uses Full Metal Field when Wildfire is ready.", "当野火准备就绪时使用全金属爆发"),
                KeyValuePair.Create("Full Metal Field only when Overheated", "仅在过热时使用全金属爆发"),
                KeyValuePair.Create("Only uses Full Metal Field while Overheated.", "只在过热状态下使用全金属爆发"),
                KeyValuePair.Create("Use Marksman's Spite when the target is below set HP", "当目标血量低于设定值时使用魔弹射手"),
                #endregion
            ];
        }
    }
}
