using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class OccultDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region OccultCrescent
                // 自由人技能
                KeyValuePair.Create("Freelancer Job Actions", "自由人技能"),
                KeyValuePair.Create("Enable this to add Freelancer-specific actions into the rotation.", "启用此选项将自由人专用技能加入循环。"),
                
                // 辅助骑士技能
                KeyValuePair.Create("Knight Job Actions", "辅助骑士技能"),
                KeyValuePair.Create("Enable this to add Knight-specific actions into the rotation.", "启用此选项将辅助骑士专用技能加入循环。"),
                KeyValuePair.Create("Phantom Guard", "防护"),
                KeyValuePair.Create("Adds Phantom Guard into the rotation.", "将防护加入循环。"),
                
                // 辅助武僧技能
                KeyValuePair.Create("Monk Job Actions", "辅助武僧技能"),
                KeyValuePair.Create("Enable this to add Monk-specific actions into the rotation.", "启用此选项将辅助武僧专用技能加入循环。"),
                
                // 辅助盗贼技能
                KeyValuePair.Create("Thief Job Actions", "辅助盗贼技能"),
                KeyValuePair.Create("Enable this to add Thief-specific actions into the rotation.", "启用此选项将辅助盗贼专用技能加入循环。"),
                KeyValuePair.Create("Vigilance", "警戒"),
                KeyValuePair.Create("Adds Vigilance into the rotation.", "将警戒加入循环。"),
                
                // 辅助武士技能
                KeyValuePair.Create("Samurai Job Actions", "辅助武士技能"),
                KeyValuePair.Create("Enable this to add Samurai-specific actions into the rotation.", "启用此选项将辅助武士专用技能加入循环。"),
                KeyValuePair.Create("Phantom Mineuchi", "刀背打"),
                KeyValuePair.Create("Adds Phantom Mineuchi into the rotation.", "将刀背打加入循环。"),
                KeyValuePair.Create("Phantom Shirahadori", "空手接白刃"),
                KeyValuePair.Create("Adds Phantom Shirahadori into the rotation.", "将空手接白刃加入循环。"),
                KeyValuePair.Create("Phantom Iainuki", "居合斩"),
                KeyValuePair.Create("Adds Phantom Iainuki into the rotation.", "将居合斩加入循环。"),
                KeyValuePair.Create("Phantom Zeninage", "扔钱"),
                KeyValuePair.Create("Adds Phantom Zeninage into the rotation.", "将扔钱加入循环。"),
                
                // 辅助狂战士技能
                KeyValuePair.Create("Berserker Job Actions", "辅助狂战士技能"),
                KeyValuePair.Create("Enable this to add Berserker-specific actions into the rotation.", "启用此选项将辅助狂战士专用技能加入循环。"),
                
                // 辅助猎人技能
                KeyValuePair.Create("Ranger Job Actions", "辅助猎人技能"),
                KeyValuePair.Create("Enable this to add Ranger-specific actions into the rotation.", "启用此选项将辅助猎人专用技能加入循环。"),
                
                // 辅助时魔法师技能
                KeyValuePair.Create("Time Mage Job Actions", "辅助时魔法师技能"),
                KeyValuePair.Create("Enable this to add Time Mage-specific actions into the rotation.", "启用此选项将辅助时魔法师专用技能加入循环。"),
                KeyValuePair.Create("Wait to get Full(-ish) Effect", "等待获得完整效果"),
                KeyValuePair.Create("Will not use Slowga if the diminishing return from repeated use is substantial, or there would be no diminishing return at all.", "如果重复使用魔强减速的收益递减严重或完全没有收益递减，则不会使用魔强减速。"),
                KeyValuePair.Create("Adds Occult Dispel into the rotation if the target has a known-dispellable status.", "如果目标有已知可驱散的异常状态，将魔驱魔加入循环。"),
                
                // 辅助药剂师技能
                KeyValuePair.Create("Chemist Job Actions", "辅助药剂师技能"),
                KeyValuePair.Create("Enable this to add Chemist-specific actions into the rotation.", "启用此选项将辅助药剂师专用技能加入循环。"),
                KeyValuePair.Create("Requires Occult Potions in inventory.", "需要背包中有魔恢复药。"),
                
                // 辅助吟游诗人技能
                KeyValuePair.Create("Bard Job Actions", "辅助吟游诗人技能"),
                KeyValuePair.Create("Enable this to add Bard-specific actions into the rotation.", "启用此选项将辅助吟游诗人专用技能加入循环。"),
                KeyValuePair.Create("Romeo's Ballad", "爱之歌"),
                KeyValuePair.Create("Adds Romeo's Ballad into the rotation.", "将爱之歌加入循环。"),
                KeyValuePair.Create("Hero's Rime", "英雄之歌"),
                KeyValuePair.Create("Adds Hero's Rime into the rotation.", "将英雄之歌加入循环。"),
                
                // 辅助预言师技能
                KeyValuePair.Create("Oracle Job Actions", "辅助预言师技能"),
                KeyValuePair.Create("Enable this to add Oracle-specific actions into the rotation.", "启用此选项将辅助预言师专用技能加入循环。"),
                
                // 辅助炮击士技能
                KeyValuePair.Create("Cannoneer Job Actions", "辅助炮击士技能"),
                KeyValuePair.Create("Enable this to add Cannoneer-specific actions into the rotation.", "启用此选项将辅助炮击士专用技能加入循环。"),
                KeyValuePair.Create("Phantom Fire", "炮击"),
                KeyValuePair.Create("Adds Phantom Fire into the rotation.", "将炮击加入循环。"),
                KeyValuePair.Create("Holy Cannon", "神圣炮"),
                KeyValuePair.Create("Adds Holy Cannon into the rotation.", "将神圣炮加入循环。"),
                
                // 辅助风水师技能
                KeyValuePair.Create("Geomancer Job Actions", "辅助风水师技能"),
                KeyValuePair.Create("Enable this to add Geomancer-specific actions into the rotation.", "启用此选项将辅助风水师专用技能加入循环。"),
                #endregion
            ];
        }
    }
}
