using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class PCTDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region PCTPvE
                KeyValuePair.Create("Replaces Fire in Red with a full one-button single target rotation.", "将火炎之红替换为完整的一键单体循环。"),
                KeyValuePair.Create("Replaces Fire in Red II with a full one-button AoE rotation.", "将烈炎之红替换为完整的一键群体循环。"),
                KeyValuePair.Create("Adds missing Motifs to the combo while out of combat.", "在战斗外时向连击添加缺失的彩绘。"),
                KeyValuePair.Create("Adds missing Motifs to the combo while no target is present in combat.", "在战斗中无目标时向连击添加缺失的彩绘。"),
                KeyValuePair.Create("Adds selected spells below to the burst phase.", "向爆发阶段添加下方选定的法术。"),
                KeyValuePair.Create("Adds Comet in Black to the burst phase.", "向爆发阶段添加Comet in Black。"),
                KeyValuePair.Create("Adds Star Prism to the burst phase.", "向爆发阶段添加Star Prism。"),
                KeyValuePair.Create("Adds Rainbow Drip to the burst phase.", "向爆发阶段添加Rainbow Drip。"),
                KeyValuePair.Create("Adds Hammer Stamp Combo to the burst phase.", "向爆发阶段添加Hammer Stamp Combo。"),
                KeyValuePair.Create("Adds Blizzard in Cyan to the burst phase.", "向爆发阶段添加冰结之蓝青。"),
                KeyValuePair.Create("Add Selected Motifs to the combo.", "向连击添加选定的彩绘。"),
                KeyValuePair.Create("Adds Landscape Motif.", "添加Landscape Motif。"),
                KeyValuePair.Create("Adds Weapon Motif.", "添加Weapon Motif。"),
                KeyValuePair.Create("Adds Selected Muses to the combo.", "向连击添加选定的构想。"),
                KeyValuePair.Create("Adds Scenic Muse.", "添加Scenic Muse。"),
                KeyValuePair.Create("Adds Living Muse.", "添加Living Muse。"),
                KeyValuePair.Create("Adds Steel Muse.", "添加Steel Muse。"),
                KeyValuePair.Create("Adds Mog/Madeen to the combo.", "向连击添加莫古力激流/马蒂恩惩罚。"),
                KeyValuePair.Create("Adds Subtractive Palette to the combo.", "向连击添加Subtractive Palette。"),
                KeyValuePair.Create("Adds Comet in Black to the combo.", "向连击添加Comet in Black。"),
                KeyValuePair.Create("Adds Hammer Stamp combo.", "添加Hammer Stamp连击。"),
                KeyValuePair.Create("Adds selected features to the combo while moving.", "在移动时向连击添加选定的功能。"),
                KeyValuePair.Create("Adds Hammer Stamp Combo to the combo while moving.", "在移动时向连击添加Hammer Stamp Combo。"),
                KeyValuePair.Create("Adds Holy in White to the combo while moving.", "在移动时向连击添加神圣之白。"),
                KeyValuePair.Create("Adds Comet in Black to the combo while moving.", "在移动时向连击添加Comet in Black。"),
                KeyValuePair.Create("Adds Swiftcast to the combo while moving.", "在移动时向连击添加Swiftcast。"),
                KeyValuePair.Create("Use swiftcast for motifs.", "使用Swiftcast来施放彩绘。"),
                KeyValuePair.Create("Adds Blizzard in Cyan to the combo.", "向连击添加冰结之蓝青。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the combo.", "向连击添加Lucid Dreaming。"),
                KeyValuePair.Create("Adds Holy in White to the combo.", "向连击添加Holy in White。"),
                KeyValuePair.Create("Merges aetherhue actions for specific target types into a single button.", "将特定目标类型的以太色调技能合并为一个按钮。"),
                KeyValuePair.Create("Merges Motifs and Muses into a single button.", "将彩绘和构想合并为一个按钮。"),
                KeyValuePair.Create("Consolidates paint-consuming actions into one button.", "将消耗颜料的技能整合为一个按钮。"),
                KeyValuePair.Create("Health % to stop Drawing Motif", "目标生命值百分比达到此值时停止彩绘"),
                KeyValuePair.Create("Prepull Motifs Feature", "战斗外彩绘"),
                KeyValuePair.Create("Downtime Motifs Option", "战斗中没有目标时补充彩绘"),
                KeyValuePair.Create("Blizzard in Cyan Option", "冰结之蓝青"),
                KeyValuePair.Create("Motif Selection Feature", "彩绘选择"),
                KeyValuePair.Create("Muse Selection Feature", "构想选择"),
                KeyValuePair.Create("Mog/Madeen Feature", "莫古力激流/马蒂恩惩罚"),
                KeyValuePair.Create("Holy in White Option", "神圣之白"),
                KeyValuePair.Create("Swiftcast Motifs Option", "即刻彩绘"),
                KeyValuePair.Create("Combined Aetherhues Feature", "整合以太色调"),
                KeyValuePair.Create("One Button Motifs", "一键构想"),
                KeyValuePair.Create("One Button Paint", "合并消耗颜料的技能为一个按钮"),
                #endregion
                
                #region PCTPvP
                KeyValuePair.Create("Turns Fire in Red into an all-in-one damage button.", "将红色状态下的Fire转化为一个全能伤害按钮。"),
                KeyValuePair.Create("Saves high-damaging actions until the target's HP falls below the threshold.", "在目标HP低于阈值前保留高伤害技能。"),
                KeyValuePair.Create("Uses Tempera Coat when HP falls below the threshold during combat.", "在战斗中HP低于阈值时使用Tempera Coat。"),
                KeyValuePair.Create("Uses Subtractive Palette when standing still and releases it when moving.", "站立不动时使用Subtractive Palette，移动时释放。"),
                KeyValuePair.Create("Adds Creature Motif to Burst Mode.", "在Burst Mode中添加Creature Motif。"),
                KeyValuePair.Create("Adds Living Muse to Burst Mode.", "在Burst Mode中添加Living Muse。"),
                KeyValuePair.Create("Adds Mog Of The Ages to Burst Mode.", "在Burst Mode中添加Mog Of The Ages。"),
                KeyValuePair.Create("Adds Holy In White to Burst Mode.", "在Burst Mode中添加Holy In White。"),
                KeyValuePair.Create("Adds Star Prism to Burst Mode.", "在Burst Mode中添加Star Prism。"),
                #endregion

                // Maunally added
                KeyValuePair.Create($"Add {PCT.MogoftheAges.ActionName()} when fully drawn and off cooldown.", $"当 {PCT.MogoftheAges.ActionName()} 完全绘制且冷却完成时添加。"),
                KeyValuePair.Create($"Add {PCT.RetributionoftheMadeen.ActionName()} when fully drawn and off cooldown.", $"当 {PCT.RetributionoftheMadeen.ActionName()} 完全绘制且冷却完成时添加。"),
                KeyValuePair.Create($"Add {PCT.HammerStamp.ActionName()} when under the effect of {PCT.Buffs.HammerTime.StatusName()}.", $"当受到{PCT.Buffs.HammerTime.StatusName()}效果时添加{PCT.HammerStamp.ActionName()}。"),
                KeyValuePair.Create($"Add {PCT.StarPrism.ActionName()} when under the effect of {PCT.Buffs.Starstruck.StatusName()}.", $"当受到{PCT.Buffs.Starstruck.StatusName()}效果时添加{PCT.StarPrism.ActionName()}。"),
                KeyValuePair.Create("Add Lucid Dreaming when below this MP", "当MP低于此值时添加醒梦"),
                KeyValuePair.Create("Both Single Target & AoE", "同时替换单体与群体技能"),
                KeyValuePair.Create($"Replaces both {PCT.FireInRed.ActionName()} & {PCT.FireIIinRed.ActionName()}", $"同时替换{PCT.FireInRed.ActionName()}和{PCT.FireIIinRed.ActionName()}"),
                KeyValuePair.Create("Single Target Only", "仅替换单体技能"),
                KeyValuePair.Create($"Replace only {PCT.FireInRed.ActionName()}", $"仅替换{PCT.FireInRed.ActionName()}"),
                KeyValuePair.Create("AoE Only", "仅替换群体技能"),
                KeyValuePair.Create($"Replace only {PCT.FireIIinRed.ActionName()}", $"仅替换{PCT.FireIIinRed.ActionName()}"),
                KeyValuePair.Create($"2nd GCD {PCT.StarryMuse.ActionName()}", $"第二个GCD使用{PCT.StarryMuse.ActionName()}"),
                KeyValuePair.Create($"3rd GCD {PCT.StarryMuse.ActionName()}", $"第三个GCD使用{PCT.StarryMuse.ActionName()}"),
            ];
        }
    }
}
