using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class PLDDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region PLD
                KeyValuePair.Create("Replaces Fast Blade with a full one-button single target rotation.", "用一键式单体循环替换Fast Blade。"),
                KeyValuePair.Create("Replaces Total Eclipse with a full one-button AoE rotation.", "用一键式AOE循环替换Total Eclipse。"),
                KeyValuePair.Create("Adds Fight or Flight to Advanced Mode.", "将Fight or Flight添加到高级模式。"),
                KeyValuePair.Create("- Uses after Royal Authority during opener.", "- 在起手式中，在Royal Authority之后使用。"),
                KeyValuePair.Create("- Afterward, on cooldown alongside Requiescat.", "- 之后，与Requiescat一起在冷却时使用。"),
                KeyValuePair.Create("- Target HP must be at or above:", "- 目标HP必须达到或超过："),
                KeyValuePair.Create("Adds Shield Lob to Advanced Mode.", "将Shield Lob添加到高级模式。"),
                KeyValuePair.Create("- Uses only while out of melee range.", "- 仅在近战范围外使用。"),
                KeyValuePair.Create("- Will not override better actions.", "- 不会覆盖更好的技能。"),
                KeyValuePair.Create("Adds Circle of Scorn to Advanced Mode.", "将厄运流转添加到高级模式。"),
                KeyValuePair.Create("- Uses only when in range of the target.", "- 仅在目标范围内使用。"),
                KeyValuePair.Create("- Prefers to use during Fight or Flight.", "- 优先在Fight or Flight期间使用。"),
                KeyValuePair.Create("Adds Spirits Within to Advanced Mode.", "将Spirits Within添加到高级模式。"),
                KeyValuePair.Create("Adds Goring Blade to Advanced Mode.", "将Goring Blade添加到高级模式。"),
                KeyValuePair.Create("- Prefers to use after Requiescat.", "- 优先在Requiescat之后使用。"),
                KeyValuePair.Create("Adds Holy Spirit to Advanced Mode.", "将Holy Spirit添加到高级模式。"),
                KeyValuePair.Create("- Uses only when under Divine Might.", "- 仅在Divine Might效果下使用。"),
                KeyValuePair.Create("- Will be prioritized if buff is expiring.", "- 如果增益即将结束，将优先使用。"),
                KeyValuePair.Create("Adds Requiescat to Advanced Mode.", "将Requiescat添加到高级模式。"),
                KeyValuePair.Create("- Uses after Fight or Flight.", "- 在Fight or Flight之后使用。"),
                KeyValuePair.Create("Adds Intervene to Advanced Mode.", "将Intervene添加到高级模式。"),
                KeyValuePair.Create("- Will not use during movement.", "- 不会在移动时使用。"),
                KeyValuePair.Create("- Amount of charges to keep:", "- 保留的充能次数："),
                KeyValuePair.Create("Adds the Atonement chain to Advanced Mode.", "将Atonement连击添加到高级模式。"),
                KeyValuePair.Create("Adds Confiteor to Advanced Mode.", "将Confiteor添加到高级模式。"),
                KeyValuePair.Create("- At lower levels, uses Holy Spirit instead.", "- 在较低等级时，使用Holy Spirit代替。"),
                KeyValuePair.Create("Adds Blade of Faith/Truth/Valor to Advanced Mode.", "将Blade of Faith/Blade of Truth/Blade of Valor添加到高级模式。"),
                KeyValuePair.Create("Adds Blade of Honor to Advanced Mode.", "将Blade of Honor添加到高级模式。"),
                KeyValuePair.Create("- Uses after Blade of Valor.", "- 在Blade of Valor之后使用。"),
                KeyValuePair.Create("Adds a minimum MP limit to Advanced Mode.", "为高级模式添加最低MP限制。"),
                KeyValuePair.Create("MP Reservation Option", "魔力保留选项"),
                KeyValuePair.Create("- This is not recommended in most cases.", "- 在大多数情况下不推荐使用。"),
                KeyValuePair.Create("- Player MP must remain at or above:", "- 玩家MP必须保持在或高于："),
                KeyValuePair.Create("Adds defensive actions to Advanced Mode.", "将防御技能添加到高级模式。"),
                KeyValuePair.Create("- Will not override offensive actions.", "- 不会覆盖进攻技能。"),
                KeyValuePair.Create("- Uses only when being targeted.", "- 仅在成为目标时使用。"),
                KeyValuePair.Create("Adds Sheltron.", "添加Sheltron。"),
                KeyValuePair.Create("- Required gauge threshold:", "- 所需量谱阈值："),
                KeyValuePair.Create("Adds Rampart.", "添加Rampart。"),
                KeyValuePair.Create("- Player HP must be under:", "- 玩家HP必须低于："),
                KeyValuePair.Create("Adds Sentinel.", "添加Sentinel。"),
                KeyValuePair.Create("Adds Hallowed Ground.", "添加Hallowed Ground。"),
                KeyValuePair.Create("Adds Low Blow or Shield Bash to the rotation when your target is casting, interruptible or not.", "当目标施法时，无论是否可打断，将Low Blow或Shield Bash加入循环。"),
                KeyValuePair.Create("- Uses on cooldown alongside Requiescat.", "- 与Requiescat一起在冷却时使用。"),
                KeyValuePair.Create("Adds Holy Circle to Advanced Mode.", "将Holy Circle添加到高级模式。"),
                KeyValuePair.Create("- At lower levels, uses Holy Circle instead.", "- 在较低等级时，使用Holy Circle代替。"),
                KeyValuePair.Create("Replaces Bulwark with an all-in-one mitigation button.", "用一键式减伤按钮替换Bulwark。"),
                KeyValuePair.Create("Gives max priority to Hallowed Ground when the Health percentage threshold is met.", "当HP百分比达到阈值时，优先使用Hallowed Ground。"),
                KeyValuePair.Create("Adds Sheltron to the one-button mitigation.", "将Sheltron添加到一键式减伤按钮。"),
                KeyValuePair.Create("Adds Divine Veil to the one-button mitigation.", "将Divine Veil添加到一键式减伤按钮。"),
                KeyValuePair.Create("Adds Sentinel / Guardian to the one-button mitigation.", "将Sentinel / Guardian添加到一键式减伤按钮。"),
                KeyValuePair.Create("Adds Hallowed Ground to the one-button mitigation.", "将Hallowed Ground添加到一键式减伤按钮。"),
                KeyValuePair.Create("Adds Clemency to the one-button mitigation.", "将Clemency添加到一键式减伤按钮。"),
                KeyValuePair.Create("Replaces Requiescat with all Requiescat-related actions.", "用所有与Requiescat相关的技能替换Requiescat。"),
                KeyValuePair.Create("- Prioritizes Confiteor and Blade actions when available.", "- 优先使用Confiteor和Blade技能。"),
                KeyValuePair.Create("- Uses Holy Spirit or Holy Circle when appropriate.", "- 在适当时使用Holy Spirit或Holy Circle。"),
                KeyValuePair.Create("Spirits Within / Circle of Scorn Feature", "Spirits Within/厄运流转特性"),
                KeyValuePair.Create("Replaces Spirits Within with Circle of Scorn when available.", "当可用时，用厄运流转替换Spirits Within。"),
                KeyValuePair.Create("Replaces Shield Lob with Holy Spirit when available.", "当可用时，用Holy Spirit替换Shield Lob。"),
                KeyValuePair.Create("- Must be under the effect of Divine Might or not moving.", "- 必须在Divine Might效果下或不移动时使用。"),
                KeyValuePair.Create("Uses Variant Spirit Dart whenever the debuff is not present on the target or about to expire.", "当目标没有debuff或debuff即将结束时，使用Variant Spirit Dart。"),
                KeyValuePair.Create("Uses Variant Cure when the player's HP falls below the set threshold.", "当玩家HP低于设定阈值时，使用Variant Cure。"),
                KeyValuePair.Create("Uses Variant Ultimatum on cooldown as long as the target is within range.", "只要目标在范围内，冷却时使用Variant Ultimatum。"),
                KeyValuePair.Create("Turns Royal Authority Combo into an all-in-one damage button.", "将Royal Authority连击变为一键式伤害按钮。"),
                KeyValuePair.Create("Adds Shield Smite to Burst Mode.", "将Shield Smite添加到爆发模式。"),
                KeyValuePair.Create("Adds Imperator to Burst Mode.", "将Imperator添加到爆发模式。"),
                KeyValuePair.Create("Adds Confiteor to Burst Mode.", "将Confiteor添加到爆发模式。"),
                KeyValuePair.Create("Adds Holy Spirit to Burst Mode.", "将Holy Spirit添加到爆发模式。"),
                KeyValuePair.Create("Adds Intervene to Burst Mode.", "将Intervene添加到爆发模式。"),
                KeyValuePair.Create("Adds Intervene to Burst Mode when in melee range.", "在近战范围内时，将Intervene添加到爆发模式。"),
                KeyValuePair.Create("Adds Phalanx Combo to Burst Mode.", "将Phalanx连击添加到爆发模式。"),
                KeyValuePair.Create("Adds Holy Sheltron to Burst Mode in melee range.", "在近战范围内时，将Holy Sheltron添加到爆发模式。"),
                KeyValuePair.Create("Attempts to hardcast Holy Spirit when not moving.", "在未移动时尝试硬读Holy Spirit"),
                KeyValuePair.Create("- Requires sufficient MP to cast.", "-需要足够的MP来施放。"),
                KeyValuePair.Create("Uses Intervene while within melee range.", "在近战范围内使用Intervene"),
                KeyValuePair.Create("- May result in minor movement.", "-可能会导致轻微移动。"),
                KeyValuePair.Create("Adds Spirits Within to the rotation.", "将Spirits Within添加到循环。"),
                KeyValuePair.Create("Adds Fight or Flight to the normal logic.", "将战逃反应添加到正常逻辑中。"),
                KeyValuePair.Create("Requires Requiescat to be ready.", "需要安魂祈祷准备就绪。"),
                KeyValuePair.Create("Normal Behavior", "普通模式"),
                KeyValuePair.Create("Add Drift Prevention", "预防循环轴偏移"),
                KeyValuePair.Create("Prevents Spirits Within and Circle of Scorn from drifting.", "防止深奥之灵和厄运流转在循环轴中产生偏移。"),
                KeyValuePair.Create("Actions must be used within 5 seconds of each other.", "技能必须在彼此 5 秒内使用。"),
                KeyValuePair.Create("Melee Range", "近战范围"),
                KeyValuePair.Create("Only uses Intervene when it would not result in movement.", "仅在不会导致移动时使用Intervene。"),
                KeyValuePair.Create("- Requires target to be within zero distance.", "-需要目标在零距离内。"),
                KeyValuePair.Create("No Movement", "无移动"),
                KeyValuePair.Create("Blade Chain", "信念之剑连击"),
                KeyValuePair.Create("Minimum MP", "最低魔力值"),
                KeyValuePair.Create("Shield Lob Only", "仅添加Shield Lob"),
                KeyValuePair.Create("Add Holy Spirit", "加入Holy Spirit"),
                KeyValuePair.Create("Circle of Scorn Option", "厄运流转"),
                KeyValuePair.Create("Oath Gauge", "忠义量谱"),
                #endregion
            ];
        }
    }
}
