using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class RDMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region RDMPvE
                KeyValuePair.Create("Replaces Jolt with a full one-button single target rotation.", "用一键单体循环替换摇荡。"),
                KeyValuePair.Create("To start the melee combo, you must be within melee range.", "要开始近战连击，你必须处于近战范围内。"),
                KeyValuePair.Create("Replaces Scatter with a full one-button AoE rotation.", "用一键AOE循环替换散碎。"),
                KeyValuePair.Create("**Must move into melee range before melee combo**", "**必须在近战连击前进入近战范围**"),
                KeyValuePair.Create("Replace Jolt with Verthunder and Veraero.", "用赤闪雷和赤疾风替换摇荡。"),
                KeyValuePair.Create("Add Acceleration when no Verfire/Verstone proc is available.", "在没有赤火炎/赤飞石触发时添加促进。"),
                KeyValuePair.Create("Add Acceleration when moving.", "在移动时添加促进。"),
                KeyValuePair.Create("Add Swiftcast when all Acceleration charges are used.", "在所有促进充能用完后添加即刻咏唱。"),
                KeyValuePair.Create("Replace Jolt with Verfire and Verstone.", "用赤火炎与赤飞石替换摇荡。"),
                KeyValuePair.Create("Weave the following oGCD actions.", "插入以下oGCD技能。"),
                KeyValuePair.Create("Add the Reposte combo.", "添加回刺连击。"),
                KeyValuePair.Create("**Must be in melee range or have Gap close with Corps-a-corps enabled**", "**必须处于近战范围或启用短兵相接进行接近**"),
                KeyValuePair.Create("Add Manafication and Embolden.", "添加魔元化和鼓励。"),
                KeyValuePair.Create("Hold both actions until you can perform a double melee combo.", "保留这两个技能直到你可以执行双近战连击。"),
                KeyValuePair.Create("Use Corp-a-corps when out of melee range and you have enough mana to start the melee combo.", "当你在近战范围外且有足够的魔力开始近战连击时，使用短兵相接。"),
                KeyValuePair.Create("Use Acceleration to unbalance mana prior to starting melee combo.", "在开始近战连击前使用促进来平衡魔力。"),
                KeyValuePair.Create("Add Verflare/Verholy and other finishing moves.", "添加赤核爆/赤神圣和其他终结技。"),
                KeyValuePair.Create("Adds melee combo to the rotation when mana is at a certain threshold.", "当魔力达到一定阈值时，将近战连击添加到循环中。"),
                KeyValuePair.Create("Add Acceleration into the AoE rotation.", "在AOE循环中添加促进。"),
                KeyValuePair.Create("Add Swiftcast when all Acceleration charges are used or when below level 50.", "在所有促进充能用完或低于50级时添加即刻咏唱。"),
                KeyValuePair.Create("Only use acceleration during weave windows.", "仅在插入窗口中使用促进。"),
                KeyValuePair.Create("Weave the following oGCD actions:", "插入以下oGCD技能："),
                KeyValuePair.Create("Use Moulinet when over 50/50 mana", "当魔力超过50/50时使用划圆斩。"),
                KeyValuePair.Create("**Must be in range of Moulinet**", "**必须在划圆斩的范围内**"),
                KeyValuePair.Create("Changes Swiftcast to Verraise when under the effect of Swiftcast or Dualcast.", "在即刻咏唱或连续咏唱效果下将即刻咏唱改为赤复活。"),
                KeyValuePair.Create("If Swiftcast is on cooldown, change to Vercure to proc Dualcast.", "如果即刻咏唱在冷却中，改为赤治疗以触发连续咏唱。"),
                KeyValuePair.Create("Replace Displacement with Corps-a-corps when out of range.", "当超出范围时用短兵相接替换移转。"),
                KeyValuePair.Create("Changes Embolden to Manafication when on cooldown.", "当鼓励在冷却中时改为魔元化。"),
                KeyValuePair.Create("Changes Magick Barrier to Addle when on cooldown.", "当抗死在冷却中时改为昏乱。"),
                KeyValuePair.Create("Disables Embolden when buffed by another Red Mage's Embolden by replacing it with Savage Blade.", "当受到另一个赤魔法师的鼓励增益时，禁用鼓励并用狂怒剑替换。"),
                KeyValuePair.Create("Disables Magick Barrier when buffed by another Red Mage's Magick Barrier by replacing it with Savage Blade.", "当受到另一个赤魔法师的抗死增益时，禁用抗死并用狂怒剑替换。"),
                KeyValuePair.Create("Replaces Jolts.", "替换摇荡/震荡/激荡。"),
                KeyValuePair.Create("Turn Swiftcast into Variant Raise whenever you have the Swiftcast or Dualcast buffs.", "当你有即刻咏唱或连续咏唱增益时，将即刻咏唱改为Variant Raise。"),
                KeyValuePair.Create("Replaces Vercure with Variant Cure.", "用Variant Cure替换赤治疗。"),
                #endregion
                
                #region RDMPvP
                KeyValuePair.Create("Turns Jolt III into an all-in-one button.", "将激荡变为一个多功能按钮。"),
                KeyValuePair.Create("- Will not attempt to cast Jolt III while moving by replacing it with Savage Blade.", "- 移动时不会尝试施放激荡，而是用Savage Blade替换。"),
                KeyValuePair.Create("Uses Riposte and Scorch when available.", "在可用时使用回刺和焦热。"),
                KeyValuePair.Create("- Requires melee range for Riposte Combo.", "- 需要近战范围以使用回刺连击。"),
                KeyValuePair.Create("Uses Resolution when available.", "在可用时使用决断。"),
                KeyValuePair.Create("- Requires target's HP to be under:", "- 需要目标的生命值低于："),
                KeyValuePair.Create("Uses Embolden when available.", "在可用时使用鼓励。"),
                KeyValuePair.Create("- Requires Enchanted Riposte to be available.", "- 需要魔回刺可用。"),
                KeyValuePair.Create("- Will use alongside Corps-a-corps if enabled.", "- 如果启用，将与短兵相接一起使用。"),
                KeyValuePair.Create("Uses Corps-a-corps when available.", "在可用时使用短兵相接。"),
                KeyValuePair.Create("Uses Displacement when available.", "在可用时使用移转。"),
                KeyValuePair.Create("- Will use when Scorch becomes available.", "- 当焦热可用时使用。"),
                KeyValuePair.Create("- Requires target to be within melee range.", "- 需要目标在近战范围内。"),
                KeyValuePair.Create("Uses Forte when available.", "在可用时使用剑身强部。"),
                KeyValuePair.Create("- Requires player's HP to be under:", "- 需要玩家的生命值低于："),
                KeyValuePair.Create("Adds Purify when affected by crowd control.", "当受到群体控制影响时添加Purify。"),
                KeyValuePair.Create("- Requires Purify to be available.", "- 需要Purify可用。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Melee combo overcap protection", "近战连击资源溢出保护"),
                KeyValuePair.Create("Gap close with Corps-a-corps Option", "使用Corps-a-corps接近敌人"),
                KeyValuePair.Create("Hold for Double Melee Combo Option [Lv.90]", "保留双近战连击选项 [Lv.90]"),
                KeyValuePair.Create("Unbalance Mana Option", "魔元失衡"),
                KeyValuePair.Create("Include Swiftcast Option", "即刻咏唱"),
                KeyValuePair.Create("Weave oGCD Damage Option", "插入能力技伤害"),
                KeyValuePair.Create("Changes which action this option will replace.", "更改此选项将替换的技能。"),
                KeyValuePair.Create("Pool one charge for manual use.", "保留一次充能以供手动使用。"),
                KeyValuePair.Create("Use only in melee range.", "仅在近战范围内使用。"),
                KeyValuePair.Create("Enforced Melee Check", "强制近战检测"),
                KeyValuePair.Create("Once the melee combo has started, don't switch away even if target is out of range.", "一旦近战连击开始，即使目标超出范围也不会切换。"),
                KeyValuePair.Create("Auto-Mode is enabled for this option.", "此选项已启用自动模式。"),
                KeyValuePair.Create($"{RDM.Zwerchhau.ActionName()} & {RDM.Redoublement.ActionName()} will be placed on {RDM.Jolt.ActionName()}", $"{RDM.Zwerchhau.ActionName()}和{RDM.Redoublement.ActionName()}将被放置在 {RDM.Jolt.ActionName()}上。"),
                KeyValuePair.Create("Uses Prefulgence when available.", "当光芒四射可用时自动使用"),
                KeyValuePair.Create("No Movement Option", "未移动时使用"),                
                KeyValuePair.Create("Movement Option", "移动检测"),
                KeyValuePair.Create("Uses Displacement only when not moving.", "仅在未移动时使用移转。"),
                KeyValuePair.Create("Uses Vice of Thorns when available.", "可用时使用荆棘环绕。"),
            ];
        }
    }
}
