using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class RPRDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region RPR
                KeyValuePair.Create("Replaces Slice with a full one-button single target rotation.", "用一键单体循环替换切割。"),
                KeyValuePair.Create("Replaces Spinning Scythe with a full one-button AoE rotation.", "用一键AOE循环替换旋转钐割。"),
                KeyValuePair.Create("Adds Arcane Circle to the rotation.", "将神秘环加入循环。"),
                KeyValuePair.Create("Adds Plentiful Harvest to the rotation.", "将大丰收加入循环。"),
                KeyValuePair.Create("Adds Shadow of Death to the rotation.", "将死亡之影加入循环。"),
                KeyValuePair.Create("Adds Soulsow to the rotation when out of combat and u dont have the buff.", "在战斗外且没有增益时，将播魂种加入循环。"),
                KeyValuePair.Create("Adds Soul Slice to the rotation.", "将灵魂切割加入循环。"),
                KeyValuePair.Create("Adds Bloodstalk to the rotation.", "将隐匿挥割加入循环。"),
                KeyValuePair.Create("Adds Gluttony to the rotation.", "将暴食加入循环。"),
                KeyValuePair.Create("Adds Gibbet and Gallows to the rotation.", "将绞决与缢杀加入循环。"),
                KeyValuePair.Create("Adds Enshroud to the rotation.", "将夜游魂衣加入循环。"),
                KeyValuePair.Create("Adds Void Reaping and Cross Reaping to the rotation.", "将虚无收割与交错收割加入循环。"),
                KeyValuePair.Create("(Disabling this may stop the one-button combo working during enshroud)", "（禁用此选项可能会停止在Enshroud期间的一键连击功能）"),
                KeyValuePair.Create("Adds Lemure's Slice to the rotation.", "将夜游魂切割加入循环。"),
                KeyValuePair.Create("Adds Communio to the rotation.", "将团契加入循环。"),
                KeyValuePair.Create("Adds Sacrificium to the rotation.", "将祭牲加入循环。"),
                KeyValuePair.Create("Adds Perfectio to the rotation.", "将完人加入循环。"),
                KeyValuePair.Create("Adds True North before Gibbet/Gallows when you are not in the correct position.", "当你不处于正确位置时，在绞决/缢杀前添加真北。"),
                KeyValuePair.Create("Hold True North for Gluttony Option", "为暴食保留真北"),
                KeyValuePair.Create("Will hold the last charge of True North for use with Gluttony, even when out of position for Gibbet/Gallows.", "即使不在Gibbet/Gallows的正确位置，也会保留True North的最后一层用于Gluttony。"),
                KeyValuePair.Create("Replaces the combo chain with Harpe when outside of melee range. Will not override Communio.", "在近战范围外时，用勾刃替换连击链。不会覆盖团契。"),
                KeyValuePair.Create("Adds Harvest Moon if available, when outside of melee range. Will not override Communio.", "在近战范围外时，如果可用，添加收获月。不会覆盖团契。"),
                KeyValuePair.Create("Adds Whorl of Death to the rotation.", "将死亡之涡加入循环。"),
                KeyValuePair.Create("Adds Soul Scythe to the rotation.", "将灵魂钐割加入循环。"),
                KeyValuePair.Create("Adds Grim Swathe to the rotation.", "将束缚挥割加入循环。"),
                KeyValuePair.Create("Adds Guillotine to the rotation.", "将断首加入循环。"),
                KeyValuePair.Create("Adds Grim Reaping to the rotation.", "将阴冷收割加入循环。"),
                KeyValuePair.Create("Adds Lemure's Scythe to the rotation.", "将夜游魂钐割加入循环。"),
                KeyValuePair.Create("Blood Stalk and Grim Swathe will turn into Gluttony when it is available.", "当暴食可用时，隐匿挥割与束缚挥割会转变为暴食。"),
                KeyValuePair.Create("Adds (Executioner's) Gibbet and Gallows on Blood Stalk.", "在隐匿挥割上添加绞决处刑（绞决）与缢杀处刑（缢杀）。"),
                KeyValuePair.Create("Adds (Executioner's) Guillotine on Grim Swathe.", "在束缚挥割上添加断首处刑（断首）。"),
                KeyValuePair.Create("Adds Enshroud combo (Void/Cross Reaping, Communio, Lemure's Slice, Sacrificium and Perfectio) on Blood Stalk and Grim Swathe.", "在隐匿挥割与束缚挥割上添加夜游魂衣连击（虚无收割/交错收割、团契、夜游魂切割、祭牲与完人）。"),
                KeyValuePair.Create("Adds Enshroud, Lemure's Slice and Sacrificium.", "添加夜游魂衣、夜游魂切割与祭牲。"),
                KeyValuePair.Create("Adds only Sacrificium on Blood Stalk and Grim Swathe while enshrouded.", "在夜游魂衣期间，仅在隐匿挥割与束缚挥割上添加祭牲。"),
                KeyValuePair.Create("Adds True North when under Gluttony and if Gibbet/Gallows options are selected to replace those skills.", "在暴食下且选择了替换绞决/缢杀的选项时，添加真北。"),
                KeyValuePair.Create("Adds Soulsow to the skills selected below when out of combat. ", "在战斗外时，将播魂种添加到下方选择的技能中。"),
                KeyValuePair.Create("Will also add Soulsow to Harpe when in combat and no target is selected.", "在战斗中且没有选择目标时，也会将播魂种添加到勾刃。"),
                KeyValuePair.Create("Adds Soulsow to Harpe during combat when no target is selected.", "在战斗中且没有选择目标时，将播魂种添加到勾刃。"),
                KeyValuePair.Create("Replaces Arcane Circle with Plentiful Harvest when you have stacks of Immortal Sacrifice.", "当你有死亡祭品层数时，用大丰收替换神秘环。"),
                KeyValuePair.Create("Changes both Hell's Ingress and Hell's Egress turn into Regress when Threshold is active.", "当回退预备激活时，将地狱入境与地狱出境都转变为回退。"),
                KeyValuePair.Create("Turns Enshroud into Gibbet/Gallows to protect Soul Reaver waste.", "将夜游魂衣转变为绞决/缢杀以防止妖异之镰浪费。"),
                KeyValuePair.Create("Turns Enshroud to Communio and Perfectio when available to use.", "当可用时，将夜游魂衣转变为团契与完人。"),
                KeyValuePair.Create("Adds Communio to Gibbet/Gallows and Guillotine.", "将团契添加到绞决/缢杀与断首。"),
                KeyValuePair.Create("Adds Lemure's Slice to Gibbet/Gallows and Lemure's Scythe to Guillotine.", "将夜游魂切割添加到绞决/缢杀，将夜游魂钐割添加到断首。"),
                KeyValuePair.Create("Turns Slice Combo into an all-in-one damage button.", "将切割连击转变为全合一伤害按钮。"),
                KeyValuePair.Create("Adds Soul Slice to the main combo.", "将灵魂切割加入主连击。"),
                KeyValuePair.Create("Add's Grim Swathe onto the main combo on cd", "将束缚挥割加入主连击并在冷却时使用。"),
                KeyValuePair.Create("Adds Death Warrant onto the main combo when Plentiful Harvest is ready to use, or when Plentiful Harvest's cooldown is longer than Death Warrant's.", "当大丰收准备就绪时，或当大丰收的冷却时间比斩首令长时，将斩首令加入主连击。"),
                KeyValuePair.Create("Respects Immortal Sacrifice Pooling Option.", "尊重死亡祭品的积攒选项。"),
                KeyValuePair.Create("Pools stacks of Immortal Sacrifice before using Plentiful Harvest.", "在使用大丰收之前积攒死亡祭品层数。"),
                KeyValuePair.Create("Also holds Plentiful Harvest if Death Warrant is on cooldown.", "如果斩首令在冷却中，也会保留大丰收。"),
                KeyValuePair.Create("Set the value to 3 or below to use Plentiful Harvest as soon as it's available.", "将值设置为3或以下以在大丰收可用时立即使用。"),
                KeyValuePair.Create("Adds Lemure's Slice to the main combo during the Enshroud burst phase.", "在Enshroud爆发阶段将夜游魂钐割加入主连击。"),
                KeyValuePair.Create("Contains burst options.", "包含爆发选项。"),
                KeyValuePair.Create("Enshrouded Death Warrant Option", $"{RPRPvP.Buffs.Enshrouded.StatusName()}Death Warrant"),
                KeyValuePair.Create("Enshrouded Burst Option", $"{RPRPvP.Buffs.Enshrouded.StatusName()}爆发"),
                KeyValuePair.Create("Adds Death Warrant onto the main combo during the Enshroud burst when available.", "在Enshroud爆发期间，当可用时将Death Warrant加入主连击。"),
                KeyValuePair.Create("Adds Communio onto the main combo when you have 1 stack of Enshroud remaining.", "当你剩余1层Enshroud时，将Communio加入主连击。"),
                KeyValuePair.Create("Will not trigger if you are moving.", "如果你在移动，则不会触发。"),
                KeyValuePair.Create("Adds Harvest Moon onto the main combo when you're out of melee range, the GCD is not rolling and it's available for use. Will also throw it when the enemy is under 12k health for execute", "当你在近战范围外、GCD未滚动且可用时，将Harvest Moon加入主连击。当敌人血量低于12k时也会投掷以执行斩杀。"),
                KeyValuePair.Create("Adds Arcane Crest to the main combo when under the set HP perecentage.", "当HP低于设定百分比时，将Arcane Crest加入主连击。"),
                KeyValuePair.Create("Set a HP% Threshold for when SoD will not be automatically applied to the target.", "目标生命百分比达到此值时不会自动使用死亡之影。"),
                KeyValuePair.Create("Set a HP% Threshold for when WoD will not be automatically applied to the target.", "目标生命百分比达到此值不会自动使用死亡之涡。"),
                #endregion
                
                // Manually added
                KeyValuePair.Create("Lemure's Slice/Scythe Option", "Lemure's Slice/Lemure's Scythe"),
                KeyValuePair.Create("Void/Cross Reaping Option", "Void Reaping/Cross Reaping"),
                KeyValuePair.Create("Arcane Circle Harvest Feature", "Arcane Circle大丰收特性"),

                #region RPR
                KeyValuePair.Create("Set a value of Immortal Sacrifice Stacks to hold for burst.", "设置保留的死亡祭品层数以用于爆发"),
                KeyValuePair.Create("Set a HP percentage value.", "设置血量百分比阈值。"),
                KeyValuePair.Create("Caps at 90 to prevent waste.", "最高90%以避免浪费")
                #endregion
            ];
        }
    }
}
