using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class RPRDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region RPR
                KeyValuePair.Create("Replaces Slice with a full one-button single target rotation.", "用一键单体循环替换Slice。"),
                KeyValuePair.Create("Replaces Spinning Scythe with a full one-button AoE rotation.", "用一键AOE循环替换Spinning Scythe。"),
                KeyValuePair.Create("Adds Arcane Circle to the rotation.", "将Arcane Circle加入循环。"),
                KeyValuePair.Create("Adds Plentiful Harvest to the rotation.", "将Plentiful Harvest加入循环。"),
                KeyValuePair.Create("Adds Shadow of Death to the rotation.", "将Shadow of Death加入循环。"),
                KeyValuePair.Create("Adds Soulsow to the rotation when out of combat and u dont have the buff.", "在战斗外且没有增益时，将Soulsow加入循环。"),
                KeyValuePair.Create("Adds Soul Slice to the rotation.", "将Soul Slice加入循环。"),
                KeyValuePair.Create("Adds Bloodstalk to the rotation.", "将Bloodstalk加入循环。"),
                KeyValuePair.Create("Adds Gluttony to the rotation.", "将Gluttony加入循环。"),
                KeyValuePair.Create("Adds Gibbet and Gallows to the rotation.", "将Gibbet和Gallows加入循环。"),
                KeyValuePair.Create("Adds Enshroud to the rotation.", "将Enshroud加入循环。"),
                KeyValuePair.Create("Adds Void Reaping and Cross Reaping to the rotation.", "将Void Reaping和Cross Reaping加入循环。"),
                KeyValuePair.Create("(Disabling this may stop the one-button combo working during enshroud)", "（禁用此选项可能会停止在Enshroud期间的一键连击功能）"),
                KeyValuePair.Create("Adds Lemure's Slice to the rotation.", "将Lemure's Slice加入循环。"),
                KeyValuePair.Create("Adds Communio to the rotation.", "将Communio加入循环。"),
                KeyValuePair.Create("Adds Sacrificium to the rotation.", "将Sacrificium加入循环。"),
                KeyValuePair.Create("Adds Perfectio to the rotation.", "将Perfectio加入循环。"),
                KeyValuePair.Create("Adds True North before Gibbet/Gallows when you are not in the correct position.", "当你不处于正确位置时，在Gibbet/Gallows前添加True North。"),
                KeyValuePair.Create("Hold True North for Gluttony Option", "为暴食保留真北"),
                KeyValuePair.Create("Will hold the last charge of True North for use with Gluttony, even when out of position for Gibbet/Gallows.", "即使不在Gibbet/Gallows的正确位置，也会保留True North的最后一层用于Gluttony。"),
                KeyValuePair.Create("Replaces the combo chain with Harpe when outside of melee range. Will not override Communio.", "在近战范围外时，用Harpe替换连击链。不会覆盖Communio。"),
                KeyValuePair.Create("Adds Harvest Moon if available, when outside of melee range. Will not override Communio.", "在近战范围外时，如果可用，添加Harvest Moon。不会覆盖Communio。"),
                KeyValuePair.Create("Adds Whorl of Death to the rotation.", "将Whorl of Death加入循环。"),
                KeyValuePair.Create("Adds Soul Scythe to the rotation.", "将Soul Scythe加入循环。"),
                KeyValuePair.Create("Adds Grim Swathe to the rotation.", "将Grim Swathe加入循环。"),
                KeyValuePair.Create("Adds Guillotine to the rotation.", "将Guillotine加入循环。"),
                KeyValuePair.Create("Adds Grim Reaping to the rotation.", "将Grim Reaping加入循环。"),
                KeyValuePair.Create("Adds Lemure's Scythe to the rotation.", "将Lemure's Scythe加入循环。"),
                KeyValuePair.Create("Blood Stalk and Grim Swathe will turn into Gluttony when it is available.", "当Gluttony可用时，Blood Stalk和Grim Swathe会转变为Gluttony。"),
                KeyValuePair.Create("Adds (Executioner's) Gibbet and Gallows on Blood Stalk.", "在Blood Stalk上添加Executioner's Gibbet（Gibbet）和Executioner's Gallows（Gallows）。"),
                KeyValuePair.Create("Adds (Executioner's) Guillotine on Grim Swathe.", "在Grim Swathe上添加Executioner's Guillotine（Guillotine）。"),
                KeyValuePair.Create("Adds Enshroud combo (Void/Cross Reaping, Communio, Lemure's Slice, Sacrificium and Perfectio) on Blood Stalk and Grim Swathe.", "在Blood Stalk和Grim Swathe上添加Enshroud连击（Void Reaping/Cross Reaping、Communio、Lemure's Slice、Sacrificium和Perfectio）。"),
                KeyValuePair.Create("Adds Enshroud, Lemure's Slice and Sacrificium.", "添加Enshroud、Lemure's Slice和Sacrificium。"),
                KeyValuePair.Create("Adds only Sacrificium on Blood Stalk and Grim Swathe while enshrouded.", "在Enshroud期间，仅在Blood Stalk和Grim Swathe上添加Sacrificium。"),
                KeyValuePair.Create("Adds True North when under Gluttony and if Gibbet/Gallows options are selected to replace those skills.", "在Gluttony下且选择了替换Gibbet/Gallows的选项时，添加True North。"),
                KeyValuePair.Create("Adds Soulsow to the skills selected below when out of combat. ", "在战斗外时，将Soulsow添加到下方选择的技能中。"),
                KeyValuePair.Create("Will also add Soulsow to Harpe when in combat and no target is selected.", "在战斗中且没有选择目标时，也会将Soulsow添加到Harpe。"),
                KeyValuePair.Create("Adds Soulsow to Harpe during combat when no target is selected.", "在战斗中且没有选择目标时，将Soulsow添加到Harpe。"),
                KeyValuePair.Create("Replaces Arcane Circle with Plentiful Harvest when you have stacks of Immortal Sacrifice.", "当你有Immortal Sacrifice层数时，用Plentiful Harvest替换Arcane Circle。"),
                KeyValuePair.Create("Changes both Hell's Ingress and Hell's Egress turn into Regress when Threshold is active.", "当Threshold激活时，将Hell's Ingress和Hell's Egress都转变为Regress。"),
                KeyValuePair.Create("Turns Enshroud into Gibbet/Gallows to protect Soul Reaver waste.", "将Enshroud转变为Gibbet/Gallows以防止Soul Reaver浪费。"),
                KeyValuePair.Create("Turns Enshroud to Communio and Perfectio when available to use.", "当可用时，将Enshroud转变为Communio和Perfectio。"),
                KeyValuePair.Create("Adds Communio to Gibbet/Gallows and Guillotine.", "将Communio添加到Gibbet/Gallows和Guillotine。"),
                KeyValuePair.Create("Adds Lemure's Slice to Gibbet/Gallows and Lemure's Scythe to Guillotine.", "将Lemure's Slice添加到Gibbet/Gallows，将Lemure's Scythe添加到Guillotine。"),
                KeyValuePair.Create("Turns Slice Combo into an all-in-one damage button.", "将Slice连击转变为全合一伤害按钮。"),
                KeyValuePair.Create("Adds Soul Slice to the main combo.", "将Soul Slice加入主连击。"),
                KeyValuePair.Create("Add's Grim Swathe onto the main combo on cd", "将Grim Swathe加入主连击并在冷却时使用。"),
                KeyValuePair.Create("Adds Death Warrant onto the main combo when Plentiful Harvest is ready to use, or when Plentiful Harvest's cooldown is longer than Death Warrant's.", "当Plentiful Harvest准备就绪时，或当Plentiful Harvest的冷却时间比Death Warrant长时，将Death Warrant加入主连击。"),
                KeyValuePair.Create("Respects Immortal Sacrifice Pooling Option.", "尊重Immortal Sacrifice的积攒选项。"),
                KeyValuePair.Create("Pools stacks of Immortal Sacrifice before using Plentiful Harvest.", "在使用Plentiful Harvest之前积攒Immortal Sacrifice层数。"),
                KeyValuePair.Create("Also holds Plentiful Harvest if Death Warrant is on cooldown.", "如果Death Warrant在冷却中，也会保留Plentiful Harvest。"),
                KeyValuePair.Create("Set the value to 3 or below to use Plentiful Harvest as soon as it's available.", "将值设置为3或以下以在Plentiful Harvest可用时立即使用。"),
                KeyValuePair.Create("Adds Lemure's Slice to the main combo during the Enshroud burst phase.", "在Enshroud爆发阶段将夜游魂钐割加入主连击。"),
                KeyValuePair.Create("Contains burst options.", "包含爆发选项。"),
                KeyValuePair.Create("Enshrouded Death Warrant Option", $"{RPRPvP.Buffs.Enshrouded.StatusName()}Death Warrant"),
                KeyValuePair.Create("Enshrouded Burst Option", $"{RPRPvP.Buffs.Enshrouded.StatusName()}爆发"),
                KeyValuePair.Create("Adds Death Warrant onto the main combo during the Enshroud burst when available.", "在Enshroud爆发期间，当可用时将Death Warrant加入主连击。"),
                KeyValuePair.Create("Adds Communio onto the main combo when you have 1 stack of Enshroud remaining.", "当你剩余1层Enshroud时，将Communio加入主连击。"),
                KeyValuePair.Create("Will not trigger if you are moving.", "如果你在移动，则不会触发。"),
                KeyValuePair.Create("Adds Harvest Moon onto the main combo when you're out of melee range, the GCD is not rolling and it's available for use. Will also throw it when the enemy is under 12k health for execute", "当你在近战范围外、GCD未滚动且可用时，将Harvest Moon加入主连击。当敌人血量低于12k时也会投掷以执行斩杀。"),
                KeyValuePair.Create("Adds Arcane Crest to the main combo when under the set HP perecentage.", "当HP低于设定百分比时，将Arcane Crest加入主连击。"),
                KeyValuePair.Create("Seconds remaining before refreshing Death's Design.", "DoT剩多少秒时续死亡烙印。"),
                KeyValuePair.Create("Set a HP% Threshold for when SoD will not be automatically applied to the target.", "目标生命百分比达到此值时不会自动使用死亡之影。"),
                KeyValuePair.Create("Set a HP% Threshold for when WoD will not be automatically applied to the target.", "目标生命百分比达到此值不会自动使用死亡之涡。"),
                #endregion
                
                // Manually added
                KeyValuePair.Create("Lemure's Slice/Scythe Option", "Lemure's Slice/Lemure's Scythe"),
                KeyValuePair.Create("Void/Cross Reaping Option", "Void Reaping/Cross Reaping"),
                KeyValuePair.Create("Arcane Circle Harvest Feature", "Arcane Circle大丰收特性"),
            ];
        }
    }
}
