using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SAMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region SAMPvE
                KeyValuePair.Create("Replaces Hakaze with a full one-button single target rotation.", "用一键单体连击替换Hakaze。"),
                KeyValuePair.Create("Replaces Fuga with a full one-button AoE rotation.", "用一键AOE连击替换Fuga。"),
                KeyValuePair.Create("Adds Yukikaze combo to the rotation.", "将Yukikaze连击添加到连击中。"),
                KeyValuePair.Create("Adds Kasha combo to the rotation.", "将Kasha连击添加到连击中。"),
                KeyValuePair.Create("Adds Shinten to the rotation", "将Shinten添加到连击中。"),
                KeyValuePair.Create("CDs on Main Combo", "有冷却时间的技能"),
                KeyValuePair.Create("Collection of CD features on main combo.", "主连击上的CD功能集合。"),
                KeyValuePair.Create("Adds Meikyo Shisui to the rotation.", "将Meikyo Shisui添加到连击中。"),
                KeyValuePair.Create(" Dynamically changes usage for 2.14 or 2.08 GCD", "动态调整2.14或2.08GCD的使用。"),
                KeyValuePair.Create("Adds Ikishoten when at or below 50 Kenki.", "当Kenki为50或以下时添加Ikishoten。"),
                KeyValuePair.Create("Will dump Kenki at 10 seconds left to allow Ikishoten to be used.", "在剩余10秒时消耗Kenki以允许使用Ikishoten。"),
                KeyValuePair.Create("Adds Shoha when you have three meditation stacks.", "当你有三层剑压时添加Shoha。"),
                KeyValuePair.Create("Adds Senei to the rotation.", "将Senei添加到连击中。"),
                KeyValuePair.Create("Adds Guren to the rotation if Senei is not unlocked.", "如果Senei未解锁，则添加Guren到连击中。"),
                KeyValuePair.Create("Adds Midare: Setsugekka, Higanbana, and Kaeshi: Setsugekka to the rotation.", "将Midare: Setsugekka、Higanbana和Kaeshi: Setsugekka添加到连击中。"),
                KeyValuePair.Create("Adds Midare: Setsugekka, Higanbana, and Kaeshi: Setsugekka when you're not moving.", "当你不移动时添加Midare: Setsugekka、Higanbana和Kaeshi: Setsugekka。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri to the rotation.", "将Ogi Namikiri和Kaeshi: Namikiri添加到连击中。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri when you're not moving.", "当你不移动时添加Ogi Namikiri和Kaeshi:Namikiri。"),
                KeyValuePair.Create("Adds Zanshin when ready to the rotation.", "当准备好时将Zanshin添加到连击中。"),
                KeyValuePair.Create("Adds True North if Meikyo Shisui's buff is on you.", "如果Meikyo Shisui的buff在你身上，则添加True North。"),
                KeyValuePair.Create("Adds Enpi to the rotation when you are out of range.", "当你超出近战范围时将Enpi添加到连击中。"),
                KeyValuePair.Create("Adds Bloodbath and Second Wind to the combo, using them when below the HP Percentage threshold.", "将Bloodbath和Second Wind添加到连击中，在HP百分比低于阈值时使用它们。"),
                KeyValuePair.Create("Adds Oka combo to the rotation.", "将Oka连击添加到连击中。"),
                KeyValuePair.Create("Adds Kyuten to the rotation.", "将Kyuten添加到连击中。"),
                KeyValuePair.Create("Adds Shoha when you have 3 meditation stacks.", "当你有三层剑压时添加Shoha。"),
                KeyValuePair.Create("Adds Guren to the rotation.", "将Guren添加到连击中。"),
                KeyValuePair.Create("Adds Hagakure to the rotation when there are three Sen.", "当集齐三闪时将Hagakure添加到连击中。"),
                KeyValuePair.Create("Adds Tenka Goken, Midare: Setsugekka, and Kaeshi: Goken when ready and when you're not moving to the rotation.", "当准备好且不移动时将Tenka Goken、Midare: Setsugekka和Kaeshi: Goken添加到连击中。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri when ready and when you're not moving to the rotation.", "当准备好且不移动时将Ogi Namikiri和Kaeshi: Namikiri添加到连击中。"),
                KeyValuePair.Create("Adds Zanshin to the rotation.", "将Zanshin添加到连击中。"),
                KeyValuePair.Create("Replace Yukikaze with its combo chain.", "用其连击链替换Yukikaze。"),
                KeyValuePair.Create("Replace Kasha with its combo chain.", "用其连击链替换Kasha。"),
                KeyValuePair.Create("Replace Gekko with its combo chain.", "用其连击链替换Gekko。"),
                KeyValuePair.Create("Replace Oka with its combo chain.", "用其连击链替换Oka。"),
                KeyValuePair.Create("Replace Mangetsu with its combo chain.", "用其连击链替换Mangetsu。"),
                KeyValuePair.Create("Replace Meikyo Shisui with Gekko, Kasha, and Yukikaze depending on what is needed.", "根据需要将Meikyo Shisui替换为Gekko、Kasha和Yukikaze。"),
                KeyValuePair.Create("Replaces Meikyo Shisui with Savage Blade when you already have Meikyo Shisui active.", "当你已经激活Meikyo Shisui时，用Savage Blade替换Meikyo Shisui。"),
                KeyValuePair.Create("Collection of Iaijutsu Features.", "Iaijutsu功能集合。"),
                KeyValuePair.Create("Replace Iaijutsu with Tsubame-gaeshi when appropriate.", "在适当时用Tsubame-gaeshi替换Iaijutsu。"),
                KeyValuePair.Create("Replace Iaijutsu with Shoha when meditation is 3.", "当剑压满时用Shoha替换Iaijutsu。"),
                KeyValuePair.Create("Replace Iaijutsu with Ogi Namikiri and Kaeshi: Namikiri when buffed with Ogi Namikiri Ready.", "当有Ogi Namikiri预备时用Ogi Namikiri和Kaeshi: Namikiri替换Iaijutsu。"),
                KeyValuePair.Create("Collection of Hissatsu: Shinten Features.", "Hissatsu: Shinten功能集合。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Shoha when Meditation is full.", "当剑压满时用Shoha替换Hissatsu: Shinten。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Senei when its cooldown is up.", "当冷却结束时用Senei替换Hissatsu: Shinten。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Zanshin when usable.", "当可用时用Zanshin替换Hissatsu: Shinten。"),
                KeyValuePair.Create("Collection of Hissatsu: Kyuten Features.", "Hissatsu: Kyuten功能集合。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Shoha when Meditation is full.", "当剑压满时用Shoha替换Hissatsu: Kyuten。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Guren when its cooldown is up.", "当冷却结束时用Guren替换Hissatsu: Kyuten。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Zanshin when usable.", "当可用时用Zanshin替换Hissatsu: Kyuten。"),
                KeyValuePair.Create("Collection of Ikishoten Features.", "Ikishoten功能集合。"),
                KeyValuePair.Create("Replace Ikishoten with Ogi Namikiri & Kaeshi Namikiri when available.", "当可用时用Ogi Namikiri和Kaeshi Namikiri替换Ikishoten。"),
                KeyValuePair.Create("Replace Ikishoten with Shoha when Meditation is full before Ogi Namikiri.", "在Ogi Namikiri之前当剑压满时用Shoha替换Ikishoten。"),
                KeyValuePair.Create("Hissatsu: Gyoten becomes Yaten/Gyoten depending on the distance from your target.", "Hissatsu: Gyoten根据与目标的距离变为Yaten/Gyoten。"),
                // Ohter Descriptions
                KeyValuePair.Create("Set the Kenki overcap amount for ST combos.", "设置单目标连击的剑气溢出量。"),
                KeyValuePair.Create("Set the Kenki overcap amount for AOE combos.", "设置多目标连击的剑气溢出量。"),
                KeyValuePair.Create("Spends Kenki when at the set value or above.", "在剑气达到设定值或以上时消耗剑气。"),
                KeyValuePair.Create("Sens Feature", "三闪特性"),
                KeyValuePair.Create("Delay from first 明镜止水 to next step. (seconds)", "从第一次明镜止水到下一步的延迟时间（秒）"),
                KeyValuePair.Create("HP percent threshold to not save Kenki", "生命值百分比阈值低于此值时不保留剑气"),
                KeyValuePair.Create("Delay is enforced by replacing your button with Savage Blade.", "通过将你的按钮替换为Savage Blade来强制执行延迟。"),
                KeyValuePair.Create("Stop using Higanbana on targets below this HP % (0% = always use).", "目标生命值百分比低于此值时停用彼岸花（0 = 总是使用）"),
                #endregion
                
                #region SAMPvP
                KeyValuePair.Create("Turns Kasha Combo into an all-in-one button.", "将Kasha连击整合为一个按钮。"),
                KeyValuePair.Create("- Will not use actions with cast time while moving.", "- 移动时不会使用有施法时间的技能。"),
                KeyValuePair.Create("Uses Meikyo Shisui when available.", "在可用时使用Meikyo Shisui。"),
                KeyValuePair.Create("- Requires target to be in melee range.", "- 需要目标在近战范围内。"),
                KeyValuePair.Create("Uses Chiten when available.", "在可用时使用Chiten。"),
                KeyValuePair.Create("- Will not use outside combat.", "- 不会在战斗外使用。"),
                KeyValuePair.Create("Uses Mineuchi when available.", "在可用时使用Mineuchi。"),
                KeyValuePair.Create("Uses Soten when available.", "在可用时使用Soten。"),
                KeyValuePair.Create("- Will not use if already under Kaiten's effect.", "- 如果已经处于Kaiten效果下则不会使用。"),
                KeyValuePair.Create("Uses Zantetsuken when available.", "在可用时使用Zantetsuken。"),
                KeyValuePair.Create("- Will not use if target is invulnerable.", "- 如果目标处于无敌状态则不会使用。"),
                KeyValuePair.Create("- Requires target to have player's Kuzushi.", "- 需要目标带有玩家的Kuzushi效果。"),
                #endregion                
            ];
        }
    }
}
