using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SAMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region SAMPvE
                KeyValuePair.Create("Replaces Hakaze with a full one-button single target rotation.", "用一键单体连击替换刃风。"),
                KeyValuePair.Create("Replaces Fuga with a full one-button AoE rotation.", "用一键AOE连击替换风雅。"),
                KeyValuePair.Create("Adds Yukikaze combo to the rotation.", "将雪风连击添加到连击中。"),
                KeyValuePair.Create("Adds Kasha combo to the rotation.", "将花车连击添加到连击中。"),
                KeyValuePair.Create("Adds Shinten to the rotation", "将必杀剑·震天添加到连击中。"),
                KeyValuePair.Create("CDs on Main Combo", "有冷却时间的技能"),
                KeyValuePair.Create("Collection of CD features on main combo.", "主连击上的CD功能集合。"),
                KeyValuePair.Create("Adds Meikyo Shisui to the rotation.", "将明镜止水添加到连击中。"),
                KeyValuePair.Create(" Dynamically changes usage for 2.14 or 2.08 GCD", "动态调整2.14或2.08GCD的使用。"),
                KeyValuePair.Create("Adds Ikishoten when at or below 50 Kenki.", "当剑气为50或以下时添加意气冲天。"),
                KeyValuePair.Create("Will dump Kenki at 10 seconds left to allow Ikishoten to be used.", "在剩余10秒时消耗Kenki以允许使用Ikishoten。"),
                KeyValuePair.Create("Adds Shoha when you have three meditation stacks.", "当你有三层剑压时添加照破。"),
                KeyValuePair.Create("Adds Senei to the rotation.", "将必杀剑·闪影添加到连击中。"),
                KeyValuePair.Create("Adds Guren to the rotation if Senei is not unlocked.", "如果未解锁必杀剑·闪影，则添加必杀剑·红莲到连击中。"),
                KeyValuePair.Create("Adds Midare: Setsugekka, Higanbana, and Kaeshi: Setsugekka to the rotation.", "将纷乱雪月花、彼岸花和回返雪月花添加到连击中。"),
                KeyValuePair.Create("Adds Midare: Setsugekka, Higanbana, and Kaeshi: Setsugekka when you're not moving.", "当你不移动时添加纷乱雪月花、彼岸花和回返雪月花。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri to the rotation.", "将奥义斩浪和回返斩浪添加到连击中。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri when you're not moving.", "当你不移动时添加奥义斩浪和回返斩浪。"),
                KeyValuePair.Create("Adds Zanshin when ready to the rotation.", "当准备好时将残心添加到连击中。"),
                KeyValuePair.Create("Adds True North if Meikyo Shisui's buff is on you.", "如果明镜止水的增益在你身上，则添加True North。"),
                KeyValuePair.Create("Adds Enpi to the rotation when you are out of range.", "当你超出近战范围时将燕飞添加到连击中。"),
                KeyValuePair.Create("Adds Bloodbath and Second Wind to the combo, using them when below the HP Percentage threshold.", "将Bloodbath和内丹添加到连击中，在HP百分比低于阈值时使用它们。"),
                KeyValuePair.Create("Adds Oka combo to the rotation.", "将樱花连击添加到连击中。"),
                KeyValuePair.Create("Adds Kyuten to the rotation.", "将必杀剑·九天添加到连击中。"),
                KeyValuePair.Create("Adds Shoha when you have 3 meditation stacks.", "当你有三层剑压时添加照破。"),
                KeyValuePair.Create("Adds Guren to the rotation.", "将必杀剑·红莲添加到连击中。"),
                KeyValuePair.Create("Adds Hagakure to the rotation when there are three Sen.", "当集齐三闪时将叶隐添加到连击中。"),
                KeyValuePair.Create("Adds Tenka Goken, Midare: Setsugekka, and Kaeshi: Goken when ready and when you're not moving to the rotation.", "当准备好且不移动时将天下五剑、纷乱雪月花和回返五剑添加到连击中。"),
                KeyValuePair.Create("Adds Ogi Namikiri and Kaeshi: Namikiri when ready and when you're not moving to the rotation.", "当准备好且不移动时将奥义斩浪和回返斩浪添加到连击中。"),
                KeyValuePair.Create("Adds Zanshin to the rotation.", "将残心添加到连击中。"),
                KeyValuePair.Create("Replace Yukikaze with its combo chain.", "用其连击链替换雪风。"),
                KeyValuePair.Create("Replace Kasha with its combo chain.", "用其连击链替换花车。"),
                KeyValuePair.Create("Replace Gekko with its combo chain.", "用其连击链替换月光。"),
                KeyValuePair.Create("Replace Oka with its combo chain.", "用其连击链替换樱花。"),
                KeyValuePair.Create("Replace Mangetsu with its combo chain.", "用其连击链替换满月。"),
                KeyValuePair.Create("Replace Meikyo Shisui with Gekko, Kasha, and Yukikaze depending on what is needed.", "根据需要将明镜止水替换为月光、花车和雪风。"),
                KeyValuePair.Create("Replaces Meikyo Shisui with Savage Blade when you already have Meikyo Shisui active.", "当你已经激活明镜止水时，用狂怒剑替换明镜止水。"),
                KeyValuePair.Create("Collection of Iaijutsu Features.", "居合术功能集合。"),
                KeyValuePair.Create("Replace Iaijutsu with Tsubame-gaeshi when appropriate.", "在适当时用燕回返替换居合术。"),
                KeyValuePair.Create("Replace Iaijutsu with Shoha when meditation is 3.", "当剑压满时用照破替换居合术。"),
                KeyValuePair.Create("Replace Iaijutsu with Ogi Namikiri and Kaeshi: Namikiri when buffed with Ogi Namikiri Ready.", "当有奥义斩浪预备时用奥义斩浪和回返斩浪替换居合术。"),
                KeyValuePair.Create("Collection of Hissatsu: Shinten Features.", "必杀剑·震天功能集合。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Shoha when Meditation is full.", "当剑压满时用照破替换必杀剑·震天。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Senei when its cooldown is up.", "当冷却结束时用必杀剑·闪影替换必杀剑·震天。"),
                KeyValuePair.Create("Replace Hissatsu: Shinten with Zanshin when usable.", "当可用时用残心替换必杀剑·震天。"),
                KeyValuePair.Create("Collection of Hissatsu: Kyuten Features.", "必杀剑·九天功能集合。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Shoha when Meditation is full.", "当剑压满时用照破替换必杀剑·九天。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Guren when its cooldown is up.", "当冷却结束时用必杀剑·红莲替换必杀剑·九天。"),
                KeyValuePair.Create("Replace Hissatsu: Kyuten with Zanshin when usable.", "当可用时用残心替换必杀剑·九天。"),
                KeyValuePair.Create("Collection of Ikishoten Features.", "意气冲天功能集合。"),
                KeyValuePair.Create("Replace Ikishoten with Ogi Namikiri & Kaeshi Namikiri when available.", "当可用时用奥义斩浪和回返斩浪替换意气冲天。"),
                KeyValuePair.Create("Replace Ikishoten with Shoha when Meditation is full before Ogi Namikiri.", "在奥义斩浪之前当剑压满时用照破替换意气冲天。"),
                KeyValuePair.Create("Hissatsu: Gyoten becomes Yaten/Gyoten depending on the distance from your target.", "必杀剑·晓天将根据与目标的距离变为必杀剑·夜天/必杀剑·晓天。"),
                // Ohter Descriptions
                KeyValuePair.Create("Set the Kenki overcap amount for ST combos.", "设置单目标连击的剑气溢出量。"),
                KeyValuePair.Create("Set the Kenki overcap amount for AOE combos.", "设置多目标连击的剑气溢出量。"),
                KeyValuePair.Create("Spends Kenki when at the set value or above.", "在剑气达到设定值或以上时消耗剑气。"),
                KeyValuePair.Create("Sens Feature", "三闪特性"),
                KeyValuePair.Create("Delay from first 明镜止水 to next step. (seconds)", "从第一次明镜止水到下一步的延迟时间（秒）"),
                KeyValuePair.Create("HP percent threshold to not save Kenki", "生命值百分比阈值低于此值时不保留剑气"),
                KeyValuePair.Create("Delay is enforced by replacing your button with Savage Blade.", "通过将你的按钮替换为狂怒剑来强制执行延迟。"),
                KeyValuePair.Create("Stop using Higanbana on targets below this HP % (0% = always use).", "目标生命值百分比低于此值时停用彼岸花（0 = 总是使用）"),
                #endregion
                
                #region SAMPvP
                KeyValuePair.Create("Turns Kasha Combo into an all-in-one button.", "将花车连击整合为一个按钮。"),
                KeyValuePair.Create("- Will not use actions with cast time while moving.", "- 移动时不会使用有施法时间的技能。"),
                KeyValuePair.Create("Uses Meikyo Shisui when available.", "在可用时使用明镜止水。"),
                KeyValuePair.Create("- Requires target to be in melee range.", "- 需要目标在近战范围内。"),
                KeyValuePair.Create("Uses Chiten when available.", "在可用时使用必杀剑·地天。"),
                KeyValuePair.Create("- Will not use outside combat.", "- 不会在战斗外使用。"),
                KeyValuePair.Create("Uses Mineuchi when available.", "在可用时使用刀背击打。"),
                KeyValuePair.Create("Uses Soten when available.", "在可用时使用必杀剑·早天。"),
                KeyValuePair.Create("- Will not use if already under Kaiten's effect.", "- 如果已经处于Kaiten效果下则不会使用。"),
                KeyValuePair.Create("Uses Zantetsuken when available.", "在可用时使用斩铁剑。"),
                KeyValuePair.Create("- Will not use if target is invulnerable.", "- 如果目标处于无敌状态则不会使用。"),
                KeyValuePair.Create("- Requires target to have player's Kuzushi.", "- 需要目标带有玩家的Kuzushi效果。"),
                KeyValuePair.Create("Burst Preparation", "爆发准备"),
                KeyValuePair.Create("Also uses Mineuchi before Tendo Setsugekka.", "在天道雪月花前额外使用刀背击打"),
                KeyValuePair.Create("Yukikaze Only", "仅限雪风"),
                KeyValuePair.Create("Also requires next weaponskill to be Yukikaze.", "同时要求下一个战技必须是雪风")
                #endregion                
            ];
        }
    }
}
