using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SGEDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region SGE
                KeyValuePair.Create("Adds various options to Dosis I/II/III.", "为Dosis I/II/III添加各种选项。"),
                KeyValuePair.Create("Use the Balance opener from level 92 onwards.", "从92级开始使用由The Balance社区建议的开场输出循环。"),
                KeyValuePair.Create("Weaves Lucid Dreaming when your MP drops below the specified value.", "当你的MP低于指定值时插入Lucid Dreaming。"),
                KeyValuePair.Create("Eukrasian Dosis Option", "均衡注药"),
                KeyValuePair.Create("Automatic DoT Uptime.", "自动续DoT。"),
                KeyValuePair.Create("Use selected instant cast actions while moving.", "在移动时使用选定的瞬发技能。"),
                KeyValuePair.Create("Use Phlegma if available and within range.", "如果Phlegma可用且在范围内，则使用。"),
                KeyValuePair.Create("Adds Kardia when not under the effect.", "当没有Kardia效果时添加Kardia。"),
                KeyValuePair.Create("Weaves Rhizomata when Addersgall gauge falls below the specified value.", "当Addersgall量谱低于指定值时插入Rhizomata。"),
                KeyValuePair.Create("Weaves Soteria if you have the Kardia buff.", "如果你有Kardia增益，则插入Soteria。"),
                KeyValuePair.Create("Weaves Psyche when available.", "当Psyche可用时插入。"),
                KeyValuePair.Create("Weaves Druochole when Addersgall gauge is greater than or equal to the specified value.", "当Addersgall量谱大于或等于指定值时插入Druochole。"),
                KeyValuePair.Create("Adds various options to Dyskrasia I & II. Requires a target.", "为Dyskrasia I & 为DyskrasiaII添加各种选项。需要目标。"),
                KeyValuePair.Create("Uses Phlegma if available.", "如果Phlegma可用，则使用。"),
                KeyValuePair.Create("Use Toxikon if available.", "如果Toxikon可用，则使用。"),
                KeyValuePair.Create("Adds Pneuma if available.", "如果Pneuma可用，则添加。"),
                KeyValuePair.Create("Weaves Psyche if available.", "如果Psyche可用，则插入。"),
                KeyValuePair.Create("Uses Eukrasia for Eukrasia Dyskrasia.", "使用Eukrasia来施放Eukrasia Dyskrasia。"),
                KeyValuePair.Create("Weaves Lucid Dreaming when your MP falls below the specified value.", "当你的MP低于指定值时插入Lucid Dreaming。"),
                KeyValuePair.Create("Supports soft-targeting.", "支持软目标选择。"),
                KeyValuePair.Create("Options below are in priority order.", "下方选项按优先级排序。"),
                KeyValuePair.Create("Applies Kardia to your target if it's not applied to anyone else.", "如果Kardia没有施放在其他人身上，则对目标施放Kardia。"),
                KeyValuePair.Create("Diagnosis becomes Eukrasian Diagnosis if the shield is not applied to the target.", "如果目标没有护盾，则将Diagnosis变为Eukrasian Diagnosis。"),
                KeyValuePair.Create("Applies Soteria.", "施放Soteria。"),
                KeyValuePair.Create("Applies Zoe.", "施放Zoe。"),
                KeyValuePair.Create("Triggers Pepsis if a shield is present.", "如果有护盾，则触发Pepsis。"),
                KeyValuePair.Create("Adds Taurochole.", "添加Taurochole。"),
                KeyValuePair.Create("Applies Haima.", "施放Haima。"),
                KeyValuePair.Create("Adds Rhizomata when Addersgall is 0.", "当Addersgall为0时添加Rhizomata。"),
                KeyValuePair.Create("Applies Krasis.", "施放Krasis。"),
                KeyValuePair.Create("Applies Druochole.", "施放Druochole。"),
                KeyValuePair.Create("Adds Kerachole.", "添加Kerachole。"),
                KeyValuePair.Create("Adds Ixochole.", "添加Ixochole。"),
                KeyValuePair.Create("Adds Physis.", "添加Physis。"),
                KeyValuePair.Create("Adds Holos.", "添加Holos。"),
                KeyValuePair.Create("Adds Panhaima.", "添加Panhaima。"),
                KeyValuePair.Create("Adds Philosophia.", "添加Philosophia。"),
                KeyValuePair.Create("Adds Zoe.", "添加Zoe。"),
                KeyValuePair.Create("Chain to Pneuma After.", "在Pneuma之后连锁。"),
                KeyValuePair.Create("Prognosis becomes Eukrasian Prognosis if the shield is not applied.", "如果没有护盾，则将Prognosis变为Eukrasia Prognosis。"),
                KeyValuePair.Create("Replaces Addersgall skills with Rhizomata when empty.", "当Addersgall技能为空时，用Rhizomata替换。"),
                KeyValuePair.Create("Turns Taurochole to Druochole when Taurochole is on cooldown.", "当Taurochole在冷却时，将其变为Druochole。"),
                KeyValuePair.Create("Places Zoe on top of Pneuma when both actions are on cooldown.", "当Pneuma和Zoe都在冷却时，将Zoe放在Pneuma之上。"),
                KeyValuePair.Create("Changes Swiftcast to Egeiro while Swiftcast is on cooldown.", "当Swiftcast在冷却时，将其变为Egeiro。"),
                KeyValuePair.Create("Soteria turns into Kardia when not active or Soteria is on-cooldown.", "当Soteria未激活或在冷却时，Soteria变为Kardia。"),
                KeyValuePair.Create("Eukrasia turns into the selected Eukrasian-type action when active.", "当Eukrasia激活时，将其变为选定的Eukrasia类型技能。"),
                KeyValuePair.Create("Prevents you from wasting actions if under the effect of someone else's actions", "防止你在他人技能效果下浪费技能。"),
                KeyValuePair.Create("Don't use Kerachole when under the effect of someone's Kerachole", "在他人的Kerachole效果下不要使用Kerachole。"),
                KeyValuePair.Create("Don't use Kerachole when under the effect of someone's Sacred Soil", "在他人的Sacred Soil效果下不要使用Kerachole。"),
                KeyValuePair.Create("Don't use Panhaima when under the effect of someone's Panhaima", "在他人的Panhaima效果下不要使用Panhaima。"),
                KeyValuePair.Create("Don't use Philosophia when under the effect of someone's Philosophia", "在他人的Philosophia效果下不要使用Philosophia。"),
                KeyValuePair.Create("Turns Dosis III into an all-in-one damage button.", "将Dosis III变为一个全能伤害按钮。"),
                KeyValuePair.Create("Adds Pneuma to Burst Mode.", "将Pneuma添加到爆发模式。"),
                KeyValuePair.Create("Adds Eukrasia to Burst Mode.", "将Eukrasia添加到爆发模式。"),
                KeyValuePair.Create("Adds Phlegma to Burst Mode.", "将Phlegma添加到爆发模式。"),
                KeyValuePair.Create("Adds Psyche to Burst Mode.", "将Psyche添加到爆发模式。"),
                KeyValuePair.Create("Adds Toxikon to Burst Mode.", "将Toxikon添加到爆发模式。"),
                KeyValuePair.Create("Adds Toxikon II to Burst Mode.", "将Toxikon II添加到爆发模式。"),
                KeyValuePair.Create("Adds Kardia to Burst Mode.", "将Kardia添加到爆发模式。"),
                KeyValuePair.Create("Customize your AoE healing to your liking.", "根据你的喜好自定义范围治疗技能。"),
                KeyValuePair.Create("Check for Scholar Galvenize", "检查学者的鼓舞激励之策护盾"),
                KeyValuePair.Create("Enable to not override an existing Scholar's shield.", "启用以避免覆盖学者的护盾。"),
                KeyValuePair.Create("Check for Enhanced Kerachole Trait (Heal over Time)", "检查强化坚角清汁特性（持续治疗）"),
                KeyValuePair.Create($"Enabling this will prevent {SGE.Kerachole.ActionName()} from being used when the Heal over Time trait == unavailable.", $"启用此选项后，当持续治疗特性不可用时，将阻止使用 {SGE.Kerachole.ActionName()}。"),
                KeyValuePair.Create("Shield Check: Percentage of Party Members without shields to check for.", "护盾检查：检查没有护盾的小队成员的百分比。"),
                KeyValuePair.Create("Ignore Shield Check", "忽略护盾检查"),
                KeyValuePair.Create("Overflow Protection", "溢出保护"),
                #endregion

                // Manually added                
                KeyValuePair.Create("Warning, will force the use of 均衡诊断, and normal 诊断 will be unavailable.", "警告：将强制使用均衡诊断，且无法使用普通的诊断。"),
                KeyValuePair.Create("Apply all selected options to 注药II", "应用所有选项到注药II"),
                KeyValuePair.Create("注药 & 注药III will behave normally.", "注药 & 注药III保留原样不被替换。"),
                KeyValuePair.Create("Addersgall", "蛇胆"),
                KeyValuePair.Create($"Use {SGE.Toxikon.ActionName()} when Addersting == available.", $"当{SGEPvP.Buffs.Addersting.StatusName()}可用时使用{SGE.Toxikon.ActionName()}。"),
                KeyValuePair.Create($"Use {SGE.Dyskrasia.ActionName()} when in range of a selected enemy target.", $"当在选中敌方目标的范围内时使用{SGE.Dyskrasia.ActionName()}。"),
                KeyValuePair.Create($"Use {SGE.Eukrasia.ActionName()}.", $"使用{SGE.Eukrasia.ActionName()}。"),
            ];
        }
    }
}
