using ECommons.ExcelServices;
using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class SMNDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region SMNPvE
                KeyValuePair.Create("Replaces Ruin with a full one-button single target rotation.", "用一键单目标循环替换毁灭。"),
                KeyValuePair.Create("Replaces Outburst with a full one-button AoE rotation.", "用一键AoE循环替换迸裂。"),
                KeyValuePair.Create("Replaces Emerald Ruin III with Ruin III in the rotation when standing still and Ruin Mastery III is not active.", "当站立不动且朦胧未激活时，在循环中用毁荡替换绿宝石毁荡。"),
                KeyValuePair.Create("Demi Attacks Combo Option", "亚灵神攻击连击选项"),
                KeyValuePair.Create("Adds Demi Summon oGCDs to the single target combo.", "将亚灵神召唤兽的能力技添加到单体连击中。"),
                KeyValuePair.Create("Adds Rekindle to the single target combo.", "将Rekindle添加到单目标连击中。"),
                KeyValuePair.Create("Egi Attacks Combo Option", "三神攻击连击选项"),
                KeyValuePair.Create("Adds Lux Solaris to the single target combo.", "将日光普照添加到单目标连击中。"),
                KeyValuePair.Create("Adds Gemshine to the single target combo.", "将宝石耀添加到单目标连击中。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the single target combo when MP falls below the set value.", "当MP低于设定值时，将Lucid Dreaming添加到单目标连击中。"),
                KeyValuePair.Create("Add Egi Astralflow", "添加三神星极超流"),
                KeyValuePair.Create("Choose which Egi Astralflows to add to the rotation.", "选择将哪些三神星极超流添加到循环中。"),
                KeyValuePair.Create("Adds Ruin IV to the single target combo.", "将毁绝添加到单目标连击中。"),
                KeyValuePair.Create("Uses when moving during Garuda Phase and you have no attunement, when moving during Ifrit phase, or when you have no active Egi or Demi summon.", "在风神阶段移动且没有共鸣时使用，或在火神阶段移动时使用，或当没有激活的三神或亚灵神召唤时使用。"),
                KeyValuePair.Create("Energy Attacks Combo Option", "能量攻击连击"),
                KeyValuePair.Create("Adds Energy Drain and Fester to the single target combo.", "将Energy Drain和Fester添加到单目标连击中。"),
                KeyValuePair.Create("Will be used on cooldown.", "将在冷却时使用。"),
                KeyValuePair.Create("Bahamut Burst becomes Solar Bahamut Burst at Lv100.", "在100级时，龙神迸发变为烈日龙神迸发。"),
                KeyValuePair.Create("Checks for any Searing Light for bursting rather than just your own.", "检查任何Searing Light以进行爆发，而不仅仅是你自己的。"),
                KeyValuePair.Create("Use this option if partied with multiple SMN and are worried about your Searing Light being wasted.", "如果与多个召唤师组队并担心你的Searing Light被浪费，请使用此选项。"),
                KeyValuePair.Create("Adds Searing Light to the single target combo.", "将灼热之光添加到单目标连击中。"),
                KeyValuePair.Create("Casts Searing Light only during Demi phases.", "仅在亚灵神阶段施放灼热之光。"),
                KeyValuePair.Create("Reflects Demi choice selected under 'Pooled oGCDs Option'.", "反映在“储备能力技”下选择的亚灵神阶段。"),
                KeyValuePair.Create("Not recommended for SpS Builds.", "不推荐用于灵活咏速构建。"),
                KeyValuePair.Create("Adds Searing Flash to the single target combo.", "将灼热之闪添加到单目标连击中。"),
                KeyValuePair.Create("Demi Summons Combo Option", "亚灵神召唤连击"),
                KeyValuePair.Create("Adds Demi summons to the single target combo.", "将亚灵神召唤添加到单目标连击中。"),
                KeyValuePair.Create("Swiftcast Egi Ability Option", "即刻咏唱三神技能"),
                KeyValuePair.Create("Uses Swiftcast during the selected Egi summon.", "在选定的三神召唤期间使用Swiftcast。"),
                KeyValuePair.Create("Egi Summons Combo Option", "三神召唤连击"),
                KeyValuePair.Create("Adds Egi summons to the single target combo.", "将三神召唤添加到单目标连击中。"),
                KeyValuePair.Create("Will prioritise the Egi selected below.", "将优先选择下面选定的三神。"),
                KeyValuePair.Create("Adds Energy Siphon and Painflare to the AoE combo.", "将能量抽取和痛苦核爆添加到AoE连击中。"),
                KeyValuePair.Create("Adds Searing Light to the AoE combo.", "将灼热之光添加到AoE连击中。"),
                KeyValuePair.Create("Adds Demi Summon oGCDs to the AoE combo.", "将亚灵神召唤兽能力技添加到AoE连击中。"),
                KeyValuePair.Create("Adds Rekindle to the AoE combo.", "将Rekindle添加到AoE连击中。"),
                KeyValuePair.Create("Any Searing Burst Option", "任意灼热之光爆发"),
                KeyValuePair.Create("Checks for any Searing light for bursting rather than just your own.", "检查任何Searing Light以进行爆发，而不仅仅是你自己的。"),
                KeyValuePair.Create("Use this option if partied with multiple SMN and are worried about your Searing being overwritten.", "如果与多个召唤师组队并担心你的Searing被覆盖，请使用此选项。"),
                KeyValuePair.Create("Adds Searing Flash to the AoE combo.", "将灼热之闪添加到AoE连击中。"),
                KeyValuePair.Create("Adds Lux Solaris to the AoE combo.", "将日光普照添加到AoE连击中。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the AoE combo when MP falls below the set value.", "当MP低于设定值时，将Lucid Dreaming添加到AoE连击中。"),
                KeyValuePair.Create("Adds Demi summons to the AoE combo.", "将亚灵神召唤添加到AoE连击中。"),
                KeyValuePair.Create("Adds Ruin IV to the AoE combo.", "将毁绝添加到AoE连击中。"),
                KeyValuePair.Create("Adds Precious Brilliance to the AoE combo.", "将宝石辉添加到AoE连击中。"),
                KeyValuePair.Create("Adds Egi summons to the AoE combo.", "将三神召唤添加到AoE连击中。"),
                KeyValuePair.Create("Change Fester into Energy Drain when out of Aetherflow stacks.", "当以太超流层数耗尽时，将溃烂爆发更改为能量吸收。"),
                KeyValuePair.Create("Changes Fester to Ruin IV when out of Aetherflow stacks, Energy Drain is on cooldown, and Ruin IV is available.", "当以太超流层数耗尽、能量吸收在冷却中且毁绝可用时，将溃烂爆发更改为毁绝。"),
                KeyValuePair.Create("Change Painflare into Energy Siphon when out of Aetherflow stacks.", "当以太超流层数耗尽时，将痛苦核爆更改为能量抽取。"),
                KeyValuePair.Create("Carbuncle Reminder Feature", "宝石兽提醒"),
                KeyValuePair.Create("Replaces most offensive actions with Summon Carbuncle when it is not summoned.", "当宝石兽召唤未召唤时，用宝石兽召唤替换大多数攻击技能。"),
                KeyValuePair.Create("Astral Flow/Enkindle on Demis Feature", "星极超流/迸发添加到亚灵神召唤"),
                KeyValuePair.Create("Adds Enkindle Bahamut, Enkindle Phoenix and Astral Flow to their relevant summons.", "将龙神迸发、不死鸟迸发和星极超流添加到它们相关的召唤中。"),
                KeyValuePair.Create("Changes Swiftcast to Raise when on cooldown.", "当即刻咏唱在冷却中时，将其更改为复活。"),
                KeyValuePair.Create("Ruin III Mobility Feature", "毁荡机动性功能"),
                KeyValuePair.Create("Puts Ruin III on Ruin IV when you don't have Further Ruin.", "当你没有毁绝预备时，将毁荡放在毁绝上。"),
                KeyValuePair.Create("Egi Abilities on Summons Feature", "三神技能添加到三神召唤"),
                KeyValuePair.Create("Adds Egi Abilities (Astral Flow) to Egi summons when ready.", "当准备好时，将三神技能（星极超流）添加到三神召唤中。"),
                KeyValuePair.Create("Egi abilities will appear on their respective Egi summon ability, as well as Titan.", "三神技能将出现在它们各自的三神召唤上。"),
                KeyValuePair.Create("Changes Painflare to Ruin IV when out of Aetherflow stacks, Energy Siphon is on cooldown, and Ruin IV is up.", "当以太超流层数耗尽、能量抽取在冷却中且毁绝可用时，将痛苦核爆更改为毁绝。"),
                KeyValuePair.Create("Turn Swiftcast into Variant Raise whenever you have the Swiftcast buff.", "当你有即刻咏唱增益时，将即刻咏唱更改为变异复活。"),
                KeyValuePair.Create("Solar Bahamut/Bahamut", "烈日龙神/龙神"),
                KeyValuePair.Create("Bursts during Bahamut phase.", "在龙神爆发。"),
                KeyValuePair.Create("Bahamut burst phase becomes Solar Bahamut at Lv100.", "在等级 100 时，龙神爆发阶段改为烈日龙神。"),
                KeyValuePair.Create("Bursts during Phoenix phase.", "在不死鸟阶段爆发。"),
                KeyValuePair.Create("Any Demi Phase", "任意亚灵神阶段"),
                KeyValuePair.Create("Bursts during any Demi Summon phase.", "在任何亚灵神召唤阶段爆发。"),
                KeyValuePair.Create("Flexible (SpS) Option", "灵活（咏速）选项"),
                KeyValuePair.Create("Bursts when Searing Light is ready, regardless of phase.", "当灼热之光准备就绪时爆发，无论处于哪个阶段。"),
                KeyValuePair.Create("Sets the amount of GCDs under Demi summon to wait for oGCD use.", "设置在亚灵神召唤下等待使用能力技的GCD数量。"),
                KeyValuePair.Create($"Do not use when under another {Job.SMN.GetData().Abbreviation}'s {SMN.Buffs.SearingLight.StatusName()} buff.", $"当处于其他召唤师的{SMN.Buffs.SearingLight.StatusName()}增益下时不要使用。"),
                KeyValuePair.Create($"Do not user when under another {Job.SMN.GetData().Abbreviation}'s {SMN.Buffs.SearingLight.StatusName()} buff.", $"当处于其他召唤师的{SMN.Buffs.SearingLight.StatusName()}增益下时不要使用。"),
                KeyValuePair.Create($"Saves your {SMN.SearingLight.ActionName()} if you already have the buff from another {Job.SMN.GetData().Abbreviation}.", $"如果你已经拥有其他召唤师的增益，则保留你的 {SMN.SearingLight.ActionName()}。"),
                KeyValuePair.Create("Enforced Crimson Cyclone Melee Check", "强制深红旋风近战范围检查"),
                KeyValuePair.Create("Only uses Crimson Cyclone within melee range.", "仅在近战范围内使用深红旋风。"),
                KeyValuePair.Create("Pooled oGCDs Option", "储备能力技"),
                KeyValuePair.Create("Enforced ", "储备能力技"),
                KeyValuePair.Create("Retarget Rekindle Combo Option", "苏生之炎重定向连击"),
                KeyValuePair.Create("Will Retarget Rekindle to a tank that needs it, then a party member that need healing, before Self.", "将苏生之炎重定向到需要治疗的坦克，然后是需要治疗的队友，最后才是自己。"),
                KeyValuePair.Create("Adds Titan to the Single Target Rotation", "将土神召唤添加到单目标循环中"),
                KeyValuePair.Create("Adds Titan to the AoE Rotation", "将土神召唤添加到多目标循环中"),
                KeyValuePair.Create("Adds Garuda to the Single Target Rotation", "将风神召唤添加到单目标循环中"),
                KeyValuePair.Create("Adds Garuda to the AoE Rotation", "将风神召唤添加到多目标循环中"),
                KeyValuePair.Create("Adds Ifrit to the Single Target Rotation", "将火神召唤添加到单目标循环中"),
                KeyValuePair.Create("Adds Ifrit to the AoE Rotation", "将火神召唤添加到多目标循环中"),
                KeyValuePair.Create("Will use Radiant Aegis, 30 second self shield, when at 2 charges to prevent waste", "当有2层充能时使用守护之光，30秒自身护盾，防止浪费"),
                KeyValuePair.Create("Searing Light Waste Protection Feature", "灼热之光防浪费功能"),
                KeyValuePair.Create("Changes Searing light to SavageBlade while under the affect of another summoners buff to prevent waste.", "在受到其他召唤师增益影响时，将灼热之光更改为重斩以防止浪费。"),
                KeyValuePair.Create("Will Retarget the Raises affected here to your Heal Stack.", "将受影响的复活重定向到你的治疗目标。"),
                KeyValuePair.Create("Retarget Raises", "重定向复活"),
                KeyValuePair.Create("Set value for your MP to be at or under for this feature to take effect.", "设置你的MP值在此功能生效时的上限。"),
                KeyValuePair.Create(" Maximum range to use Crimson Cyclone.", "使用深红旋风的最大范围。"),
                KeyValuePair.Create("Use Ruin III instead of Emerald Ruin III when standing still between the levels of 54 and 72", "在54到72级之间站立不动时使用毁荡代替绿宝石毁荡"),
                #endregion

                #region SMNPvP
                KeyValuePair.Create("Turns Ruin III into an all-in-one damage button.", "将Ruin III变为一个全能伤害技能按钮。"),
                KeyValuePair.Create("Only uses Crimson Cyclone when in melee range.", "仅在近战范围内使用Crimson Cyclone。"),
                KeyValuePair.Create("Adds Radiant Aegis to Burst Mode when available, and your HP is at or below the set percentage.", "当可用且你的HP低于或等于设定百分比时，将Radiant Aegis加入Burst Mode。"),
                KeyValuePair.Create("Adds Crimson Cyclone to Burst Mode.", "将Crimson Cyclone加入Burst Mode。"),
                KeyValuePair.Create("Adds Crimson Strike to Burst Mode.", "将Crimson Strike加入Burst Mode。"),
                KeyValuePair.Create("Adds Mountain Buster to Burst Mode.", "将Mountain Buster加入Burst Mode。"),
                KeyValuePair.Create("Adds Slipstream to Burst Mode.", "将Slipstream加入Burst Mode。"),
                KeyValuePair.Create("Adds Necrotize to Burst Mode.", "将Necrotize加入Burst Mode。"),
                KeyValuePair.Create("Adds DeathFlare to Burst Mode.", "将DeathFlare加入Burst Mode。"),
                KeyValuePair.Create("Adds Brand of Purgatory to Burst Mode.", "将Brand of Purgatory加入Burst Mode。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Swiftcasts the first available Egi when Swiftcast is ready.", "即刻咏唱冷却即用，不管是哪个蛮神"),
                KeyValuePair.Create("Swiftcasts Slipstream", "即刻咏唱螺旋气流"),
                KeyValuePair.Create("Swiftcasts Ruby Ruin/Ruby Rite", "即刻咏唱红宝石毁灭（毁荡/毁坏）/红宝石之仪"),
                KeyValuePair.Create("Summons Titan, Garuda then Ifrit.", "召唤顺序：土神->风神->火神"),
                KeyValuePair.Create("Summons Garuda, Titan then Ifrit.", "召唤顺序：风土神->土神->火神"),
            ];
        }
    }
}
