using Lumina.Data.Parsing;
using System;
using System.Collections.Generic;
using static WrathCombo.Combos.PvE.WAR;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class WARDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region WARPvE
                KeyValuePair.Create("Replaces Heavy Swing with a full one-button single target rotation.", "用一键完整单体循环替换重劈。"),
                KeyValuePair.Create("This is the ideal option for newcomers to the job.", "这是新手玩家的理想选择。"),
                KeyValuePair.Create("Replaces Overpower with a full one-button AoE rotation.", "用一键完整AOE循环替换超压斧。"),
                KeyValuePair.Create("Adds Interject to the rotation when your target's cast is interruptible.", "当目标施法可打断时，将插言加入循环。"),
                KeyValuePair.Create("Adds Storms Eye into the rotation.", "将暴风碎加入循环。"),
                KeyValuePair.Create("Adds Tomahawk into the rotation when you are out of range.", "当你超出近战范围时，将飞斧加入循环。"),
                KeyValuePair.Create("Adds Berserk / Inner Release into the rotation.", "将狂暴/原初的解放加入循环。"),
                KeyValuePair.Create("Adds Inner Beast / Fell Cleave into the rotation.", "将原初之魂/裂石飞环加入循环。"),
                KeyValuePair.Create("Will use when you have the set minimum gauge, or under Inner Release buff.", "当你有设定的最低怒气槽或在原初的解放增益下时使用。"),
                KeyValuePair.Create("Will also use Nascent Chaos.", "同时也会使用原初的混沌。"),
                KeyValuePair.Create("Adds Infuriate into the rotation.", "将战嚎加入循环。"),
                KeyValuePair.Create("Adds Onslaught into the rotation.", "将猛攻加入循环。"),
                KeyValuePair.Create("Uses Onslaught when in the Target's target ring (or within 1 yalm) & when not moving.", "在目标的环形范围内（或1码内）且不移动时使用猛攻。"),
                KeyValuePair.Create("Will use as many stacks as selected in the above slider.", "将使用上述滑块中选择的尽可能多的层数。"),
                KeyValuePair.Create("Adds Upheaval into the rotation.", "将动乱加入循环。"),
                KeyValuePair.Create("Adds Primal Rend into the rotation.", "将蛮荒崩裂加入循环。"),
                KeyValuePair.Create("Only uses when in the Target's target ring (or within 1 yalm) & when not moving.", "仅在目标的环形范围内（或1码内）且不移动时使用。"),
                KeyValuePair.Create("Adds Primal Wrath into the rotation.", "将原初的怒震加入循环。"),
                KeyValuePair.Create("Adds Primal Ruination into the rotation.", "将尽毁加入循环。"),
                KeyValuePair.Create("Adds Orogeny into the rotation.", "将群山隆起加入循环。"),
                KeyValuePair.Create("Uses Primal Rend after you consume 3 stacks of Inner Release & after Primal Wrath.", "在你消耗3层原初的解放后并在原初的怒震之后使用蛮荒崩裂。"),
                KeyValuePair.Create("Adds defensive actions into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将防御技能加入循环。"),
                KeyValuePair.Create("Adds Raw Intuition / Bloodwhetting into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将原初的直觉/原初的血气加入循环。"),
                KeyValuePair.Create("Adds Equilibrium into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将泰然自若加入循环。"),
                KeyValuePair.Create("Adds Rampart into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将铁壁加入循环。"),
                KeyValuePair.Create("Adds Thrill of Battle into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将战栗加入循环。"),
                KeyValuePair.Create("Adds Vengeance / Damnation into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将复仇/戮罪加入循环。"),
                KeyValuePair.Create("Adds Holmgang into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将死斗加入循环。"),
                KeyValuePair.Create("Adds Reprisal into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将雪仇加入循环。"),
                KeyValuePair.Create("Adds Arm's Length into the rotation based on Health percentage remaining.", "根据剩余生命值百分比将亲疏自行加入循环。"),
                KeyValuePair.Create("Adds Low Blow to the rotation when your target is casting, interruptible or not.", "当目标施法时，无论是否可打断，将下踢加入循环。"),
                KeyValuePair.Create("Replace Nascent Flash with Raw intuition when level synced below 76.", "当等级同步低于76级时，用原初的直觉替换原初的勇猛。"),
                KeyValuePair.Create("Adds Infuriate into the rotation when gauge is below 50 and not under Inner Release.", "当怒气槽低于50且不在原初的解放下时，将战嚎加入循环。"),
                KeyValuePair.Create("Adds Steel Cyclone / Decimate into the rotation.", "将钢铁旋风/地毁人亡加入循环。"),
                KeyValuePair.Create("Gives max priority to Holmgang when the Health percentage threshold is met.", "当生命值百分比达到阈值时，优先使用死斗。"),
                KeyValuePair.Create("Adds Raw Intuition / Bloodwhetting to the one-button mitigation.", "将原初的直觉/原初的血气加入一键减伤。"),
                KeyValuePair.Create("Adds Equilibrium to the one-button mitigation.", "将泰然自若加入一键减伤。"),
                KeyValuePair.Create("Adds Reprisal to the one-button mitigation.", "将雪仇加入一键减伤。"),
                KeyValuePair.Create("NOTE: Will not use unless there is a target within range to prevent waste", "注意：除非范围内有目标，否则不会使用，以防止浪费。"),
                KeyValuePair.Create("Adds Rampart to the one-button mitigation.", "将铁壁加入一键减伤。"),
                KeyValuePair.Create("Adds Shake It Off to the one-button mitigation.", "将摆脱加入一键减伤。"),
                KeyValuePair.Create("Adds Arm's Length to the one-button mitigation.", "将亲疏自行加入一键减伤。"),
                KeyValuePair.Create("Adds Vengeance to the one-button mitigation.", "将复仇加入一键减伤。"),
                KeyValuePair.Create("Turns Fell Cleave and Decimate into Infuriate if at or under set gauge value.", "当怒气槽等于或低于设定值时，将裂石飞环和地毁人亡转换为战嚎。"),
                KeyValuePair.Create("Inner Release Priority Option", "原初的解放优先级"),
                KeyValuePair.Create("Prevents the use of Infuriate while you have Inner Release stacks available.", "当你有原初的解放层数时，阻止使用战嚎。"),
                KeyValuePair.Create("Replace Storm's Eye with its combo chain.", "用其连击链替换暴风碎。"),
                KeyValuePair.Create("Replaces Storm's Path with Storm's Eye when Surging Tempest buff needs refreshing.", "当战场风暴增益需要刷新时，用暴风碎替换暴风斩。"),
                KeyValuePair.Create("Replaces Thrill Of Battle with Equilibrium when used.", "使用时用泰然自若替换战栗。"),
                KeyValuePair.Create("Replaces Thrill Of Battle with Equilibrium only when under its buff.", "仅在战栗增益存在时用泰然自若替换战栗。"),
                KeyValuePair.Create("Buffed Equilibrium Only", "仅在有增益状态时使用Equilibrium"),
                KeyValuePair.Create($" Seconds remaining before refreshing {Buffs.SurgingTempest.StatusName()} buff:", $"刷新{Buffs.SurgingTempest.StatusName()}增益前的剩余秒数"),
                KeyValuePair.Create("Stop usage if Target HP% is below set value.", "如果目标生命值百分比低于设定值则停用。"),
                KeyValuePair.Create("To disable this, set value to 0", "0为禁用此功能。"),
                KeyValuePair.Create("Uses Onslaught only while stationary", "仅在静止时使用猛攻"),
                KeyValuePair.Create("Uses Onslaught regardless of any movement conditions.", "无论任何移动条件都使用猛攻。"),
                KeyValuePair.Create("- Will use at set minimum Beast Gauge value or to consume Inner Release stacks", "- 将在设定的最低兽魂值或消耗原初的解放层数时使用"),
                KeyValuePair.Create("- Also includes Inner Chaos when available", "- 当可用时也会包含狂魂"),
                KeyValuePair.Create("Allow Fell Cleave for extra use during burst windows", "允许在爆发窗口期间额外使用裂石飞环"),
                KeyValuePair.Create("NOTE: This ignores the gauge slider below when ready for or already in burst", "注意：当准备爆发或已在爆发中时，此选项会忽略下方的怒气槽滑块"),
                KeyValuePair.Create("Forbid Fell Cleave for extra use during burst windows", "禁止在爆发窗口期间额外使用裂石飞环"),
                KeyValuePair.Create("NOTE: This fully honors the value set on the gauge slider below", "注意：此选项完全遵循下方怒气槽滑块设置的值"),
                KeyValuePair.Create("No Burst Pooling", "无爆发蓄力"),
                KeyValuePair.Create("Burst Pooling", "爆发蓄力"),
                KeyValuePair.Create("Minimum Beast Gauge required to spend:", "使用技能所需的最低兽魂值："),
                KeyValuePair.Create("Uses Primal Rend ASAP", "尽快使用蛮荒崩裂"),
                KeyValuePair.Create("Uses Primal Rend after consumption of all Inner Release stacks", "在消耗所有原初的解放层数后使用蛮荒崩裂"),
                KeyValuePair.Create("Uses Primal Rend only while stationary", "仅在静止时使用蛮荒崩裂"),
                KeyValuePair.Create("Uses Primal Rend regardless of any movement conditions.", "无论任何移动条件都使用蛮荒崩裂。"),
                KeyValuePair.Create("Adds Onslaught into the AoE rotation.", "将猛攻加入AOE循环。"),
                KeyValuePair.Create("Adds Steel Cyclone / Decimate into the AoE rotation.", "将钢铁旋风/地毁人亡加入AOE循环。"),
                KeyValuePair.Create("Adds Infuriate into the AoE rotation.", "将战嚎加入AOE循环。"),
                KeyValuePair.Create("Adds Orogeny into the AoE rotation.", "将群山隆起加入AOE循环。"),
                KeyValuePair.Create("Adds Primal Rend into the AoE rotation.", "将蛮荒崩裂加入AOE循环。"),
                KeyValuePair.Create("Adds Primal Wrath into the AoE rotation.", "将原初的怒震加入AOE循环。"),
                KeyValuePair.Create("Adds Interject to the AoE rotation when your target's cast is interruptible.", "当目标施法可打断时，将插言加入AOE循环。"),
                KeyValuePair.Create("Adds Low Blow to the AoE rotation when your target is casting, interruptible or not.", "当目标施法时，无论是否可打断，将下踢加入AOE循环。"),
                KeyValuePair.Create("Replaces Thrill Of Battle with an all-in-one mitigation button.", "用一键减伤按钮替换战栗。"),
                KeyValuePair.Create("Replaces Shake It Off with Reprisal when ready.", "准备就绪时用雪仇替换摆脱。"),
                KeyValuePair.Create("Collection of Fell Cleave related features.", "裂石飞环相关功能集合。"),
                KeyValuePair.Create("Enable all for this to be an all-in-one Single Target Burst button.", "启用所有功能使其成为一键单体爆发按钮。"),
                KeyValuePair.Create("Adds Berserk / Inner Release to Fell Cleave when available.", "当可用时将狂暴/原初的解放加入裂石飞环。"),
                KeyValuePair.Create("Adds Infuriate to Fell Cleave when available.", "当可用时将战嚎加入裂石飞环。"),
                KeyValuePair.Create("Adds Onslaught to Fell Cleave when available.", "当可用时将猛攻加入裂石飞环。"),
                KeyValuePair.Create("Adds Upheaval to Fell Cleave when available.", "当可用时将动乱加入裂石飞环。"),
                KeyValuePair.Create("Adds Primal Rend to Fell Cleave when available.", "当可用时将蛮荒崩裂加入裂石飞环。"),
                KeyValuePair.Create("Adds Primal Wrath to Fell Cleave when available.", "当可用时将原初的怒震加入裂石飞环。"),
                KeyValuePair.Create("Adds Primal Ruination to Fell Cleave when available.", "当可用时将尽毁加入裂石飞环。"),
                KeyValuePair.Create("Equilibirum to Thrill of Battle Feature", "泰然自若转战栗功能"),
                KeyValuePair.Create("Replaces Equilibirum with Thrill of Battle when ready.", "准备就绪时用战栗替换泰然自若。"),
                KeyValuePair.Create("Raw Intuition to Nascent Flash Retargeting Feature", "原初的直觉转原初的勇猛重定向功能"),
                KeyValuePair.Create("If available, will replace the Raw Intuition/Bloodwhetting with Nascent Flash if you are hard targeting an ally.", "如果可用且你硬锁定盟友，将用原初的勇猛替换原初的直觉/原初的血气。"),
                KeyValuePair.Create("Include MouseOver Target", "包含鼠标悬停目标"),
                KeyValuePair.Create("If mousing over an ally in the UI, will Retarget Nascent Flash onto them.", "如果在UI中鼠标悬停在盟友上，将重定向原初的勇猛到他们身上。"),
                KeyValuePair.Create("Include Target's Target", "包含目标的目标"),
                KeyValuePair.Create("If your target's target is not you, will Retarget Nascent Flash onto them.", "如果你的目标的目标不是你，将重定向原初的勇猛到他们身上。"),
                KeyValuePair.Create("(if you're not top aggro, and not mousing over or hard targeting an ally)", "（如果你不是最高仇恨，且没有鼠标悬停或硬锁定盟友）"),
                KeyValuePair.Create("Retarget Holmgang Feature", "死斗重定向功能"),
                KeyValuePair.Create("Will Retarget Holmgang to yourself, instead of letting it go on enemies.", "将死斗重定向到自己身上，而不是让它作用于敌人。"),
                KeyValuePair.Create("Use when Beast Gauge is less than or equal to:", "当兽魂小于或等于以下值时使用"),
                KeyValuePair.Create("Use when Distance from target is less than or equal to:", "当与目标的距离小于或等于以下值时使用"),
                KeyValuePair.Create("Adds Berserk / Inner Release into the AoE rotation.", "将狂暴/原初的解放加入AOE循环。"),
                #endregion

                #region WARPvP
                KeyValuePair.Create("Turns Heavy Swing into an all-in-one damage button.", "将重劈变为一个全能伤害技能按钮。"),
                KeyValuePair.Create("Allows use of Bloodwhetting any time, not just between GCDs.", "允许随时使用原初的血气，而不仅限于GCD之间。"),
                KeyValuePair.Create("Adds Blota to Burst Mode when not in melee range.", "当不在近战范围内时，将献身加入爆发模式。"),
                KeyValuePair.Create("Adds Primal Rend to Burst Mode.", "将蛮荒崩裂加入爆发模式。"),
                KeyValuePair.Create("Adds Inner Chaos to Burst Mode.", "将狂魂加入爆发模式。"),
                KeyValuePair.Create("Adds Orogeny to Burst Mode.", "将群山隆起加入爆发模式。"),
                KeyValuePair.Create("Adds Onslaught to Burst Mode.", "将猛攻加入爆发模式。"),
                KeyValuePair.Create("Adds Primal Scream to Burst Mode.", "将原初的怒号加入爆发模式。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Use when gauge is less than or equal to:", "当怒气槽小于或等于以下此值时使用："),
                KeyValuePair.Create("Minimum gauge required to spend", "使用技能所需的最低怒气槽值"),
                KeyValuePair.Create("Use when gauge is under or equal to", "当怒气槽小于或等于此值时使用"),
                KeyValuePair.Create("Primal Combo Feature", "原初连击"),
            ];
        }
    }
}
