using System;
using System.Collections.Generic;
using WrathCombo.Combos.PvE;
using WrathCombo.Combos.PvP;
using WrathCombo.Extensions;

namespace WrathCombo.Resources.Dictionary.Chinese.Description
{
    public static class WHMDesc
    {
        public static IEnumerable<KeyValuePair<string, string>> GetDescriptions()
        {
            return
            [
                // Generated by the String Extraction and Translation Tool  
                // Model: DeepSeek v3  
                // Temperature: 0.1  
                // Generation Time: 2025-03-13 18:14:55  
                #region WHM                                
                KeyValuePair.Create("Advanced Action", "高级技能"),
                KeyValuePair.Create("Change how actions are handled", "更改技能的处理方式"),
                KeyValuePair.Create("Balance Opener (Level 92)", "平衡起手式（等级92）"),
                KeyValuePair.Create("Adds a Swiftcast->Holy at the beginning of your AoE rotation.", "在AoE循环开始时添加一个即刻咏唱->神圣。"),
                KeyValuePair.Create("Swift Holy Pull 'Opener' Option", "即刻神圣起手"),
                KeyValuePair.Create("Requires you to already be in combat, to have stopped moving, and to not have used Assize yet.", "需要你已经进入战斗状态，停止移动，并且尚未使用Assize。"),
                KeyValuePair.Create("Collection of cooldowns and spell features on Glares/Stones/Aeros/Dia.", "飞石/闪耀/疾风/天辉替换为冷却技和法术集合。"),
                KeyValuePair.Create("Adds Aero/Dia to the single target combo if the debuff is not present on current target, or is about to expire.", "如果当前目标没有疾风/天辉的减益效果，或者即将消失，则在单体连击中添加疾风/天辉。"),
                KeyValuePair.Create("Adds Assize to the single target combo.", "在单体连击中添加法令。"),
                KeyValuePair.Create("Adds Glare IV to the single target combo when under Sacred Sight", "在闪飒预备状态下，在单体连击中添加闪飒。"),
                KeyValuePair.Create("Adds Afflatus Misery to the single target combo when it is ready to be used.", "当苦难之心准备就绪时，在单体连击中添加苦难之心。"),
                KeyValuePair.Create("Adds Afflatus Rapture to the single target combo when at three Lilies.", "当拥有三个血百合时，在单体连击中添加狂喜之心。"),
                KeyValuePair.Create("Adds Presence of Mind to the single target combo.", "在单体连击中添加神速咏唱。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the single target combo when below set MP value.", "当魔力值低于设定值时，在单体连击中添加Lucid Dreaming。"),
                KeyValuePair.Create("Collection of cooldowns and spell features on Holy/Holy III.", "神圣/豪圣替换为冷却技和法术集合。"),
                KeyValuePair.Create("Adds Assize to the AoE combo.", "在AoE连击中添加法令。"),
                KeyValuePair.Create("Adds Glare IV to the AoE combo when under Sacred Sight", "在闪飒预备状态下，在AoE连击中添加闪飒。"),
                KeyValuePair.Create("Adds Afflatus Misery to the AoE combo when it is ready to be used.", "当苦难之心准备就绪时，在AoE连击中添加苦难之心。"),
                KeyValuePair.Create("Adds Afflatus Rapture to the AoE combo when at three Lilies.", "当拥有三个血百合时，在AoE连击中添加狂喜之心。"),
                KeyValuePair.Create("Adds Presence of Mind to the AoE combo, this will delay your GCD by default.", "在AoE连击中添加神速咏唱，默认情况下会延迟你的GCD。"),
                KeyValuePair.Create("Adds Lucid Dreaming to the AoE combo when below the set MP value if you are moving or it can be weaved without GCD delay.", "当MP低于设定值时，如果你在移动或可以在不延迟GCD的情况下插入，则在AoE连击中添加Lucid Dreaming。"),
                KeyValuePair.Create("Replaces Afflatus Solace with Afflatus Misery when it is ready to be used.", "当苦难之心准备就绪时，用苦难之心替换安慰之心。"),
                KeyValuePair.Create("Replaces Afflatus Rapture with Afflatus Misery when it is ready to be used.", "当苦难之心准备就绪时，用苦难之心替换狂喜之心。"),
                KeyValuePair.Create("Replaces Medica with a one button AoE healing setup.", "用一个按钮的AoE治疗设置替换医治。"),
                KeyValuePair.Create("Uses Afflatus Rapture when available.", "当狂喜之心可用时使用。"),
                KeyValuePair.Create("Uses Afflatus Misery when available.", "当苦难之心可用时使用。"),
                KeyValuePair.Create("Uses Thin Air when available.", "当无中生有可用时使用。"),
                KeyValuePair.Create("Replaces Medica with Cure III when available.", "当愈疗可用时，用愈疗替换医治。"),
                KeyValuePair.Create("Uses Assize when available.", "当法令可用时使用。"),
                KeyValuePair.Create("Uses Plenary Indulgence when available.", "当全大赦可用时使用。"),
                KeyValuePair.Create("Uses Lucid Dreaming when available.", "当Lucid Dreaming可用时使用。"),
                KeyValuePair.Create("Uses Divine Caress when Divine Grace from Temperance is active.", "当节制的神爱抚预备激活时使用神爱抚。"),
                KeyValuePair.Create("Replaces Cure with a one button single target healing setup.", "用一个按钮的单体治疗设置替换治疗。"),
                KeyValuePair.Create("Applies Regen to the target if missing.", "如果目标缺少再生，则应用再生。"),
                KeyValuePair.Create("Uses Benediction when target is below HP threshold.", "当目标HP低于阈值时使用天赐祝福。"),
                KeyValuePair.Create("Uses Afflatus Solace when available.", "当安慰之心可用时使用。"),
                KeyValuePair.Create("Uses Tetragrammaton when available.", "当神名可用时使用。"),
                KeyValuePair.Create("Uses Divine Benison when available.", "当神祝祷可用时使用。"),
                KeyValuePair.Create("Uses Aquaveil when available.", "当水流幕可用时使用。"),
                KeyValuePair.Create("Applies Esuna to your target if there is a cleansable debuff.", "如果目标有可清除的减益效果，则对目标使用Esuna。"),
                KeyValuePair.Create("Changes Cure II to Cure when synced below Lv.30.", "当同步到30级以下时，将救疗更改为治疗。"),
                KeyValuePair.Create("Changes Swiftcast to Raise.", "将即刻咏唱更改为复活。"),
                KeyValuePair.Create("Adds Thin Air to the Global Raise Feature/Alternative Raise Feature.", "将无中生有添加到全局复活功能/备用复活功能。"),
                KeyValuePair.Create("Use Variant Rampart on cooldown.", "冷却即用Variant Rampart。"),
                KeyValuePair.Create("Turns Glare into an all-in-one damage button.", "将闪耀变成一个全能伤害按钮。"),
                KeyValuePair.Create("Adds Afflatus Misery to Burst Mode.", "将苦难之心添加到爆发模式。"),
                KeyValuePair.Create("Adds Miracle of Nature to Burst Mode.", "将自然的奇迹添加到爆发模式。"),
                KeyValuePair.Create("Adds Seraph Strike to Burst Mode.", "将炽天强袭添加到爆发模式。"),
                KeyValuePair.Create("Adds Afflatus Purgation (Limit Break) to Burst Mode.", "将涤罪之心（极限技）添加到爆发模式。"),
                KeyValuePair.Create("Adds the below options onto Cure II.", "将以下选项添加到救疗。"),
                KeyValuePair.Create("Adds Cure III to Cure II when available.", "当愈疗可用时，将其添加到救疗。"),
                KeyValuePair.Create("Adds Aquaviel to Cure II when available.", "当水流幕可用时，将其添加到救疗。"),
                KeyValuePair.Create("Uses Medica II when heal target doesn't have Medica II buff.", "当当前目标没有Medica II增益时，使用Medica II。"),
                KeyValuePair.Create("Upgrades to Medica III when level allows.", "当等级允许时，升级为Medica III。"),
                KeyValuePair.Create("Only Weave or Use Whilst Moving.", "仅在移动时插入或使用。"),
                KeyValuePair.Create("Use when MP is above", "当MP高于此值时使用"),
                KeyValuePair.Create("Time Remaining on Buff to Renew", "刷新增益的剩余时间"),
                KeyValuePair.Create("Party UI Mousover Checking", "小队UI鼠标悬停检查"),
                KeyValuePair.Create("Check your mouseover target for the Medica II/III buff.", "检查你的鼠标悬停目标是否有医济/医养增益。"),
                KeyValuePair.Create("Time Remaining Before Refreshing", "刷新前的剩余时间"),
                KeyValuePair.Create("Use when target HP% is at or below.", "当目标生命值百分比等于或低于此值时使用。"),
                #endregion

                // Manually added
                KeyValuePair.Create("Apply options to all Stones and Glares.", "将选项应用于所有飞石及闪耀。"),
                KeyValuePair.Create("Apply options to Aeros and Dia.", "将选项应用于所有疾风及天辉。"),
                KeyValuePair.Create($"Apply options to On 坚石.", $"将选项应用于坚石。"),
                KeyValuePair.Create($"If Both {WHMPvP.Aquaveil.ActionName()} & {WHMPvP.Cure3.ActionName()} are ready, prioritise {WHMPvP.Aquaveil.ActionName()}", "如果水流幕和愈疗都准备就绪，优先使用水流幕"),
                KeyValuePair.Create($"If Both {WHMPvP.Aquaveil.ActionName()} & {WHMPvP.Cure3.ActionName()} are ready, prioritise {WHMPvP.Cure3.ActionName()}", "如果水流幕和愈疗都准备就绪，优先使用愈疗"),
                KeyValuePair.Create("Replaces Stone with a full one-button single target rotation.", "将飞石替换为完整的一键单体循环。"),
                KeyValuePair.Create("Replaces Holy with a full one-button AoE rotation.", "将神圣替换为完整的一键多目标循环。"),
                KeyValuePair.Create("Will reapply DoT early to all enemies within range while moving.", "移动时会对范围内所有敌人提前补上DoT。"),
                KeyValuePair.Create("Multitarget Dot Option", "多目标DOT选项"),
                KeyValuePair.Create("Maintains dots on multiple targets.", "保持DOT在多个目标上。"),
                
            ];
        }
    }
}
