//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OccultCrescent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OccultCrescent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.Content.OccultCrescent", typeof(OccultCrescent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} or {1} prior to using {2}.
        /// </summary>
        internal static string Add0Or1PriorUsing2 {
            get {
                return ResourceManager.GetString("Add0Or1PriorUsing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require at least 1 party member.
        /// </summary>
        internal static string AtLeast1PartyMember {
            get {
                return ResourceManager.GetString("AtLeast1PartyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Party HP to be less than or equal to:.
        /// </summary>
        internal static string AveragePartyHPLessOrEqual {
            get {
                return ResourceManager.GetString("AveragePartyHPLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are NOT one of the jobs that regularly damage buffs themselves, or do not party up in OC, then this will SKIP using Phantom Abilities until burst time is detected (which might be never on a buff-less job)!.
        /// </summary>
        internal static string BuffOnlyDont {
            get {
                return ResourceManager.GetString("BuffOnlyDont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRK, PLD, WAR, AST, MNK, DRG, NIN, BRD, are the only jobs this is likely to be a good option for.
        /// </summary>
        internal static string BuffOnlyList {
            get {
                return ResourceManager.GetString("BuffOnlyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many jobs do not have self buffs that are up regularly, many burst phases cannot accommodate extra Phantom Abilities, and many Phantom Abilities are up more often than this on would be on many jobs!.
        /// </summary>
        internal static string BuffOnlyNotRecommended {
            get {
                return ResourceManager.GetString("BuffOnlyNotRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a costly Feature!.
        /// </summary>
        internal static string Costly {
            get {
                return ResourceManager.GetString("Costly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not advisable in most situations!.
        /// </summary>
        internal static string NotAdvised {
            get {
                return ResourceManager.GetString("NotAdvised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require {0} or {1} to use {2}.
        /// </summary>
        internal static string Requires0Or1ToUse2 {
            get {
                return ResourceManager.GetString("Requires0Or1ToUse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slider value should be rather low, if you do use it!.
        /// </summary>
        internal static string SliderShouldBeLow {
            get {
                return ResourceManager.GetString("SliderShouldBeLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a VERY costly Feature!.
        /// </summary>
        internal static string VeryCostly {
            get {
                return ResourceManager.GetString("VeryCostly", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Keep Pray up.
        /// </summary>
        internal static string KeepPrayUp {
            get {
                return ResourceManager.GetString("KeepPrayUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also use Pray whenever the buff is missing, not only below the HP threshold..
        /// </summary>
        internal static string KeepPrayUpDesc {
            get {
                return ResourceManager.GetString("KeepPrayUpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When disabled, prefers the lowest-HP party member under the threshold..
        /// </summary>
        internal static string PledgeSelfOnlyDesc {
            get {
                return ResourceManager.GetString("PledgeSelfOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max target distance (yalms) to use Phantom Kick.
        /// </summary>
        internal static string MaxTargetDistancePhantomKick {
            get {
                return ResourceManager.GetString("MaxTargetDistancePhantomKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self or average party HP % at or below which to use Blessing.
        /// </summary>
        internal static string BlessingHpThreshold {
            get {
                return ResourceManager.GetString("BlessingHpThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self or average party HP % at or below which to prioritize Judgment as a heal.
        /// </summary>
        internal static string JudgmentHealHpThreshold {
            get {
                return ResourceManager.GetString("JudgmentHealHpThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save for Starfall.
        /// </summary>
        internal static string SaveForStarfall {
            get {
                return ResourceManager.GetString("SaveForStarfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Invulnerability before Starfall when Prediction of Starfall is up..
        /// </summary>
        internal static string SaveForStarfallDesc {
            get {
                return ResourceManager.GetString("SaveForStarfallDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In combat.
        /// </summary>
        internal static string InCombat {
            get {
                return ResourceManager.GetString("InCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Suspend while in combat..
        /// </summary>
        internal static string InCombatDesc {
            get {
                return ResourceManager.GetString("InCombatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of combat.
        /// </summary>
        internal static string OutOfCombat {
            get {
                return ResourceManager.GetString("OutOfCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Suspend while out of combat..
        /// </summary>
        internal static string OutOfCombatDesc {
            get {
                return ResourceManager.GetString("OutOfCombatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only as AoE mit.
        /// </summary>
        internal static string OnlyAsAoEMit {
            get {
                return ResourceManager.GetString("OnlyAsAoEMit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only use Occult Toad with 2+ targets in range, or when raidwide damage is incoming..
        /// </summary>
        internal static string OnlyAsAoEMitDesc {
            get {
                return ResourceManager.GetString("OnlyAsAoEMitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Occult Libra when remaining time is at or below this many seconds..
        /// </summary>
        internal static string RefreshOccultLibra {
            get {
                return ResourceManager.GetString("RefreshOccultLibra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazing Spellblade also refreshes at 30s remaining so other Spellblades do not take its cooldown..
        /// </summary>
        internal static string BlazingSpellbladeRefreshNote {
            get {
                return ResourceManager.GetString("BlazingSpellbladeRefreshNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh this buff or debuff when remaining time is at or below this many seconds. 0 waits until it drops..
        /// </summary>
        internal static string StatusRefreshSlider {
            get {
                return ResourceManager.GetString("StatusRefreshSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When disabled, also triggers if the lowest party member is below the HP threshold..
        /// </summary>
        internal static string PotionSelfOnlyDesc {
            get {
                return ResourceManager.GetString("PotionSelfOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When disabled, also triggers if any party member is below the MP threshold..
        /// </summary>
        internal static string EtherSelfOnlyDesc {
            get {
                return ResourceManager.GetString("EtherSelfOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarget to Out of Party Players.
        /// </summary>
        internal static string RetargetOutOfParty {
            get {
                return ResourceManager.GetString("RetargetOutOfParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also retargets if anyone outside your party falls below this HP%.
        /// </summary>
        internal static string RetargetOutOfPartyDesc {
            get {
                return ResourceManager.GetString("RetargetOutOfPartyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drain Touch usage:.
        /// </summary>
        internal static string DrainTouchUsage {
            get {
                return ResourceManager.GetString("DrainTouchUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        internal static string DrainTouchDps {
            get {
                return ResourceManager.GetString("DrainTouchDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use for damage (respects Restrict to Buff)..
        /// </summary>
        internal static string DrainTouchDpsDesc {
            get {
                return ResourceManager.GetString("DrainTouchDpsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        internal static string DrainTouchHeal {
            get {
                return ResourceManager.GetString("DrainTouchHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when your HP is at or below the heal threshold..
        /// </summary>
        internal static string DrainTouchHealDesc {
            get {
                return ResourceManager.GetString("DrainTouchHealDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        internal static string DrainTouchEmergency {
            get {
                return ResourceManager.GetString("DrainTouchEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when your HP is at or below the emergency threshold..
        /// </summary>
        internal static string DrainTouchEmergencyDesc {
            get {
                return ResourceManager.GetString("DrainTouchEmergencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necromancer spells while Drain Touch is active:.
        /// </summary>
        internal static string NecroSpellsDuringDrain {
            get {
                return ResourceManager.GetString("NecroSpellsDuringDrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when inactive.
        /// </summary>
        internal static string OnlyWhenInactive {
            get {
                return ResourceManager.GetString("OnlyWhenInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast Deep Freeze / Hell Wind / Chaos Drive / Doomsday only while Drain Touch is down..
        /// </summary>
        internal static string OnlyWhenInactiveDesc {
            get {
                return ResourceManager.GetString("OnlyWhenInactiveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when active.
        /// </summary>
        internal static string OnlyWhenActive {
            get {
                return ResourceManager.GetString("OnlyWhenActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast those spells only during the Drain Touch buff..
        /// </summary>
        internal static string OnlyWhenActiveDesc {
            get {
                return ResourceManager.GetString("OnlyWhenActiveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either.
        /// </summary>
        internal static string Either {
            get {
                return ResourceManager.GetString("Either", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Drain Touch buff for spell usage..
        /// </summary>
        internal static string EitherDesc {
            get {
                return ResourceManager.GetString("EitherDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only at 4 Finishing Fervor.
        /// </summary>
        internal static string OnlyAt4FinishingFervor {
            get {
                return ResourceManager.GetString("OnlyAt4FinishingFervor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Defend for when you have full Finishing Fervor stacks..
        /// </summary>
        internal static string OnlyAt4FinishingFervorDesc {
            get {
                return ResourceManager.GetString("OnlyAt4FinishingFervorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When both Blind and Paralysis can apply:.
        /// </summary>
        internal static string WhenBothBlindParalysis {
            get {
                return ResourceManager.GetString("WhenBothBlindParalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Dark Cannon.
        /// </summary>
        internal static string PreferDarkCannon {
            get {
                return ResourceManager.GetString("PreferDarkCannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind.
        /// </summary>
        internal static string Blind {
            get {
                return ResourceManager.GetString("Blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Shock Cannon.
        /// </summary>
        internal static string PreferShockCannon {
            get {
                return ResourceManager.GetString("PreferShockCannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralysis.
        /// </summary>
        internal static string Paralysis {
            get {
                return ResourceManager.GetString("Paralysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When neither can apply (immune / capped):.
        /// </summary>
        internal static string WhenNeitherCanApply {
            get {
                return ResourceManager.GetString("WhenNeitherCanApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Dark Cannon.
        /// </summary>
        internal static string UseDarkCannon {
            get {
                return ResourceManager.GetString("UseDarkCannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Shock Cannon.
        /// </summary>
        internal static string UseShockCannon {
            get {
                return ResourceManager.GetString("UseShockCannon", resourceCulture);
            }
        }

    }
}