//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.UI.Settings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsCfgUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsCfgUI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.UI.Settings.SettingsCfgUI", typeof(SettingsCfgUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string ActionChanging_defaultValue {
            get {
                return ResourceManager.GetString("ActionChanging_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls whether Actions on your Hotbar will be Replaced with combos from the plugin.
        ///If disabled, your manual presses of abilities will no longer be affected by any Wrath settings.
        ///
        ///Auto-Rotation will work regardless of the setting. 的本地化字符串。
        /// </summary>
        internal static string ActionChanging_helpMark {
            get {
                return ResourceManager.GetString("ActionChanging_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action Replacing 的本地化字符串。
        /// </summary>
        internal static string ActionChanging_Name {
            get {
                return ResourceManager.GetString("ActionChanging_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On (This is essentially turning OFF most of Wrath) 的本地化字符串。
        /// </summary>
        internal static string ActionChanging_recommendedValue {
            get {
                return ResourceManager.GetString("ActionChanging_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrath is largely designed with Action Replacing in mind.
        ///Only Auto-Rotation will work if this is disabled.
        ///Disabling it may also lead to unexpected behavior, such as regarding Retargeting. 的本地化字符串。
        /// </summary>
        internal static string ActionChanging_warningMark {
            get {
                return ResourceManager.GetString("ActionChanging_warningMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string AddOutOfPartyNPCsToRetargeting_defaultValue {
            get {
                return ResourceManager.GetString("AddOutOfPartyNPCsToRetargeting_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will add any NPCs that are not in your party to the retargeting logic for healing actions.
        ///
        ///Useful for healers who want to be able to target NPCs that are not in their party, such as quest NPCs.
        ///These NPCs will not generally work with any role-based custom Heal Stack entries
        ///(even if an NPC looks like a tank, they&apos;re not always classified as one) 的本地化字符串。
        /// </summary>
        internal static string AddOutOfPartyNPCsToRetargeting_helpMark {
            get {
                return ResourceManager.GetString("AddOutOfPartyNPCsToRetargeting_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Out-of-Party NPCs to Retargeting 的本地化字符串。
        /// </summary>
        internal static string AddOutOfPartyNPCsToRetargeting_Name {
            get {
                return ResourceManager.GetString("AddOutOfPartyNPCsToRetargeting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On (If you use Retargeting at all) 的本地化字符串。
        /// </summary>
        internal static string AddOutOfPartyNPCsToRetargeting_recommendedValue {
            get {
                return ResourceManager.GetString("AddOutOfPartyNPCsToRetargeting_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string AoEDamageToast_defaultValue {
            get {
                return ResourceManager.GetString("AoEDamageToast_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show a message on-screen whenever a stack/group damage cast is detected, including who it is targeting if applicable. 的本地化字符串。
        /// </summary>
        internal static string AoEDamageToast_helpMark {
            get {
                return ResourceManager.GetString("AoEDamageToast_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Toast on Group Damage 的本地化字符串。
        /// </summary>
        internal static string AoEDamageToast_Name {
            get {
                return ResourceManager.GetString("AoEDamageToast_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string AoEDamageToast_recommendedValue {
            get {
                return ResourceManager.GetString("AoEDamageToast_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string AoEDamageTTS_defaultValue {
            get {
                return ResourceManager.GetString("AoEDamageTTS_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will play a text-to-speech sound clip whenever a stack/group damage cast is detected, including who it is targeting if applicable. 的本地化字符串。
        /// </summary>
        internal static string AoEDamageTTS_helpMark {
            get {
                return ResourceManager.GetString("AoEDamageTTS_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play TTS on Group Damage 的本地化字符串。
        /// </summary>
        internal static string AoEDamageTTS_Name {
            get {
                return ResourceManager.GetString("AoEDamageTTS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string AoEDamageTTS_recommendedValue {
            get {
                return ResourceManager.GetString("AoEDamageTTS_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On, cause it&apos;s that type of day y&apos;know 的本地化字符串。
        /// </summary>
        internal static string AprilFools2026_defaultValue {
            get {
                return ResourceManager.GetString("AprilFools2026_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For when you can&apos;t get enough MNK in your plugin. 的本地化字符串。
        /// </summary>
        internal static string AprilFools2026_helpMark {
            get {
                return ResourceManager.GetString("AprilFools2026_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 April Fools 2026 Feature 的本地化字符串。
        /// </summary>
        internal static string AprilFools2026_Name {
            get {
                return ResourceManager.GetString("AprilFools2026_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off, unless your name starts with Beep 的本地化字符串。
        /// </summary>
        internal static string AprilFools2026_recommendedValue {
            get {
                return ResourceManager.GetString("AprilFools2026_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string BlockSpellOnMove_defaultValue {
            get {
                return ResourceManager.GetString("BlockSpellOnMove_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will completely block actions while moving, by replacing Combo outputs with Savage Blade.
        ///This would supersede combo-specific movement options, which many jobs have. 的本地化字符串。
        /// </summary>
        internal static string BlockSpellOnMove_helpMark {
            get {
                return ResourceManager.GetString("BlockSpellOnMove_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block Spells while Moving 的本地化字符串。
        /// </summary>
        internal static string BlockSpellOnMove_Name {
            get {
                return ResourceManager.GetString("BlockSpellOnMove_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off (Most Jobs will handle this better with their Features) 的本地化字符串。
        /// </summary>
        internal static string BlockSpellOnMove_recommendedValue {
            get {
                return ResourceManager.GetString("BlockSpellOnMove_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Target &gt; Hard Target &gt; Self 的本地化字符串。
        /// </summary>
        internal static string CustomHealStack_defaultValue {
            get {
                return ResourceManager.GetString("CustomHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If there are fewer than 4 items, and all return nothing when checked, will fall back to Self.
        ///
        ///These targets will only be considered valid if they are friendly and within 25y.
        ///
        ///When applied to something like Esuna, these targets will be checked for having a Cleansable Debuff, etc.
        ///So adding &apos;Any Cleansable Ally&apos; or similar is not necessary. 的本地化字符串。
        /// </summary>
        internal static string CustomHealStack_helpMark {
            get {
                return ResourceManager.GetString("CustomHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Heal Stack 的本地化字符串。
        /// </summary>
        internal static string CustomHealStack_Name {
            get {
                return ResourceManager.GetString("CustomHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string CustomHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("CustomHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string EnabledOutputLog_defaultValue {
            get {
                return ResourceManager.GetString("EnabledOutputLog_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will print to chat every time you use an action provided by Wrath. 的本地化字符串。
        /// </summary>
        internal static string EnabledOutputLog_helpMark {
            get {
                return ResourceManager.GetString("EnabledOutputLog_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Log to Chat 的本地化字符串。
        /// </summary>
        internal static string EnabledOutputLog_Name {
            get {
                return ResourceManager.GetString("EnabledOutputLog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On (IF trying to report an issue) 的本地化字符串。
        /// </summary>
        internal static string EnabledOutputLog_recommendedValue {
            get {
                return ResourceManager.GetString("EnabledOutputLog_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string HideChildren_defaultValue {
            get {
                return ResourceManager.GetString("HideChildren_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will hide the Features and Options under disabled Combos. 的本地化字符串。
        /// </summary>
        internal static string HideChildren_helpMark {
            get {
                return ResourceManager.GetString("HideChildren_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Sub-Combo Options 的本地化字符串。
        /// </summary>
        internal static string HideChildren_Name {
            get {
                return ResourceManager.GetString("HideChildren_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string HideChildren_recommendedValue {
            get {
                return ResourceManager.GetString("HideChildren_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string HideConflictedCombos_defaultValue {
            get {
                return ResourceManager.GetString("HideConflictedCombos_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will hide Combos that conflict with Combos that you have enabled. 的本地化字符串。
        /// </summary>
        internal static string HideConflictedCombos_helpMark {
            get {
                return ResourceManager.GetString("HideConflictedCombos_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Conflicted Combos 的本地化字符串。
        /// </summary>
        internal static string HideConflictedCombos_Name {
            get {
                return ResourceManager.GetString("HideConflictedCombos_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string HideConflictedCombos_recommendedValue {
            get {
                return ResourceManager.GetString("HideConflictedCombos_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string HideMessageOfTheDay_defaultValue {
            get {
                return ResourceManager.GetString("HideMessageOfTheDay_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will prevent the Message of the Day from being shown in your chat upon login. 的本地化字符串。
        /// </summary>
        internal static string HideMessageOfTheDay_helpMark {
            get {
                return ResourceManager.GetString("HideMessageOfTheDay_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide Message of the Day 的本地化字符串。
        /// </summary>
        internal static string HideMessageOfTheDay_Name {
            get {
                return ResourceManager.GetString("HideMessageOfTheDay_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string HideMessageOfTheDay_recommendedValue {
            get {
                return ResourceManager.GetString("HideMessageOfTheDay_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string InterruptDelay_defaultValue {
            get {
                return ResourceManager.GetString("InterruptDelay_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls the percentage of a total cast time to wait before interrupting enemy casts.
        ///Applies to all interrupts (including stuns used to interrupt) in every Job&apos;s Combos. 的本地化字符串。
        /// </summary>
        internal static string InterruptDelay_helpMark {
            get {
                return ResourceManager.GetString("InterruptDelay_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interrupt Delay 的本地化字符串。
        /// </summary>
        internal static string InterruptDelay_Name {
            get {
                return ResourceManager.GetString("InterruptDelay_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 below 40 (Above that and you start failing to interrupt many short casts) 的本地化字符串。
        /// </summary>
        internal static string InterruptDelay_recommendedValue {
            get {
                return ResourceManager.GetString("InterruptDelay_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % of cast 的本地化字符串。
        /// </summary>
        internal static string InterruptDelay_unitLabel {
            get {
                return ResourceManager.GetString("InterruptDelay_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main UI Options 的本地化字符串。
        /// </summary>
        internal static string MainUIOptions_Category {
            get {
                return ResourceManager.GetString("MainUIOptions_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string MaximumWeavesPerWindow_defaultValue {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls how many oGCDs are allowed between GCDs.
        ///The &apos;default&apos; for the game is double weaving, but triple weaving is completely possible with low enough latency (of every kind);but if you struggle with latency of any sort then single weaving may even be a good answer to try for you.
        ///Triple weaving is already done in a manner where we try to avoid clipping GCDs, and as such doesn&apos;t happen particularly often even if you have good latency, and is a valid thing to do, so it is a safe option if you want. 的本地化字符串。
        /// </summary>
        internal static string MaximumWeavesPerWindow_helpMark {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Number of Weaves 的本地化字符串。
        /// </summary>
        internal static string MaximumWeavesPerWindow_Name {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2-3 的本地化字符串。
        /// </summary>
        internal static string MaximumWeavesPerWindow_recommendedValue {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # of oGCDs 的本地化字符串。
        /// </summary>
        internal static string MaximumWeavesPerWindow_unitLabel {
            get {
                return ResourceManager.GetString("MaximumWeavesPerWindow_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string MeleeOffset_defaultValue {
            get {
                return ResourceManager.GetString("MeleeOffset_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls what is considered to be in melee range.
        ///Mainly for those who don&apos;t want to switch to ranged attacks if the boss walks slightly outside of range.
        ///For example a value of -0.5 would make you have to be 0.5 yalms closer to the target,
        ///or a value of 2 would allow you to be 2 yalms further away and still be considered in melee range
        ///(melee actions wouldn&apos;t work, but it would give you some warning instead of just suddenly doing less optimal actions). 的本地化字符串。
        /// </summary>
        internal static string MeleeOffset_helpMark {
            get {
                return ResourceManager.GetString("MeleeOffset_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Melee Distance Offset 的本地化字符串。
        /// </summary>
        internal static string MeleeOffset_Name {
            get {
                return ResourceManager.GetString("MeleeOffset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string MeleeOffset_recommendedValue {
            get {
                return ResourceManager.GetString("MeleeOffset_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yalms 的本地化字符串。
        /// </summary>
        internal static string MeleeOffset_unitLabel {
            get {
                return ResourceManager.GetString("MeleeOffset_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string MovementLeeway_defaultValue {
            get {
                return ResourceManager.GetString("MovementLeeway_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This controls how long of a delay is needed before Wrath recognizes you as moving.
        ///This allows you to not have to worry about small movements affecting your rotation, primarily for casters. 的本地化字符串。
        /// </summary>
        internal static string MovementLeeway_helpMark {
            get {
                return ResourceManager.GetString("MovementLeeway_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movement Check Delay 的本地化字符串。
        /// </summary>
        internal static string MovementLeeway_Name {
            get {
                return ResourceManager.GetString("MovementLeeway_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.0-1.0 (Above that gets into the territory of breaking any Movement Options in your Job) 的本地化字符串。
        /// </summary>
        internal static string MovementLeeway_recommendedValue {
            get {
                return ResourceManager.GetString("MovementLeeway_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 seconds 的本地化字符串。
        /// </summary>
        internal static string MovementLeeway_unitLabel {
            get {
                return ResourceManager.GetString("MovementLeeway_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string OpenerTimeout_defaultValue {
            get {
                return ResourceManager.GetString("OpenerTimeout_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls how long of a gap with no action is allowed in an Opener, before it is considered failed and normal rotation is resumed.
        ///Can be necessary for some casters to increase, particularly when the first action of an Opener is a hard-cast. 的本地化字符串。
        /// </summary>
        internal static string OpenerTimeout_helpMark {
            get {
                return ResourceManager.GetString("OpenerTimeout_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opener Failure Timeout 的本地化字符串。
        /// </summary>
        internal static string OpenerTimeout_Name {
            get {
                return ResourceManager.GetString("OpenerTimeout_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.0-7.0 (Above that can really screw Openers) 的本地化字符串。
        /// </summary>
        internal static string OpenerTimeout_recommendedValue {
            get {
                return ResourceManager.GetString("OpenerTimeout_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 seconds 的本地化字符串。
        /// </summary>
        internal static string OpenerTimeout_unitLabel {
            get {
                return ResourceManager.GetString("OpenerTimeout_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string OpenToCurrentJob_defaultValue {
            get {
                return ResourceManager.GetString("OpenToCurrentJob_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When the PvE Features tab is opened it will automatically open to your current Job. 的本地化字符串。
        /// </summary>
        internal static string OpenToCurrentJob_helpMark {
            get {
                return ResourceManager.GetString("OpenToCurrentJob_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open PvE Features Tab to Current Job on Opening 的本地化字符串。
        /// </summary>
        internal static string OpenToCurrentJob_Name {
            get {
                return ResourceManager.GetString("OpenToCurrentJob_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string OpenToCurrentJob_recommendedValue {
            get {
                return ResourceManager.GetString("OpenToCurrentJob_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string OpenToCurrentJobOnSwitch_defaultValue {
            get {
                return ResourceManager.GetString("OpenToCurrentJobOnSwitch_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will automatically switch the PvE Features tab to the job you are currently playing, when you switch jobs. 的本地化字符串。
        /// </summary>
        internal static string OpenToCurrentJobOnSwitch_helpMark {
            get {
                return ResourceManager.GetString("OpenToCurrentJobOnSwitch_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open PvE Features Tab to Current Job on Switching Jobs 的本地化字符串。
        /// </summary>
        internal static string OpenToCurrentJobOnSwitch_Name {
            get {
                return ResourceManager.GetString("OpenToCurrentJobOnSwitch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string OpenToCurrentJobOnSwitch_recommendedValue {
            get {
                return ResourceManager.GetString("OpenToCurrentJobOnSwitch_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string OpenToPvE_defaultValue {
            get {
                return ResourceManager.GetString("OpenToPvE_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When you open Wrath with `/wrath`, it will open to the PvE Features tab, instead of the last tab you were on.
        ///Same as always using the `/wrath pve` command to open Wrath. 的本地化字符串。
        /// </summary>
        internal static string OpenToPvE_helpMark {
            get {
                return ResourceManager.GetString("OpenToPvE_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Wrath to the PvE Features Tab 的本地化字符串。
        /// </summary>
        internal static string OpenToPvE_Name {
            get {
                return ResourceManager.GetString("OpenToPvE_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string OpenToPvE_recommendedValue {
            get {
                return ResourceManager.GetString("OpenToPvE_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string OpenToPvP_defaultValue {
            get {
                return ResourceManager.GetString("OpenToPvP_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same as above, when you open Wrath with `/wrath`, it will open to the PvP Features tab, instead of the last tab you were on, when in a PvP area.
        ///Similar to using the `/wrath pvp` command to open Wrath. 的本地化字符串。
        /// </summary>
        internal static string OpenToPvP_helpMark {
            get {
                return ResourceManager.GetString("OpenToPvP_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Wrath to the PvP Features Tab in PvP areas 的本地化字符串。
        /// </summary>
        internal static string OpenToPvP_Name {
            get {
                return ResourceManager.GetString("OpenToPvP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string OpenToPvP_recommendedValue {
            get {
                return ResourceManager.GetString("OpenToPvP_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string OutputOpenerLogs_defaultValue {
            get {
                return ResourceManager.GetString("OutputOpenerLogs_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will print the status of your Job&apos;s Opener to chat.
        ///e.g. When it is Ready, Fails, or Finishes. 的本地化字符串。
        /// </summary>
        internal static string OutputOpenerLogs_helpMark {
            get {
                return ResourceManager.GetString("OutputOpenerLogs_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Opener Status to Chat 的本地化字符串。
        /// </summary>
        internal static string OutputOpenerLogs_Name {
            get {
                return ResourceManager.GetString("OutputOpenerLogs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On (IF trying to troubleshoot an Opener) 的本地化字符串。
        /// </summary>
        internal static string OutputOpenerLogs_recommendedValue {
            get {
                return ResourceManager.GetString("OutputOpenerLogs_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string OverwriteQueue_defaultValue {
            get {
                return ResourceManager.GetString("OverwriteQueue_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will allow you to overwrite whatever is currently queued up with another action. 的本地化字符串。
        /// </summary>
        internal static string OverwriteQueue_helpMark {
            get {
                return ResourceManager.GetString("OverwriteQueue_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite Queue 的本地化字符串。
        /// </summary>
        internal static string OverwriteQueue_Name {
            get {
                return ResourceManager.GetString("OverwriteQueue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string OverwriteQueue_recommendedValue {
            get {
                return ResourceManager.GetString("OverwriteQueue_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string QueueAdjust_defaultValue {
            get {
                return ResourceManager.GetString("QueueAdjust_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows you to adjust your queue window to any time during the GCD rather than just within the last 0.3-0.5s. Useful if you&apos;re not mashing the key or using Auto-Rotation and wish to manually intervene. 的本地化字符串。
        /// </summary>
        internal static string QueueAdjust_helpMark {
            get {
                return ResourceManager.GetString("QueueAdjust_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Manual Queue Window 的本地化字符串。
        /// </summary>
        internal static string QueueAdjust_Name {
            get {
                return ResourceManager.GetString("QueueAdjust_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string QueueAdjust_recommendedValue {
            get {
                return ResourceManager.GetString("QueueAdjust_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.5 的本地化字符串。
        /// </summary>
        internal static string QueueAdjustThreshold_defaultValue {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will allow you to queue when the GCD is at this time or less. 的本地化字符串。
        /// </summary>
        internal static string QueueAdjustThreshold_helpMark {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Queueing At 的本地化字符串。
        /// </summary>
        internal static string QueueAdjustThreshold_Name {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.5-2.5 的本地化字符串。
        /// </summary>
        internal static string QueueAdjustThreshold_recommendedValue {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 seconds 的本地化字符串。
        /// </summary>
        internal static string QueueAdjustThreshold_unitLabel {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting this too low or to zero will make it really hard to manually queue. 的本地化字符串。
        /// </summary>
        internal static string QueueAdjustThreshold_warningMark {
            get {
                return ResourceManager.GetString("QueueAdjustThreshold_warningMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any Healer &gt; Any Tank &gt; Any Raiser &gt; Any Dead Party Member 的本地化字符串。
        /// </summary>
        internal static string RaiseStack_defaultValue {
            get {
                return ResourceManager.GetString("RaiseStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (all targets are checked for rezz-ability) 的本地化字符串。
        /// </summary>
        internal static string RaiseStack_extraText {
            get {
                return ResourceManager.GetString("RaiseStack_extraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is the order in which Wrath will try to select a target to Raise,
        ///if Retargeting of any Raise Feature is enabled.
        ///
        ///You can find Raise Features under PvE&gt;General,
        ///or under each caster that has a Raise.
        ///
        ///If there are fewer than 5 items, and all return nothing when checked, will fall back to:
        ///your Hard Target if they&apos;re dead, or &lt;Any Dead Party Member&gt;.
        ///
        ///These targets will only be considered valid if they are friendly, dead, and within 30y. 的本地化字符串。
        /// </summary>
        internal static string RaiseStack_helpMark {
            get {
                return ResourceManager.GetString("RaiseStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Raise Stack 的本地化字符串。
        /// </summary>
        internal static string RaiseStack_Name {
            get {
                return ResourceManager.GetString("RaiseStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string RaiseStack_recommendedValue {
            get {
                return ResourceManager.GetString("RaiseStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string RetargetHealingActionsToStack_defaultValue {
            get {
                return ResourceManager.GetString("RetargetHealingActionsToStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will Retarget all Single-Target Healing Actions to the Heal Stack as shown below,
        ///similarly to how Redirect or Reaction would.
        ///This ensures that the target used to check HP% threshold logic for healing actions is the same target that will receive that heal. 的本地化字符串。
        /// </summary>
        internal static string RetargetHealingActionsToStack_helpMark {
            get {
                return ResourceManager.GetString("RetargetHealingActionsToStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retarget (Single Target) Healing Actions 的本地化字符串。
        /// </summary>
        internal static string RetargetHealingActionsToStack_Name {
            get {
                return ResourceManager.GetString("RetargetHealingActionsToStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On (If you customize the Heal Stack AT ALL) 的本地化字符串。
        /// </summary>
        internal static string RetargetHealingActionsToStack_recommendedValue {
            get {
                return ResourceManager.GetString("RetargetHealingActionsToStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation Behaviour Options 的本地化字符串。
        /// </summary>
        internal static string RotationBehaviourOptions_Category {
            get {
                return ResourceManager.GetString("RotationBehaviourOptions_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string ShortDTRText_defaultValue {
            get {
                return ResourceManager.GetString("ShortDTRText_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will hide the number of active Auto-Mode Combos.
        ///By default the Server Info Bar shows:
        ///- Whether Auto-Rotation is on or off
        ///- (if on) The number of active Auto-Mode Combos
        ///- (if applicable) Whether another plugin is controlling the state of Auto-Rotation. 的本地化字符串。
        /// </summary>
        internal static string ShortDTRText_helpMark {
            get {
                return ResourceManager.GetString("ShortDTRText_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shorten Server Info Bar Text 的本地化字符串。
        /// </summary>
        internal static string ShortDTRText_Name {
            get {
                return ResourceManager.GetString("ShortDTRText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string ShortDTRText_recommendedValue {
            get {
                return ResourceManager.GetString("ShortDTRText_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string ShowBorderAroundOptionsWithChildren_defaultValue {
            get {
                return ResourceManager.GetString("ShowBorderAroundOptionsWithChildren_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will draw a border around Combos and Features that have Features and Options of their own. 的本地化字符串。
        /// </summary>
        internal static string ShowBorderAroundOptionsWithChildren_helpMark {
            get {
                return ResourceManager.GetString("ShowBorderAroundOptionsWithChildren_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Borders around Combos and Features with Options 的本地化字符串。
        /// </summary>
        internal static string ShowBorderAroundOptionsWithChildren_Name {
            get {
                return ResourceManager.GetString("ShowBorderAroundOptionsWithChildren_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string ShowBorderAroundOptionsWithChildren_recommendedValue {
            get {
                return ResourceManager.GetString("ShowBorderAroundOptionsWithChildren_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string ShowOpenerDtr_defaultValue {
            get {
                return ResourceManager.GetString("ShowOpenerDtr_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shows the status of your current opener, if enabled and applicable. 的本地化字符串。
        /// </summary>
        internal static string ShowOpenerDtr_helpMark {
            get {
                return ResourceManager.GetString("ShowOpenerDtr_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opener Status in Server Info Bar 的本地化字符串。
        /// </summary>
        internal static string ShowOpenerDtr_Name {
            get {
                return ResourceManager.GetString("ShowOpenerDtr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string ShowOpenerDtr_recommendedValue {
            get {
                return ResourceManager.GetString("ShowOpenerDtr_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string ShowTargetHighlight_defaultValue {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Only used by AST and DNC currently) 的本地化字符串。
        /// </summary>
        internal static string ShowTargetHighlight_extraText {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_extraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draws a box around party members in the vanilla Party List, when targeted by certain Features. 的本地化字符串。
        /// </summary>
        internal static string ShowTargetHighlight_helpMark {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Target Highlighter 的本地化字符串。
        /// </summary>
        internal static string ShowTargetHighlight_Name {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string ShowTargetHighlight_recommendedValue {
            get {
                return ResourceManager.GetString("ShowTargetHighlight_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string SuppressAutorotCommand_defaultValue {
            get {
                return ResourceManager.GetString("SuppressAutorotCommand_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will hide chat feedback for /wrath auto commands 的本地化字符串。
        /// </summary>
        internal static string SuppressAutorotCommand_helpMark {
            get {
                return ResourceManager.GetString("SuppressAutorotCommand_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suppress Auto-Rotation commands feedback 的本地化字符串。
        /// </summary>
        internal static string SuppressAutorotCommand_Name {
            get {
                return ResourceManager.GetString("SuppressAutorotCommand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string SuppressAutorotCommand_recommendedValue {
            get {
                return ResourceManager.GetString("SuppressAutorotCommand_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string SuppressSetCommands_defaultValue {
            get {
                return ResourceManager.GetString("SuppressSetCommands_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will hide chat feedback for /wrath set and /wrath unset commands.
        ///(Will still show feedback if the command is being overriden by IPC, or fails) 的本地化字符串。
        /// </summary>
        internal static string SuppressSetCommands_helpMark {
            get {
                return ResourceManager.GetString("SuppressSetCommands_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suppress Set and Unset commands feedback 的本地化字符串。
        /// </summary>
        internal static string SuppressSetCommands_Name {
            get {
                return ResourceManager.GetString("SuppressSetCommands_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string SuppressSetCommands_recommendedValue {
            get {
                return ResourceManager.GetString("SuppressSetCommands_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string TankbusterToast_defaultValue {
            get {
                return ResourceManager.GetString("TankbusterToast_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show a message on-screen whenever a tankbuster is detected, including who it is targeting. 的本地化字符串。
        /// </summary>
        internal static string TankbusterToast_helpMark {
            get {
                return ResourceManager.GetString("TankbusterToast_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Toast on Tankbuster 的本地化字符串。
        /// </summary>
        internal static string TankbusterToast_Name {
            get {
                return ResourceManager.GetString("TankbusterToast_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string TankbusterToast_recommendedValue {
            get {
                return ResourceManager.GetString("TankbusterToast_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string TankbusterTTS_defaultValue {
            get {
                return ResourceManager.GetString("TankbusterTTS_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will play a text-to-speech sound clip whenever a tankbuster is detected, including who it is targeting. 的本地化字符串。
        /// </summary>
        internal static string TankbusterTTS_helpMark {
            get {
                return ResourceManager.GetString("TankbusterTTS_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play TTS on Tankbuster 的本地化字符串。
        /// </summary>
        internal static string TankbusterTTS_Name {
            get {
                return ResourceManager.GetString("TankbusterTTS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string TankbusterTTS_recommendedValue {
            get {
                return ResourceManager.GetString("TankbusterTTS_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #808080FF 的本地化字符串。
        /// </summary>
        internal static string TargetHighlightColor_defaultValue {
            get {
                return ResourceManager.GetString("TargetHighlightColor_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls the color of the box drawn around party members. 的本地化字符串。
        /// </summary>
        internal static string TargetHighlightColor_helpMark {
            get {
                return ResourceManager.GetString("TargetHighlightColor_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Highlighter Color 的本地化字符串。
        /// </summary>
        internal static string TargetHighlightColor_Name {
            get {
                return ResourceManager.GetString("TargetHighlightColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string TargetHighlightColor_recommendedValue {
            get {
                return ResourceManager.GetString("TargetHighlightColor_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Targeting Options 的本地化字符串。
        /// </summary>
        internal static string TargetingOptions_Category {
            get {
                return ResourceManager.GetString("TargetingOptions_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 50 的本地化字符串。
        /// </summary>
        internal static string Throttle_defaultValue {
            get {
                return ResourceManager.GetString("Throttle_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will restrict how often Combos will update the Action on your Hotbar.
        ///At 50ms it&apos;s not really restrictive, always giving you an up to date action.
        ///
        ///If you are looking for some (fairly minor) FPS gains then you can increase this value to make Combos run less often.
        ///This makes your combos less responsive, and perhaps even clips GCDs.
        ///At high values this will clip your GCDs by several seconds or break your rotation altogether. 的本地化字符串。
        /// </summary>
        internal static string Throttle_helpMark {
            get {
                return ResourceManager.GetString("Throttle_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action Updater Throttle 的本地化字符串。
        /// </summary>
        internal static string Throttle_Name {
            get {
                return ResourceManager.GetString("Throttle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20-200 的本地化字符串。
        /// </summary>
        internal static string Throttle_recommendedValue {
            get {
                return ResourceManager.GetString("Throttle_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 milliseconds 的本地化字符串。
        /// </summary>
        internal static string Throttle_unitLabel {
            get {
                return ResourceManager.GetString("Throttle_unitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Troubleshooting Options 的本地化字符串。
        /// </summary>
        internal static string TroubleshootingOptions_Category {
            get {
                return ResourceManager.GetString("TroubleshootingOptions_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string UIShowPresetIDs_defaultValue {
            get {
                return ResourceManager.GetString("UIShowPresetIDs_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displays the Preset ID number next to the name of each Combo and Feature.
        ///These are the IDs used for commands like `/wrath toggle &lt;ID&gt;`.
        ///Pre-7.3 the behavior was to show a number here, but it was much shorter, and did not work in commands. 的本地化字符串。
        /// </summary>
        internal static string UIShowPresetIDs_helpMark {
            get {
                return ResourceManager.GetString("UIShowPresetIDs_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Preset IDs next to Combo Names 的本地化字符串。
        /// </summary>
        internal static string UIShowPresetIDs_Name {
            get {
                return ResourceManager.GetString("UIShowPresetIDs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string UIShowPresetIDs_recommendedValue {
            get {
                return ResourceManager.GetString("UIShowPresetIDs_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string UIShowSearchBar_defaultValue {
            get {
                return ResourceManager.GetString("UIShowSearchBar_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controls whether Search Bars should be shown in Settings, and PvE and PvP Jobs. 的本地化字符串。
        /// </summary>
        internal static string UIShowSearchBar_helpMark {
            get {
                return ResourceManager.GetString("UIShowSearchBar_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Search Bars 的本地化字符串。
        /// </summary>
        internal static string UIShowSearchBar_Name {
            get {
                return ResourceManager.GetString("UIShowSearchBar_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string UIShowSearchBar_recommendedValue {
            get {
                return ResourceManager.GetString("UIShowSearchBar_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string UseCustomHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseCustomHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select this if you would rather make your own stack of target priorities for Heal Targets instead of using our default stack.
        ///
        ///It is recommended to use this to align with your Redirect/Reaction configuration IF you&apos;re not using the Retarget Healing Actions option above; otherwise it is preference. 的本地化字符串。
        /// </summary>
        internal static string UseCustomHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseCustomHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use a Custom Heal Stack Instead 的本地化字符串。
        /// </summary>
        internal static string UseCustomHealStack_Name {
            get {
                return ResourceManager.GetString("UseCustomHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string UseCustomHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseCustomHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string UseFieldMouseoverOverridesInDefaultHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseFieldMouseoverOverridesInDefaultHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add any MouseOver targets to the top of the Default Heal Stack, overriding the rest of the stack if you are mousing over any party member UI.
        ///
        ///It is recommended to enable this if you are a keyboard+mouse user and enable Retarget Healing Actions (or have UI MouseOver targets in your Redirect/Reaction configuration). 的本地化字符串。
        /// </summary>
        internal static string UseFieldMouseoverOverridesInDefaultHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseFieldMouseoverOverridesInDefaultHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Field MouseOver to the Default Healing Stack 的本地化字符串。
        /// </summary>
        internal static string UseFieldMouseoverOverridesInDefaultHealStack_Name {
            get {
                return ResourceManager.GetString("UseFieldMouseoverOverridesInDefaultHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string UseFieldMouseoverOverridesInDefaultHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseFieldMouseoverOverridesInDefaultHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string UseFocusTargetOverrideInDefaultHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseFocusTargetOverrideInDefaultHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will add your focus target under your hard and soft targets in the Default Heal Stack, overriding the rest of the stack if you have a living focus target. 的本地化字符串。
        /// </summary>
        internal static string UseFocusTargetOverrideInDefaultHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseFocusTargetOverrideInDefaultHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Focus Target to the Default Healing Stack 的本地化字符串。
        /// </summary>
        internal static string UseFocusTargetOverrideInDefaultHealStack_Name {
            get {
                return ResourceManager.GetString("UseFocusTargetOverrideInDefaultHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string UseFocusTargetOverrideInDefaultHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseFocusTargetOverrideInDefaultHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will add a nearby party member with the lowest HP% to bottom of the Default Heal Stack, overriding only yourself. 的本地化字符串。
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Lowest HP% Ally to the Default Healing Stack 的本地化字符串。
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_Name {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_recommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlike the other Default+ Options, this one is not an option in most other Retargeting Plugins.
        ///THIS SHOULD BE USED WITH THE &apos;RETARGET HEALING ACTIONS&apos; SETTING ABOVE! 的本地化字符串。
        /// </summary>
        internal static string UseLowestHPOverrideInDefaultHealStack_warningMark {
            get {
                return ResourceManager.GetString("UseLowestHPOverrideInDefaultHealStack_warningMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string UseUIMouseoverOverridesInDefaultHealStack_defaultValue {
            get {
                return ResourceManager.GetString("UseUIMouseoverOverridesInDefaultHealStack_defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will add any UI MouseOver targets to the top of the Default Heal Stack, overriding the rest of the stack if you are mousing over any party member UI.
        ///
        ///It is recommended to enable this if you are a keyboard+mouse user and enable Retarget Healing Actions (or have UI MouseOver targets in your Redirect/Reaction configuration). 的本地化字符串。
        /// </summary>
        internal static string UseUIMouseoverOverridesInDefaultHealStack_helpMark {
            get {
                return ResourceManager.GetString("UseUIMouseoverOverridesInDefaultHealStack_helpMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add UI MouseOver to the Default Healing Stack 的本地化字符串。
        /// </summary>
        internal static string UseUIMouseoverOverridesInDefaultHealStack_Name {
            get {
                return ResourceManager.GetString("UseUIMouseoverOverridesInDefaultHealStack_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preference 的本地化字符串。
        /// </summary>
        internal static string UseUIMouseoverOverridesInDefaultHealStack_recommendedValue {
            get {
                return ResourceManager.GetString("UseUIMouseoverOverridesInDefaultHealStack_recommendedValue", resourceCulture);
            }
        }
    }
}
